import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/squash_models.dart';

/// Perfil Universal BIO-G de calabaza (v2).
///
/// Contiene targets sensoriales y pesos de score por etapa para la
/// familia `crop_squash`. La fuente principal son las secciones 5 (rangos
/// fisiológicos) y 10 (ponderación AgroScore) del Perfil Universal v2.
///
/// IMPORTANTE para v1:
/// - La fertilización activa sigue siendo NPK. Ca/Mg/S reciben prioridad
///   informativa pero no generan dosis ni alertas principales.
/// - Polinización, calor en floración y K desde cuajado son los cuellos
///   reales del cultivo; los pesos de etapa los reflejan.
class SquashUniversalProfile {
  const SquashUniversalProfile({
    required this.byStage,
    required this.weights,
  });

  final Map<SquashStageKey, StageTargets> byStage;
  final Map<SquashStageKey, StageWeights> weights;
}

// ─────────────────────────────────────────────────────────────────────
// Rangos sensoriales BIO-G v2 §5.
// pH 6.0-7.2 base; tolera 5.5-7.6. EC <1.8 dS/m segura, >2.5 alerta.
// Suelo cálido obligatorio para germinación (>=15 °C). Resistencia
// fuerte como riesgo en establecimiento por anoxia.
// ─────────────────────────────────────────────────────────────────────
const AgroRange _phEarly = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 7.0,
  highMin: 7.5,
);

const AgroRange _phStd = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 7.2,
  highMin: 7.6,
);

const AgroRange _phReproductive = AgroRange(
  lowMax: 5.8,
  optimalMin: 6.0,
  optimalMax: 7.2,
  highMin: 7.6,
);

const AgroRange _ecEarly = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecStd = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.8,
  highMin: 2.5,
);

const AgroRange _ecReproductive = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.8,
  highMin: 2.5,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 2.0,
  highMin: 3.0,
);

// La raíz de cucurbitácea explora lateralmente; compactación + humedad
// alta reduce oxígeno. <1.5 MPa óptimo; >2.0 MPa alerta.
const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

// Suelo cálido obligatorio: <15 °C en germinación es alerta crítica.
const AgroRange _soilTempEarly = AgroRange(
  lowMax: 15,
  optimalMin: 18,
  optimalMax: 30,
  highMin: 32,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 15,
  optimalMin: 18,
  optimalMax: 30,
  highMin: 33,
);

// Agua disponible 60-90% óptimo; <50% en flor/cuajado es crítico.
const AgroRange _moistureActive = AgroRange(
  lowMax: 50,
  optimalMin: 60,
  optimalMax: 90,
  highMin: 95,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required double caPriority,
  required double mgPriority,
  required double sPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  required String caGuide,
  required String mgGuide,
  required String sGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.78,
}) {
  AgroRange idx(double p) => AgroRange(
        lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
        optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
        optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
        highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
      );

  AgroRange ppm(double low, double min, double max) => AgroRange(
        lowMax: low,
        optimalMin: min,
        optimalMax: max,
        highMin: max + (max - min) * 0.55,
      );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: caPriority,
    mgPriority: mgPriority,
    sPriority: sPriority,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs: caGuide,
    mgShortGuidanceEs: mgGuide,
    sShortGuidanceEs: sGuide,
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final SquashUniversalProfile squashUniversalV1 = SquashUniversalProfile(
  byStage: <SquashStageKey, StageTargets>{
    SquashStageKey.germinacion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 18,
      nOptMin: 22,
      nOptMax: 45,
      pLow: 35,
      pOptMin: 45,
      pOptMax: 70,
      kLow: 55,
      kOptMin: 70,
      kOptMax: 110,
      nPriority: 0.18,
      pPriority: 0.55,
      kPriority: 0.25,
      caPriority: 0.30,
      mgPriority: 0.25,
      sPriority: 0.20,
      nWindow: 'Arranque sin presión de N',
      pWindow: 'Soporte mínimo de raíz',
      kWindow: 'Reserva mínima',
      nGuide: 'No empujar N en germinación; sales bajas mandan.',
      pGuide: 'P apenas como base; raíz aún corta.',
      kGuide: 'K solo en mínimos; cuidar CE.',
      caGuide: 'Ca de base como contexto.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S sin protagonismo.',
      confidence: 0.70,
    ),
    SquashStageKey.establecimiento: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 28,
      nOptMin: 36,
      nOptMax: 60,
      pLow: 40,
      pOptMin: 50,
      pOptMax: 76,
      kLow: 65,
      kOptMin: 80,
      kOptMax: 120,
      nPriority: 0.40,
      pPriority: 0.78,
      kPriority: 0.42,
      caPriority: 0.45,
      mgPriority: 0.32,
      sPriority: 0.26,
      nWindow: 'Soporte moderado',
      pWindow: 'Pegue y raíz',
      kWindow: 'Balance inicial',
      nGuide: 'N acompaña sin forzar guía.',
      pGuide: 'P starter es clave para raíz.',
      kGuide: 'K como balance temprano.',
      caGuide: 'Ca y Mg como contexto agronómico.',
      mgGuide: 'Mg apoya hojas iniciales.',
      sGuide: 'S en soporte base.',
      nHint: 'Evitar pulsos altos de N en raíz joven.',
      pHint: 'Corregir P temprano si la lectura queda corta.',
      kHint: 'Mantener K base sin subir sales.',
      confidence: 0.80,
    ),
    SquashStageKey.vegetativo: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStd,
      nLow: 50,
      nOptMin: 62,
      nOptMax: 96,
      pLow: 32,
      pOptMin: 42,
      pOptMax: 65,
      kLow: 85,
      kOptMin: 105,
      kOptMax: 155,
      nPriority: 0.74,
      pPriority: 0.48,
      kPriority: 0.58,
      caPriority: 0.50,
      mgPriority: 0.48,
      sPriority: 0.34,
      nWindow: 'Follaje y guía',
      pWindow: 'Soporte de P',
      kWindow: 'Reserva antes de flor',
      nGuide: 'N para hoja, sin retrasar floración por exceso.',
      pGuide: 'P pasa a soporte.',
      kGuide: 'K sube de cara a floración.',
      caGuide: 'Ca como contexto, no dosis.',
      mgGuide: 'Mg sostiene fotosíntesis.',
      sGuide: 'S apoya vigor general.',
      nHint: 'No llegar a flor con planta vegetada de más.',
      kHint: 'Preparar reserva de K antes de cuajado.',
      confidence: 0.84,
    ),
    SquashStageKey.floracion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phReproductive,
      ec: _ecReproductive,
      nLow: 42,
      nOptMin: 50,
      nOptMax: 80,
      pLow: 32,
      pOptMin: 40,
      pOptMax: 64,
      kLow: 100,
      kOptMin: 125,
      kOptMax: 170,
      nPriority: 0.55,
      pPriority: 0.60,
      kPriority: 0.74,
      caPriority: 0.62,
      mgPriority: 0.52,
      sPriority: 0.38,
      nWindow: 'N moderado en flor',
      pWindow: 'Energía reproductiva',
      kWindow: 'K subiendo para amarre',
      nGuide: 'N estable: exceso castiga relación macho/hembra.',
      pGuide: 'P sostiene energía de flor.',
      kGuide: 'K empieza a mandar; humedad pareja es clave.',
      caGuide: 'Ca como contexto de calidad.',
      mgGuide: 'Mg sostiene hoja activa.',
      sGuide: 'S acompaña.',
      nHint: 'No subir N como reflejo: revisar polinización primero.',
      pHint: 'P solo si la lectura lo justifica.',
      kHint: 'Subir K sin golpes salinos.',
      confidence: 0.86,
    ),
    SquashStageKey.cuajado: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phReproductive,
      ec: _ecReproductive,
      nLow: 38,
      nOptMin: 46,
      nOptMax: 74,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 58,
      kLow: 115,
      kOptMin: 140,
      kOptMax: 190,
      nPriority: 0.50,
      pPriority: 0.50,
      kPriority: 0.86,
      caPriority: 0.68,
      mgPriority: 0.55,
      sPriority: 0.40,
      nWindow: 'N moderado para cuaje',
      pWindow: 'P de soporte',
      kWindow: 'K fuerte para amarre',
      nGuide: 'N controlado: exceso resta amarre.',
      pGuide: 'P acompaña, no rescata tarde.',
      kGuide: 'K, agua y polinización dominan el amarre.',
      caGuide: 'Ca como contexto de calidad.',
      mgGuide: 'Mg sostiene hoja cargada.',
      sGuide: 'S en soporte.',
      nHint: 'No meter pulsos altos de N en amarre activo.',
      kHint: 'Si K cae, corregir con humedad estable.',
      confidence: 0.88,
    ),
    SquashStageKey.llenado: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecReproductive,
      nLow: 32,
      nOptMin: 40,
      nOptMax: 70,
      pLow: 26,
      pOptMin: 34,
      pOptMax: 56,
      kLow: 125,
      kOptMin: 150,
      kOptMax: 205,
      nPriority: 0.46,
      pPriority: 0.40,
      kPriority: 0.94,
      caPriority: 0.66,
      mgPriority: 0.58,
      sPriority: 0.42,
      nWindow: 'N a la baja',
      pWindow: 'P de mantenimiento',
      kWindow: 'K dominante en llenado',
      nGuide: 'N baja; exceso abre vegetatividad y abre fruto a podredumbre.',
      pGuide: 'P de soporte; respuesta moderada.',
      kGuide: 'K manda peso, color, firmeza y vida de almacén.',
      caGuide: 'Ca como contexto de calidad de fruto.',
      mgGuide: 'Mg sostiene llenado desde hoja sana.',
      sGuide: 'S acompaña.',
      nHint: 'No perseguir N como cuello en llenado.',
      kHint: 'Priorizar K soluble fraccionado, sin golpes osmóticos.',
      confidence: 0.88,
    ),
    SquashStageKey.cosechaProgresiva: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecReproductive,
      nLow: 28,
      nOptMin: 36,
      nOptMax: 64,
      pLow: 22,
      pOptMin: 30,
      pOptMax: 52,
      kLow: 115,
      kOptMin: 140,
      kOptMax: 195,
      nPriority: 0.42,
      pPriority: 0.34,
      kPriority: 0.84,
      caPriority: 0.58,
      mgPriority: 0.50,
      sPriority: 0.36,
      nWindow: 'N de mantenimiento',
      pWindow: 'P de mantenimiento',
      kWindow: 'K sostenido en cosecha',
      nGuide: 'N solo para sostener cortes productivos en calabacita.',
      pGuide: 'P rara vez es el cuello en cosecha.',
      kGuide: 'K sostenido mantiene continuidad y calidad.',
      caGuide: 'Ca como contexto de firmeza.',
      mgGuide: 'Mg sostiene hoja funcional.',
      sGuide: 'S en soporte.',
      nHint: 'En fruto maduro, bajar N para no retrasar madurez/cáscara.',
      kHint: 'Mantener K constante y balanceado.',
      confidence: 0.82,
    ),
    SquashStageKey.finCiclo: _targets(
      moisture: const AgroRange(
        lowMax: 22,
        optimalMin: 35,
        optimalMax: 60,
        highMin: 75,
      ),
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 16,
      nOptMin: 20,
      nOptMax: 42,
      pLow: 18,
      pOptMin: 24,
      pOptMax: 48,
      kLow: 70,
      kOptMin: 90,
      kOptMax: 145,
      nPriority: 0.18,
      pPriority: 0.16,
      kPriority: 0.30,
      caPriority: 0.22,
      mgPriority: 0.20,
      sPriority: 0.18,
      nWindow: 'Cierre de N',
      pWindow: 'Cierre de P',
      kWindow: 'Cierre de K',
      nGuide: 'No corregir N tarde; documentar y cerrar.',
      pGuide: 'Usar la lectura para la base del siguiente ciclo.',
      kGuide: 'K solo sostiene cosecha residual.',
      caGuide: 'Ca informativo; v1 no genera dosis.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S en mantenimiento.',
      nHint: 'No invertir tarde; reservar para pre-siembra.',
      pHint: 'Usar lectura para pre-siembra del siguiente ciclo.',
      kHint: 'Documentar para trazabilidad del plan.',
      confidence: 0.66,
    ),
  },
  // Pesos por etapa según Perfil Universal v2 §10.
  // Floración y cuajado: agua + temperatura suben fuerte; el bloque
  // npk pesa moderado para no opacar la señal de polinización.
  weights: const <SquashStageKey, StageWeights>{
    SquashStageKey.germinacion: StageWeights(
      moisture: 0.34,
      soilTemp: 0.18,
      resistance: 0.10,
      ph: 0.10,
      ec: 0.12,
      npk: 0.16,
    ),
    SquashStageKey.establecimiento: StageWeights(
      moisture: 0.30,
      soilTemp: 0.12,
      resistance: 0.18,
      ph: 0.10,
      ec: 0.12,
      npk: 0.18,
    ),
    SquashStageKey.vegetativo: StageWeights(
      moisture: 0.26,
      soilTemp: 0.10,
      resistance: 0.12,
      ph: 0.10,
      ec: 0.12,
      npk: 0.30,
    ),
    SquashStageKey.floracion: StageWeights(
      moisture: 0.32,
      soilTemp: 0.16,
      resistance: 0.06,
      ph: 0.08,
      ec: 0.14,
      npk: 0.24,
    ),
    SquashStageKey.cuajado: StageWeights(
      moisture: 0.34,
      soilTemp: 0.14,
      resistance: 0.06,
      ph: 0.08,
      ec: 0.14,
      npk: 0.24,
    ),
    SquashStageKey.llenado: StageWeights(
      moisture: 0.30,
      soilTemp: 0.10,
      resistance: 0.06,
      ph: 0.08,
      ec: 0.14,
      npk: 0.32,
    ),
    SquashStageKey.cosechaProgresiva: StageWeights(
      moisture: 0.26,
      soilTemp: 0.08,
      resistance: 0.06,
      ph: 0.08,
      ec: 0.14,
      npk: 0.38,
    ),
    SquashStageKey.finCiclo: StageWeights(
      moisture: 0.22,
      soilTemp: 0.06,
      resistance: 0.10,
      ph: 0.12,
      ec: 0.14,
      npk: 0.36,
    ),
  },
);
