// Proposed file generated from catalogo_biog_corregido_rendimiento.csv
// Source status: V=validated, C=calibrated, M=modeled

enum YieldDataConfidence { validated, calibrated, modeled }

class YieldReference {
  final String id;
  final String cropId;
  final String useType;
  final String displayName;
  final double yieldLowTonPerHa;
  final double yieldHighTonPerHa;
  final double seedsLowPerHa;
  final double seedsHighPerHa;
  final bool isFreshMatter;
  final YieldDataConfidence confidence;
  final String sourceMethod;

  const YieldReference({
    required this.id,
    required this.cropId,
    required this.useType,
    required this.displayName,
    required this.yieldLowTonPerHa,
    required this.yieldHighTonPerHa,
    required this.seedsLowPerHa,
    required this.seedsHighPerHa,
    required this.isFreshMatter,
    required this.confidence,
    required this.sourceMethod,
  });
}

class YieldReferenceCatalog {
  static const Map<String, YieldReference> byId = <String, YieldReference>{
    'asgrow_antilope_forage': const YieldReference(
      id: 'asgrow_antilope_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'ANTÍLOPE',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 95000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial ASGROW Occidente',
    ),
    'asgrow_antilope_grain': const YieldReference(
      id: 'asgrow_antilope_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'ANTÍLOPE',
      yieldLowTonPerHa: 16.2,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 95000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial ASGROW Occidente',
    ),
    'asgrow_antilope_grain_long': const YieldReference(
      id: 'asgrow_antilope_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'ANTÍLOPE',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_armadillo_forage': const YieldReference(
      id: 'asgrow_armadillo_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'ARMADILLO',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_hipopotamo_forage': const YieldReference(
      id: 'asgrow_hipopotamo_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'HIPOPÓTAMO',
      yieldLowTonPerHa: 90,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rinoceronte_forage': const YieldReference(
      id: 'asgrow_rinoceronte_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'RINOCERONTE',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rinoceronte_grain_long': const YieldReference(
      id: 'asgrow_rinoceronte_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'RINOCERONTE',
      yieldLowTonPerHa: 17,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_berrendo_forage': const YieldReference(
      id: 'asgrow_berrendo_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'BERRENDO',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_berrendo_grain_long': const YieldReference(
      id: 'asgrow_berrendo_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'BERRENDO',
      yieldLowTonPerHa: 17,
      yieldHighTonPerHa: 17.8,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_cimarron_grain_long': const YieldReference(
      id: 'asgrow_cimarron_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'CIMARRÓN',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_ocelote_grain': const YieldReference(
      id: 'asgrow_ocelote_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'OCELOTE',
      yieldLowTonPerHa: 9.5,
      yieldHighTonPerHa: 11,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_tigrillo_grain': const YieldReference(
      id: 'asgrow_tigrillo_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'TIGRILLO',
      yieldLowTonPerHa: 11,
      yieldHighTonPerHa: 13,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_salamandra_grain_short': const YieldReference(
      id: 'asgrow_salamandra_grain_short',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'SALAMANDRA',
      yieldLowTonPerHa: 16.2,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial ASGROW Salamandra',
    ),
    'asgrow_salamandra_grain_long': const YieldReference(
      id: 'asgrow_salamandra_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'SALAMANDRA',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial ASGROW Salamandra',
    ),
    'asgrow_az60_grain_long': const YieldReference(
      id: 'asgrow_az60_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'AZ60',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_faisan_grain_long': const YieldReference(
      id: 'asgrow_faisan_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'FAISÁN',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_albatros_grain_long': const YieldReference(
      id: 'asgrow_albatros_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'ALBATROS',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_antilope_y_grain_long': const YieldReference(
      id: 'asgrow_antilope_y_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'ANTÍLOPE Y',
      yieldLowTonPerHa: 16.8,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 95000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con ficha ASGROW Antílope',
    ),
    'asgrow_rx715_grain': const YieldReference(
      id: 'asgrow_rx715_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'RX-715',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rx717_grain_tropical': const YieldReference(
      id: 'asgrow_rx717_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'RX-717',
      yieldLowTonPerHa: 10.5,
      yieldHighTonPerHa: 12,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rx840_grain': const YieldReference(
      id: 'asgrow_rx840_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'RX-840',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rx860_forage_precoz': const YieldReference(
      id: 'asgrow_rx860_forage_precoz',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'RX-860',
      yieldLowTonPerHa: 70,
      yieldHighTonPerHa: 80,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 92000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_rx860_forage_super': const YieldReference(
      id: 'asgrow_rx860_forage_super',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'RX-860',
      yieldLowTonPerHa: 65,
      yieldHighTonPerHa: 75,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 92000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_a7573_elote': const YieldReference(
      id: 'asgrow_a7573_elote',
      cropId: 'maize',
      useType: 'elote',
      displayName: 'A 7573',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 65000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_a7573_grain': const YieldReference(
      id: 'asgrow_a7573_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'A 7573',
      yieldLowTonPerHa: 8.5,
      yieldHighTonPerHa: 10,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'asgrow_garanon_elote': const YieldReference(
      id: 'asgrow_garanon_elote',
      cropId: 'maize',
      useType: 'elote',
      displayName: 'GARAÑÓN',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 65000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p2327w_forage': const YieldReference(
      id: 'pioneer_p2327w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P2327W',
      yieldLowTonPerHa: 75,
      yieldHighTonPerHa: 82,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p32208w_forage': const YieldReference(
      id: 'pioneer_p32208w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P32208W',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 90,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3274w_forage': const YieldReference(
      id: 'pioneer_p3274w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P3274W',
      yieldLowTonPerHa: 90,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con fichas Pioneer por región',
    ),
    'pioneer_p3274w_grain_oi': const YieldReference(
      id: 'pioneer_p3274w_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3274W',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Fichas oficiales Pioneer por región',
    ),
    'pioneer_p39177w_forage': const YieldReference(
      id: 'pioneer_p39177w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P39177W',
      yieldLowTonPerHa: 80,
      yieldHighTonPerHa: 88,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p39177w_grain_tropical': const YieldReference(
      id: 'pioneer_p39177w_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P39177W',
      yieldLowTonPerHa: 10.5,
      yieldHighTonPerHa: 12,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3966w_forage': const YieldReference(
      id: 'pioneer_p3966w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P3966W',
      yieldLowTonPerHa: 82,
      yieldHighTonPerHa: 90,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3966w_grain_tropical': const YieldReference(
      id: 'pioneer_p3966w_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3966W',
      yieldLowTonPerHa: 11,
      yieldHighTonPerHa: 12.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p4082w_forage': const YieldReference(
      id: 'pioneer_p4082w_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'P4082W',
      yieldLowTonPerHa: 90,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con fichas Pioneer por región',
    ),
    'pioneer_p4082w_grain_tropical': const YieldReference(
      id: 'pioneer_p4082w_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P4082W',
      yieldLowTonPerHa: 11.7,
      yieldHighTonPerHa: 12.5,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 65000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Fichas oficiales Pioneer Sureste/Noreste',
    ),
    'pioneer_p3260w_grain': const YieldReference(
      id: 'pioneer_p3260w_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3260W',
      yieldLowTonPerHa: 15.5,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3057w_grain_invernal': const YieldReference(
      id: 'pioneer_p3057w_grain_invernal',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3057W',
      yieldLowTonPerHa: 15.5,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3051w_grain': const YieldReference(
      id: 'pioneer_p3051w_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3051W',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3011w_grain': const YieldReference(
      id: 'pioneer_p3011w_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3011W',
      yieldLowTonPerHa: 16.2,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p30064w_grain_oi': const YieldReference(
      id: 'pioneer_p30064w_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P30064W',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 100000,
      seedsHighPerHa: 110000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial Pioneer',
    ),
    'pioneer_p40007w_grain_tropical': const YieldReference(
      id: 'pioneer_p40007w_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P40007W',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 11.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p39092w_grain_tropical': const YieldReference(
      id: 'pioneer_p39092w_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P39092W',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 11.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p1382_grain': const YieldReference(
      id: 'pioneer_p1382_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P1382',
      yieldLowTonPerHa: 14,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p1445_grain': const YieldReference(
      id: 'pioneer_p1445_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P1445',
      yieldLowTonPerHa: 13.5,
      yieldHighTonPerHa: 14.8,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p2807_grain_oi': const YieldReference(
      id: 'pioneer_p2807_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P2807',
      yieldLowTonPerHa: 15.5,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3076_grain_invernal': const YieldReference(
      id: 'pioneer_p3076_grain_invernal',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3076',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3092_grain_invernal': const YieldReference(
      id: 'pioneer_p3092_grain_invernal',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3092',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3097_grain_invernal': const YieldReference(
      id: 'pioneer_p3097_grain_invernal',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3097',
      yieldLowTonPerHa: 14.5,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_b3715_forage_calido': const YieldReference(
      id: 'pioneer_b3715_forage_calido',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'B3715',
      yieldLowTonPerHa: 80,
      yieldHighTonPerHa: 85,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 92000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_b3799_grain_oi': const YieldReference(
      id: 'pioneer_b3799_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'B3799',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p3898_grain_tropical': const YieldReference(
      id: 'pioneer_p3898_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P3898',
      yieldLowTonPerHa: 9.5,
      yieldHighTonPerHa: 11,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p35136_grain_tropical': const YieldReference(
      id: 'pioneer_p35136_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P35136',
      yieldLowTonPerHa: 9.5,
      yieldHighTonPerHa: 11,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'pioneer_p4039_grain_tropical': const YieldReference(
      id: 'pioneer_p4039_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'P4039',
      yieldLowTonPerHa: 9,
      yieldHighTonPerHa: 11,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk2037_grain': const YieldReference(
      id: 'dekalb_dk2037_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-2037',
      yieldLowTonPerHa: 11.5,
      yieldHighTonPerHa: 13,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk1050_grain': const YieldReference(
      id: 'dekalb_dk1050_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-1050',
      yieldLowTonPerHa: 14,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk2061_forage': const YieldReference(
      id: 'dekalb_dk2061_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-2061',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 92,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk2069_forage': const YieldReference(
      id: 'dekalb_dk2069_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-2069',
      yieldLowTonPerHa: 88,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 100000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Fichas oficiales DEKALB por región',
    ),
    'dekalb_dk2069_grain': const YieldReference(
      id: 'dekalb_dk2069_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-2069',
      yieldLowTonPerHa: 16.2,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Fichas oficiales DEKALB por región',
    ),
    'dekalb_dk2048_forage': const YieldReference(
      id: 'dekalb_dk2048_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-2048',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk2048_grain_long': const YieldReference(
      id: 'dekalb_dk2048_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-2048',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk4018_forage': const YieldReference(
      id: 'dekalb_dk4018_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-4018',
      yieldLowTonPerHa: 82,
      yieldHighTonPerHa: 88,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk4018_grain': const YieldReference(
      id: 'dekalb_dk4018_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-4018',
      yieldLowTonPerHa: 15.5,
      yieldHighTonPerHa: 16.8,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk4021_grain': const YieldReference(
      id: 'dekalb_dk4021_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-4021',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk4050_grain_oi': const YieldReference(
      id: 'dekalb_dk4050_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-4050',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 17.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk357_forage': const YieldReference(
      id: 'dekalb_dk357_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-357',
      yieldLowTonPerHa: 75,
      yieldHighTonPerHa: 82,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk390_grain_tropical': const YieldReference(
      id: 'dekalb_dk390_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-390',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 11.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk7088_forage': const YieldReference(
      id: 'dekalb_dk7088_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-7088',
      yieldLowTonPerHa: 88,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk7500_forage': const YieldReference(
      id: 'dekalb_dk7500_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'DK-7500',
      yieldLowTonPerHa: 90,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'dekalb_dk4020y_grain_tardio': const YieldReference(
      id: 'dekalb_dk4020y_grain_tardio',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'DK-4020Y',
      yieldLowTonPerHa: 15.5,
      yieldHighTonPerHa: 17.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_sorento_grain': const YieldReference(
      id: 'syngenta_sorento_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'SORENTO',
      yieldLowTonPerHa: 11.5,
      yieldHighTonPerHa: 13,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_lucino_grain': const YieldReference(
      id: 'syngenta_lucino_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'LUCINO',
      yieldLowTonPerHa: 11,
      yieldHighTonPerHa: 12.5,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_nmi078_grain_tardio': const YieldReference(
      id: 'syngenta_nmi078_grain_tardio',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'NMI078',
      yieldLowTonPerHa: 16.5,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial Syngenta',
    ),
    'syngenta_6018w_grain': const YieldReference(
      id: 'syngenta_6018w_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: '6018W',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 17,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_tiburon_grain_long': const YieldReference(
      id: 'syngenta_tiburon_grain_long',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'TIBURÓN',
      yieldLowTonPerHa: 17.2,
      yieldHighTonPerHa: 18,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_sy600_forage': const YieldReference(
      id: 'syngenta_sy600_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'SY-600',
      yieldLowTonPerHa: 85,
      yieldHighTonPerHa: 90,
      seedsLowPerHa: 88000,
      seedsHighPerHa: 98000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_sy700_grain': const YieldReference(
      id: 'syngenta_sy700_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'SY-700',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_sy800_forage_calido': const YieldReference(
      id: 'syngenta_sy800_forage_calido',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'SY-800',
      yieldLowTonPerHa: 80,
      yieldHighTonPerHa: 85,
      seedsLowPerHa: 85000,
      seedsHighPerHa: 92000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_impacto_grain': const YieldReference(
      id: 'syngenta_impacto_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'IMPACTO',
      yieldLowTonPerHa: 13,
      yieldHighTonPerHa: 14.5,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_8246_grain': const YieldReference(
      id: 'syngenta_8246_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: '8246',
      yieldLowTonPerHa: 14,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_n83n5_grain_tardio': const YieldReference(
      id: 'syngenta_n83n5_grain_tardio',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'N83N5',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 16.5,
      seedsLowPerHa: 95000,
      seedsHighPerHa: 105000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_9166_grain': const YieldReference(
      id: 'syngenta_9166_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: '9166',
      yieldLowTonPerHa: 14,
      yieldHighTonPerHa: 15.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 100000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'syngenta_9703_grain_oi': const YieldReference(
      id: 'syngenta_9703_grain_oi',
      cropId: 'maize',
      useType: 'grain',
      displayName: '9703',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 17.5,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 95000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Ficha oficial Syngenta 9703',
    ),
    'syngenta_tundra_grain_tropical': const YieldReference(
      id: 'syngenta_tundra_grain_tropical',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'TUNDRA',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 11.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 78000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por segmento agronómico',
    ),
    'generic_maize_white_grain': const YieldReference(
      id: 'generic_maize_white_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'Blanco',
      yieldLowTonPerHa: 6.5,
      yieldHighTonPerHa: 8.5,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 75000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con promedios nacionales y catálogo',
    ),
    'generic_maize_yellow_grain': const YieldReference(
      id: 'generic_maize_yellow_grain',
      cropId: 'maize',
      useType: 'grain',
      displayName: 'Amarillo',
      yieldLowTonPerHa: 6.2,
      yieldHighTonPerHa: 8.2,
      seedsLowPerHa: 65000,
      seedsHighPerHa: 75000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con promedios nacionales y catálogo',
    ),
    'generic_maize_forage': const YieldReference(
      id: 'generic_maize_forage',
      cropId: 'maize',
      useType: 'forage',
      displayName: 'Forrajero',
      yieldLowTonPerHa: 45,
      yieldHighTonPerHa: 60,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 90000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con promedios nacionales de forraje',
    ),
    'generic_maize_elote': const YieldReference(
      id: 'generic_maize_elote',
      cropId: 'maize',
      useType: 'elote',
      displayName: 'Elotero',
      yieldLowTonPerHa: 12,
      yieldHighTonPerHa: 16,
      seedsLowPerHa: 55000,
      seedsHighPerHa: 65000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con benchmark INIFAP de elote',
    ),
    'bean_negro_temprano': const YieldReference(
      id: 'bean_negro_temprano',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Negro Precoz',
      yieldLowTonPerHa: 1.2,
      yieldHighTonPerHa: 1.8,
      seedsLowPerHa: 180000,
      seedsHighPerHa: 220000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con Negro Tropical + guías de población',
    ),
    'bean_negro': const YieldReference(
      id: 'bean_negro',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Negro Intermedio',
      yieldLowTonPerHa: 1.2,
      yieldHighTonPerHa: 2.1,
      seedsLowPerHa: 160000,
      seedsHighPerHa: 210000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con Negro Tropical + guías de población',
    ),
    'bean_pinto': const YieldReference(
      id: 'bean_pinto',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Pinto',
      yieldLowTonPerHa: 1.6,
      yieldHighTonPerHa: 2.5,
      seedsLowPerHa: 120000,
      seedsHighPerHa: 180000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'INIFAP Pinto Saltillo + guías de población',
    ),
    'bean_flor_mayo_junio': const YieldReference(
      id: 'bean_flor_mayo_junio',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Flor Mayo/Junio',
      yieldLowTonPerHa: 1.6,
      yieldHighTonPerHa: 2.6,
      seedsLowPerHa: 140000,
      seedsHighPerHa: 190000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con evaluaciones de temporal',
    ),
    'bean_bayo_azufrado_blanco': const YieldReference(
      id: 'bean_bayo_azufrado_blanco',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Azufrado/Bayo',
      yieldLowTonPerHa: 1.8,
      yieldHighTonPerHa: 2.8,
      seedsLowPerHa: 120000,
      seedsHighPerHa: 170000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'Calibrado con Janasa/Azufrasin',
    ),
    'bean_peruano': const YieldReference(
      id: 'bean_peruano',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Peruano',
      yieldLowTonPerHa: 1.7,
      yieldHighTonPerHa: 2.5,
      seedsLowPerHa: 130000,
      seedsHighPerHa: 180000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo por clase comercial',
    ),
    'bean_canario': const YieldReference(
      id: 'bean_canario',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Canario',
      yieldLowTonPerHa: 1.8,
      yieldHighTonPerHa: 2.6,
      seedsLowPerHa: 160000,
      seedsHighPerHa: 200000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Agenda técnica Canario',
    ),
    'bean_generic': const YieldReference(
      id: 'bean_generic',
      cropId: 'bean',
      useType: 'grain',
      displayName: 'Genérico',
      yieldLowTonPerHa: 1.3,
      yieldHighTonPerHa: 1.9,
      seedsLowPerHa: 130000,
      seedsHighPerHa: 180000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo conservador',
    ),
    'wheat_kentana_48': const YieldReference(
      id: 'wheat_kentana_48',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Kentana 48',
      yieldLowTonPerHa: 3.3,
      yieldHighTonPerHa: 4,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_chapingo_53': const YieldReference(
      id: 'wheat_chapingo_53',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Chapingo 53',
      yieldLowTonPerHa: 3.5,
      yieldHighTonPerHa: 4.3,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_bajio_53': const YieldReference(
      id: 'wheat_bajio_53',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Bajío 53',
      yieldLowTonPerHa: 4.2,
      yieldHighTonPerHa: 4.9,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_mexe_53': const YieldReference(
      id: 'wheat_mexe_53',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Mexe 53',
      yieldLowTonPerHa: 4.1,
      yieldHighTonPerHa: 4.8,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_tobari_f66': const YieldReference(
      id: 'wheat_tobari_f66',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Tobari F66',
      yieldLowTonPerHa: 4.8,
      yieldHighTonPerHa: 5.5,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_roelfs_f2007': const YieldReference(
      id: 'wheat_roelfs_f2007',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Roelfs F2007',
      yieldLowTonPerHa: 6.4,
      yieldHighTonPerHa: 7.2,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_tacupeto_f2001': const YieldReference(
      id: 'wheat_tacupeto_f2001',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Tacupeto F2001',
      yieldLowTonPerHa: 6.1,
      yieldHighTonPerHa: 6.9,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_bacanora_t88': const YieldReference(
      id: 'wheat_bacanora_t88',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Bacanora T88',
      yieldLowTonPerHa: 5.5,
      yieldHighTonPerHa: 6.3,
      seedsLowPerHa: 2.4e+06,
      seedsHighPerHa: 3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_opata_m85': const YieldReference(
      id: 'wheat_opata_m85',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Ópata M85',
      yieldLowTonPerHa: 5.1,
      yieldHighTonPerHa: 5.9,
      seedsLowPerHa: 2.4e+06,
      seedsHighPerHa: 3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_kronstad_f2004': const YieldReference(
      id: 'wheat_kronstad_f2004',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Kronstad F2004',
      yieldLowTonPerHa: 6.3,
      yieldHighTonPerHa: 7.1,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_onavas_f2009': const YieldReference(
      id: 'wheat_onavas_f2009',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Ónavas F2009',
      yieldLowTonPerHa: 6.8,
      yieldHighTonPerHa: 7.8,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP / validación Ónavas F2009; Equivalente de tasa oficial de semilla',
    ),
    'wheat_borlaug_m95': const YieldReference(
      id: 'wheat_borlaug_m95',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Borlaug M95',
      yieldLowTonPerHa: 5.6,
      yieldHighTonPerHa: 6.4,
      seedsLowPerHa: 2.4e+06,
      seedsHighPerHa: 3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_cirno_c2008': const YieldReference(
      id: 'wheat_cirno_c2008',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'CIRNO C2008',
      yieldLowTonPerHa: 6.3,
      yieldHighTonPerHa: 7.4,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Ensayos comparativos en Mexicali; Equivalente de tasa oficial de semilla',
    ),
    'wheat_borlaug_100_f2014': const YieldReference(
      id: 'wheat_borlaug_100_f2014',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Borlaug 100',
      yieldLowTonPerHa: 7.2,
      yieldHighTonPerHa: 8,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_conatrigo_f2015': const YieldReference(
      id: 'wheat_conatrigo_f2015',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Conatrigo F2015',
      yieldLowTonPerHa: 5.7,
      yieldHighTonPerHa: 7.2,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP Conatrigo F2015; Equivalente de tasa oficial de semilla',
    ),
    'wheat_bacorehuis_f2015': const YieldReference(
      id: 'wheat_bacorehuis_f2015',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Bacorehuis F2015',
      yieldLowTonPerHa: 6.9,
      yieldHighTonPerHa: 7.7,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_seri_m82': const YieldReference(
      id: 'wheat_seri_m82',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Seri M82',
      yieldLowTonPerHa: 5.4,
      yieldHighTonPerHa: 6.2,
      seedsLowPerHa: 2.4e+06,
      seedsHighPerHa: 3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_huatabampo_durum_c2017': const YieldReference(
      id: 'wheat_huatabampo_durum_c2017',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Huatabampo',
      yieldLowTonPerHa: 6.7,
      yieldHighTonPerHa: 7.6,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'wheat_quetchehueca_oro_c2013': const YieldReference(
      id: 'wheat_quetchehueca_oro_c2013',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Quetchehueca',
      yieldLowTonPerHa: 6.6,
      yieldHighTonPerHa: 8,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Ensayos comparativos + validación; Equivalente de tasa oficial de semilla',
    ),
    'wheat_movas_c2015': const YieldReference(
      id: 'wheat_movas_c2015',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Movas C2009',
      yieldLowTonPerHa: 5.9,
      yieldHighTonPerHa: 7.6,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.2e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP Movas C2009 (corrección de nombre); Equivalente de tasa oficial de semilla',
    ),
    'wheat_forrajero': const YieldReference(
      id: 'wheat_forrajero',
      cropId: 'wheat',
      useType: 'forage',
      displayName: 'Forrajero',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con estadísticas oficiales de trigo forrajero verde + guías de manejo forrajero; equivalente desde 100–120 kg/ha',
    ),
    'wheat_generic': const YieldReference(
      id: 'wheat_generic',
      cropId: 'wheat',
      useType: 'grain',
      displayName: 'Genérico',
      yieldLowTonPerHa: 6,
      yieldHighTonPerHa: 6.8,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo por año de liberación + ajuste al catálogo; Equivalente de tasa oficial de semilla',
    ),
    'barley_esperanza': const YieldReference(
      id: 'barley_esperanza',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Esperanza',
      yieldLowTonPerHa: 4.9,
      yieldHighTonPerHa: 6.2,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP + evaluación Bajío 2025; equivalente desde 100–120 kg/ha',
    ),
    'barley_maravilla': const YieldReference(
      id: 'barley_maravilla',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Maravilla',
      yieldLowTonPerHa: 5,
      yieldHighTonPerHa: 6.3,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP Maravilla + evaluación Bajío 2025; equivalente desde 100–120 kg/ha',
    ),
    'barley_cucapah_87': const YieldReference(
      id: 'barley_cucapah_87',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Cucapah 87',
      yieldLowTonPerHa: 4,
      yieldHighTonPerHa: 5.2,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales históricos; equivalente desde 100–120 kg/ha',
    ),
    'barley_lg_diablo': const YieldReference(
      id: 'barley_lg_diablo',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'LG Diablo',
      yieldLowTonPerHa: 5.7,
      yieldHighTonPerHa: 7,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_kws_fantex': const YieldReference(
      id: 'barley_kws_fantex',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'KWS Fantex',
      yieldLowTonPerHa: 5.8,
      yieldHighTonPerHa: 7.2,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_esmeralda': const YieldReference(
      id: 'barley_esmeralda',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Esmeralda',
      yieldLowTonPerHa: 4.7,
      yieldHighTonPerHa: 5.9,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales INIFAP afines; equivalente desde 100–120 kg/ha',
    ),
    'barley_adabella': const YieldReference(
      id: 'barley_adabella',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Adabella',
      yieldLowTonPerHa: 4.5,
      yieldHighTonPerHa: 5.8,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales INIFAP afines; equivalente desde 100–120 kg/ha',
    ),
    'barley_armida': const YieldReference(
      id: 'barley_armida',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Armida',
      yieldLowTonPerHa: 5.5,
      yieldHighTonPerHa: 6.8,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod:
          'INIFAP Armida + relativo sobre Esperanza; equivalente desde 100–120 kg/ha',
    ),
    'barley_alina': const YieldReference(
      id: 'barley_alina',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Alina',
      yieldLowTonPerHa: 5.6,
      yieldHighTonPerHa: 7,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Evaluación Bajío 2025; equivalente desde 100–120 kg/ha',
    ),
    'barley_dona_josefa': const YieldReference(
      id: 'barley_dona_josefa',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Doña Josefa',
      yieldLowTonPerHa: 4.8,
      yieldHighTonPerHa: 6,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales INIFAP afines; equivalente desde 100–120 kg/ha',
    ),
    'barley_rgt_planet': const YieldReference(
      id: 'barley_rgt_planet',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'RGT Planet',
      yieldLowTonPerHa: 6,
      yieldHighTonPerHa: 7.5,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_rgt_asteroid': const YieldReference(
      id: 'barley_rgt_asteroid',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'RGT Asteroid',
      yieldLowTonPerHa: 5.8,
      yieldHighTonPerHa: 7.2,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_sy_tungsten': const YieldReference(
      id: 'barley_sy_tungsten',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'SY Tungsten',
      yieldLowTonPerHa: 5.8,
      yieldHighTonPerHa: 7.2,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_sy_odyssey': const YieldReference(
      id: 'barley_sy_odyssey',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'SY Odyssey',
      yieldLowTonPerHa: 5.6,
      yieldHighTonPerHa: 7,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_lg_zebra': const YieldReference(
      id: 'barley_lg_zebra',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'LG Zebra',
      yieldLowTonPerHa: 5.6,
      yieldHighTonPerHa: 7,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_lg_esterel': const YieldReference(
      id: 'barley_lg_esterel',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'LG Esterel',
      yieldLowTonPerHa: 5.5,
      yieldHighTonPerHa: 6.8,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_kws_orbit': const YieldReference(
      id: 'barley_kws_orbit',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'KWS Orbit',
      yieldLowTonPerHa: 5.7,
      yieldHighTonPerHa: 7.1,
      seedsLowPerHa: 2.7e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales élite modernos; equivalente desde 100–120 kg/ha',
    ),
    'barley_estelar_oh': const YieldReference(
      id: 'barley_estelar_oh',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Estelar-OH',
      yieldLowTonPerHa: 5,
      yieldHighTonPerHa: 6.4,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'Evaluación Bajío 2025; equivalente desde 100–120 kg/ha',
    ),
    'barley_forrajera_inifap': const YieldReference(
      id: 'barley_forrajera_inifap',
      cropId: 'barley',
      useType: 'forage',
      displayName: 'Forrajera',
      yieldLowTonPerHa: 28,
      yieldHighTonPerHa: 38,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con estadísticas oficiales de cebada forrajera verde; equivalente desde 100–120 kg/ha',
    ),
    'barley_cerro_prieto': const YieldReference(
      id: 'barley_cerro_prieto',
      cropId: 'barley',
      useType: 'forage',
      displayName: 'Cerro Prieto',
      yieldLowTonPerHa: 30,
      yieldHighTonPerHa: 40,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con estadísticas oficiales de cebada forrajera verde; equivalente desde 100–120 kg/ha',
    ),
    'barley_puebla': const YieldReference(
      id: 'barley_puebla',
      cropId: 'barley',
      useType: 'forage',
      displayName: 'Puebla',
      yieldLowTonPerHa: 28,
      yieldHighTonPerHa: 36,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con estadísticas oficiales de cebada forrajera verde; equivalente desde 100–120 kg/ha',
    ),
    'barley_generic': const YieldReference(
      id: 'barley_generic',
      cropId: 'barley',
      useType: 'grain',
      displayName: 'Genérica',
      yieldLowTonPerHa: 3.4,
      yieldHighTonPerHa: 4.2,
      seedsLowPerHa: 2.5e+06,
      seedsHighPerHa: 3.1e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo conservador; equivalente desde 100–120 kg/ha',
    ),
    'oat_chihuahua': const YieldReference(
      id: 'oat_chihuahua',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Chihuahua',
      yieldLowTonPerHa: 3.6,
      yieldHighTonPerHa: 5.5,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.4e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'INIFAP Chihuahua; equivalente de 90–120 kg/ha',
    ),
    'oat_cuauhtemoc': const YieldReference(
      id: 'oat_cuauhtemoc',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Cuauhtémoc',
      yieldLowTonPerHa: 1.8,
      yieldHighTonPerHa: 3,
      seedsLowPerHa: 3e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con materiales estables; equivalente de 90–120 kg/ha',
    ),
    'oat_menonita': const YieldReference(
      id: 'oat_menonita',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Menonita',
      yieldLowTonPerHa: 1.5,
      yieldHighTonPerHa: 2.5,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo conservador; equivalente de 90–120 kg/ha',
    ),
    'oat_obispo': const YieldReference(
      id: 'oat_obispo',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Obispo',
      yieldLowTonPerHa: 2.2,
      yieldHighTonPerHa: 3.5,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo conservador; equivalente de 90–120 kg/ha',
    ),
    'oat_turquesa': const YieldReference(
      id: 'oat_turquesa',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Turquesa',
      yieldLowTonPerHa: 4.2,
      yieldHighTonPerHa: 6.2,
      seedsLowPerHa: 3e+06,
      seedsHighPerHa: 3.6e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'INIFAP Turquesa + tope >8 t/ha; equivalente de 90–120 kg/ha',
    ),
    'oat_karma': const YieldReference(
      id: 'oat_karma',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Karma',
      yieldLowTonPerHa: 3,
      yieldHighTonPerHa: 4.2,
      seedsLowPerHa: 3e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con evaluación reciente; equivalente de 90–120 kg/ha',
    ),
    'oat_agata': const YieldReference(
      id: 'oat_agata',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Ágata',
      yieldLowTonPerHa: 2.7,
      yieldHighTonPerHa: 4.2,
      seedsLowPerHa: 3e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.validated,
      sourceMethod: 'INIFAP Ágata; equivalente de 90–120 kg/ha',
    ),
    'oat_generic': const YieldReference(
      id: 'oat_generic',
      cropId: 'oat',
      useType: 'grain',
      displayName: 'Genérica',
      yieldLowTonPerHa: 1.5,
      yieldHighTonPerHa: 2.5,
      seedsLowPerHa: 2.6e+06,
      seedsHighPerHa: 3.3e+06,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'Modelo conservador; equivalente de 90–120 kg/ha',
    ),
    'oat_forrajera': YieldReference(
      id: 'oat_forrajera',
      cropId: 'oat',
      useType: 'forage',
      displayName: 'Forrajera',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 2.8e+06,
      seedsHighPerHa: 3.5e+06,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado con agendas técnicas INIFAP y estadísticas oficiales de avena forrajera; equivalente desde 100–120 kg/ha',
    ),

    // ── Tomate (hortaliza, fruto fresco) ───────────────────────────────────
    // v1: sólo suelo (campo abierto + protegido en suelo). No hidroponía.
    // seedsLow/HighPerHa representan densidad de plantas trasplantadas por
    // hectárea, no semillas (el ciclo se ancla a trasplante).
    'tomato_field_generic': const YieldReference(
      id: 'tomato_field_generic',
      cropId: 'tomato',
      useType: 'fresh',
      displayName: 'Tomate campo abierto (genérico)',
      yieldLowTonPerHa: 45,
      yieldHighTonPerHa: 75,
      seedsLowPerHa: 15000,
      seedsHighPerHa: 22000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador tomate saladette/roma en suelo a cielo abierto; densidad y rendimiento típicos en manejo medio.',
    ),
    'tomato_protected_generic': const YieldReference(
      id: 'tomato_protected_generic',
      cropId: 'tomato',
      useType: 'fresh',
      displayName: 'Tomate protegido en suelo (genérico)',
      yieldLowTonPerHa: 90,
      yieldHighTonPerHa: 160,
      seedsLowPerHa: 20000,
      seedsHighPerHa: 30000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador tomate bajo malla/invernadero en suelo; excluye hidroponía y sustrato.',
    ),

    // ── Pepino (hortaliza, fruto fresco / proceso) ───────────────────────
    // v1: sólo campo abierto e invernadero en suelo. Sin hidroponía.
    'cucumber_generic': const YieldReference(
      id: 'cucumber_generic',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino genérico',
      yieldLowTonPerHa: 30,
      yieldHighTonPerHa: 70,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 35000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Transitorio conservador PE-GEN; migrable al definir sistema/tipo.',
    ),
    'cucumber_field_generic': const YieldReference(
      id: 'cucumber_field_generic',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino campo abierto (genérico)',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado desde referencia BIO-G para pepino campo abierto genérico.',
    ),
    'cucumber_protected_soil_generic': const YieldReference(
      id: 'cucumber_protected_soil_generic',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino protegido en suelo (genérico)',
      yieldLowTonPerHa: 70,
      yieldHighTonPerHa: 95,
      seedsLowPerHa: 18000,
      seedsHighPerHa: 30000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Calibrado desde referencia BIO-G para pepino protegido en suelo.',
    ),
    'cucumber_slicer_ca': const YieldReference(
      id: 'cucumber_slicer_ca',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino americano / slicer campo abierto',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 40,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'PE-01 BIO-G; slicer/americano a campo abierto.',
    ),
    'cucumber_european_protected': const YieldReference(
      id: 'cucumber_european_protected',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino europeo / inglés protegido',
      yieldLowTonPerHa: 75,
      yieldHighTonPerHa: 100,
      seedsLowPerHa: 18000,
      seedsHighPerHa: 28000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'PE-02 BIO-G; europeo largo protegido en suelo.',
    ),
    'cucumber_persian': const YieldReference(
      id: 'cucumber_persian',
      cropId: 'cucumber',
      useType: 'fresh',
      displayName: 'Pepino persa / mini protegido',
      yieldLowTonPerHa: 40,
      yieldHighTonPerHa: 70,
      seedsLowPerHa: 18000,
      seedsHighPerHa: 30000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'PE-03 BIO-G; persa/mini protegido en suelo.',
    ),
    'cucumber_pickler': const YieldReference(
      id: 'cucumber_pickler',
      cropId: 'cucumber',
      useType: 'process',
      displayName: 'Pepinillo / pickle campo abierto',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 120000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'PE-04 BIO-G; pickler/pickle campo abierto.',
    ),

    // Chile (hortaliza, fruto fresco / seco)
    // v1: suelo en campo abierto o protegido. Densidad = plantas/ha.
    'chili_generic': const YieldReference(
      id: 'chili_generic',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile generico (CH-GEN)',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 30000,
      seedsHighPerHa: 45000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador CH-GEN BIO-G; migrable al definir tipo sin reiniciar historial.',
    ),
    'chili_field_generic': const YieldReference(
      id: 'chili_field_generic',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile campo abierto (generico)',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 30000,
      seedsHighPerHa: 45000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Referencia BIO-G calibrada para chile verde generico en campo abierto.',
    ),
    'chili_protected_soil_generic': const YieldReference(
      id: 'chili_protected_soil_generic',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile protegido en suelo (generico)',
      yieldLowTonPerHa: 35,
      yieldHighTonPerHa: 65,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 45000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Referencia BIO-G para malla/invernadero en suelo; excluye hidroponia.',
    ),
    'chili_jalapeno': const YieldReference(
      id: 'chili_jalapeno',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile jalapeno',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 30000,
      seedsHighPerHa: 45000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-01 BIO-G; fresco/proceso/chipotle, calibrado contra fuentes oficiales.',
    ),
    'chili_serrano': const YieldReference(
      id: 'chili_serrano',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile serrano',
      yieldLowTonPerHa: 22,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 35000,
      seedsHighPerHa: 55000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'CH-02 BIO-G; alta carga y cosecha continua.',
    ),
    'chili_poblano_ancho': const YieldReference(
      id: 'chili_poblano_ancho',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile poblano (verde)',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-03 BIO-G poblano fresco; usar chili_ancho_dry si destino es ancho/mulato seco.',
    ),
    'chili_ancho_dry': const YieldReference(
      id: 'chili_ancho_dry',
      cropId: 'chili',
      useType: 'dry',
      displayName: 'Chile ancho / mulato seco',
      yieldLowTonPerHa: 1.5,
      yieldHighTonPerHa: 3.5,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'CH-03 BIO-G destino seco (ancho/mulato/deshidratado).',
    ),
    'chili_chilaca_pasilla': const YieldReference(
      id: 'chili_chilaca_pasilla',
      cropId: 'chili',
      useType: 'dry',
      displayName: 'Chile pasilla seco',
      yieldLowTonPerHa: 1.2,
      yieldHighTonPerHa: 2.8,
      seedsLowPerHa: 20000,
      seedsHighPerHa: 35000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'CH-04 BIO-G; destino seco como pasilla.',
    ),
    'chili_chilaca_fresh': const YieldReference(
      id: 'chili_chilaca_fresh',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile chilaca (verde)',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 20000,
      seedsHighPerHa: 35000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CH-04 BIO-G chilaca fresco; cosecha verde antes de secado.',
    ),
    'chili_guajillo_mirasol': const YieldReference(
      id: 'chili_guajillo_mirasol',
      cropId: 'chili',
      useType: 'dry',
      displayName: 'Chile guajillo / mirasol seco',
      yieldLowTonPerHa: 1.5,
      yieldHighTonPerHa: 3.5,
      seedsLowPerHa: 20000,
      seedsHighPerHa: 35000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-05 BIO-G; mercado seco principal calibrado contra Plan Rector / extension.',
    ),
    'chili_arbol_fresh': const YieldReference(
      id: 'chili_arbol_fresh',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile de arbol fresco',
      yieldLowTonPerHa: 8,
      yieldHighTonPerHa: 22,
      seedsLowPerHa: 40000,
      seedsHighPerHa: 70000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CH-06 BIO-G; chile de arbol / puya cosechado en fresco cuando el alias lo indique.',
    ),
    'chili_arbol_puya_dry': const YieldReference(
      id: 'chili_arbol_puya_dry',
      cropId: 'chili',
      useType: 'dry',
      displayName: 'Chile de arbol / puya seco',
      yieldLowTonPerHa: 1.0,
      yieldHighTonPerHa: 2.8,
      seedsLowPerHa: 40000,
      seedsHighPerHa: 70000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'CH-06 BIO-G; fruto pequeno, alta densidad, destino seco.',
    ),
    'chili_arbol_puya': const YieldReference(
      id: 'chili_arbol_puya',
      cropId: 'chili',
      useType: 'dry',
      displayName: 'Chile de arbol / puya seco',
      yieldLowTonPerHa: 1.0,
      yieldHighTonPerHa: 2.8,
      seedsLowPerHa: 40000,
      seedsHighPerHa: 70000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.modeled,
      sourceMethod: 'CH-06 BIO-G; fruto pequeno, alta densidad, destino seco.',
    ),
    'chili_habanero': const YieldReference(
      id: 'chili_habanero',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Chile habanero',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 40,
      seedsLowPerHa: 20000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-07 BIO-G; Capsicum chinense, mayor sensibilidad termica.',
    ),
    'chili_bell_pepper': const YieldReference(
      id: 'chili_bell_pepper',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Pimiento morron / chile gordo (campo)',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-08 BIO-G campo abierto; fruto grande, calidad sensible.',
    ),
    'chili_bell_pepper_protected': const YieldReference(
      id: 'chili_bell_pepper_protected',
      cropId: 'chili',
      useType: 'fresh',
      displayName: 'Pimiento morron / chile gordo (protegido)',
      yieldLowTonPerHa: 55,
      yieldHighTonPerHa: 85,
      seedsLowPerHa: 25000,
      seedsHighPerHa: 40000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CH-08 BIO-G casa malla/invernadero en suelo; excluye hidroponia.',
    ),

    // Berenjena (hortaliza, fruto fresco)
    // v1: suelo en campo abierto o protegido. Densidad = plantas
    // establecidas/ha, no semilla bruta de charola.
    'eggplant_generic': const YieldReference(
      id: 'eggplant_generic',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena generica (BE-GEN)',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 32,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 20000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador BE-GEN BIO-G; migrable al definir tipo sin reiniciar historial.',
    ),
    'eggplant_field_generic': const YieldReference(
      id: 'eggplant_field_generic',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena campo abierto (generica)',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 36,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 22000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Referencia BIO-G para berenjena generica en campo abierto.',
    ),
    'eggplant_protected_soil_generic': const YieldReference(
      id: 'eggplant_protected_soil_generic',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena protegida en suelo (generica)',
      yieldLowTonPerHa: 40,
      yieldHighTonPerHa: 65,
      seedsLowPerHa: 8000,
      seedsHighPerHa: 18000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Referencia BIO-G para malla/invernadero en suelo; excluye hidroponia y sustratos inertes.',
    ),
    'eggplant_long_purple_field': const YieldReference(
      id: 'eggplant_long_purple_field',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena larga / semilarga morada (campo)',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 24000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'BE-01 BIO-G; tipo dominante en campo abierto.',
    ),
    'eggplant_long_purple_protected': const YieldReference(
      id: 'eggplant_long_purple_protected',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena larga / semilarga morada (protegida)',
      yieldLowTonPerHa: 55,
      yieldHighTonPerHa: 85,
      seedsLowPerHa: 8000,
      seedsHighPerHa: 18000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-01 BIO-G protegido en suelo; mayor continuidad, sin hidroponia.',
    ),
    'eggplant_oval_round_field': const YieldReference(
      id: 'eggplant_oval_round_field',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena oval / bola morada (campo)',
      yieldLowTonPerHa: 22,
      yieldHighTonPerHa: 42,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 22000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod: 'BE-02 BIO-G; fruto fresco, tamano y uniformidad.',
    ),
    'eggplant_oval_round_protected': const YieldReference(
      id: 'eggplant_oval_round_protected',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena oval / bola morada (protegida)',
      yieldLowTonPerHa: 45,
      yieldHighTonPerHa: 75,
      seedsLowPerHa: 8000,
      seedsHighPerHa: 16000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-02 BIO-G protegido en suelo; mayor continuidad, sin hidroponia.',
    ),
    'eggplant_striped_field': const YieldReference(
      id: 'eggplant_striped_field',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena rayada / listada (campo)',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 32,
      seedsLowPerHa: 10000,
      seedsHighPerHa: 18000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-03 BIO-G; nicho/gourmet, rango conservador por calidad visual.',
    ),
    'eggplant_striped_protected': const YieldReference(
      id: 'eggplant_striped_protected',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena rayada / listada (protegida)',
      yieldLowTonPerHa: 30,
      yieldHighTonPerHa: 55,
      seedsLowPerHa: 7000,
      seedsHighPerHa: 14000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-03 BIO-G protegido en suelo; calidad visual como limitante principal.',
    ),
    'eggplant_white_field': const YieldReference(
      id: 'eggplant_white_field',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena blanca (campo)',
      yieldLowTonPerHa: 14,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 10000,
      seedsHighPerHa: 18000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-04 BIO-G; nicho pequeno, rango conservador por rechazo visual.',
    ),
    'eggplant_white_protected': const YieldReference(
      id: 'eggplant_white_protected',
      cropId: 'eggplant',
      useType: 'fresh',
      displayName: 'Berenjena blanca (protegida)',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 50,
      seedsLowPerHa: 7000,
      seedsHighPerHa: 14000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'BE-04 BIO-G protegido en suelo; calidad visual como limitante principal.',
    ),

    // Calabaza / squash (hortaliza, fruto fresco/maduro y semilla seca)
    // v1: suelo en campo abierto o protegido. Densidad = plantas
    // establecidas/ha, no semilla bruta. CA-07 se resuelve por defecto como
    // semilla seca / pepita y no se mezcla con t/ha de fruto fresco.
    'squash_generic': const YieldReference(
      id: 'squash_generic',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'Calabaza generica (CA-GEN)',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 28,
      seedsLowPerHa: 8000,
      seedsHighPerHa: 18000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador CA-GEN BIO-G; no asume calabacita, fruto maduro ni pepita hasta que el usuario define tipo.',
    ),
    'squash_field_generic': const YieldReference(
      id: 'squash_field_generic',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'Calabaza campo abierto (generica)',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 32,
      seedsLowPerHa: 10000,
      seedsHighPerHa: 20000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Referencia BIO-G para calabaza de campo abierto cuando no hay tipo especifico.',
    ),
    'squash_protected_soil_generic': const YieldReference(
      id: 'squash_protected_soil_generic',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'Calabaza protegida en suelo (generica)',
      yieldLowTonPerHa: 35,
      yieldHighTonPerHa: 60,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 25000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo para malla/invernadero en suelo; excluye hidroponia y sustratos inertes.',
    ),
    'squash_zucchini_field': const YieldReference(
      id: 'squash_zucchini_field',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-01 calabacita italiana / zucchini campo',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 40,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 25000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CA-01 BIO-G; fruto tierno de corte continuo en campo abierto.',
    ),
    'squash_zucchini_protected': const YieldReference(
      id: 'squash_zucchini_protected',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-01 zucchini protegido en suelo',
      yieldLowTonPerHa: 45,
      yieldHighTonPerHa: 75,
      seedsLowPerHa: 15000,
      seedsHighPerHa: 30000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-01 BIO-G protegido en suelo; potencial alto por cortes continuos, sin hidroponia.',
    ),
    'squash_criolla_field': const YieldReference(
      id: 'squash_criolla_field',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-02 criolla / huicha / milpa',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 25,
      seedsLowPerHa: 5000,
      seedsHighPerHa: 15000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-02 BIO-G; sistema mixto, milpa o temporal con alta variabilidad.',
    ),
    'squash_round_field': const YieldReference(
      id: 'squash_round_field',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-03 calabacita bola / redonda',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 36,
      seedsLowPerHa: 12000,
      seedsHighPerHa: 25000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-03 BIO-G; fruto tierno redondo, similar a zucchini con ajuste por calibre y forma.',
    ),
    'squash_castilla_mature': const YieldReference(
      id: 'squash_castilla_mature',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-04 Calabaza de Castilla / fruto maduro',
      yieldLowTonPerHa: 18,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 4000,
      seedsHighPerHa: 10000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CA-04 BIO-G; fruto grande maduro, menor densidad y ciclo largo.',
    ),
    'squash_butternut_field': const YieldReference(
      id: 'squash_butternut_field',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-05 butternut / buchona campo',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 4000,
      seedsHighPerHa: 10000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CA-05 BIO-G; fruto maduro uniforme con mejor techo en cultivares modernos.',
    ),
    'squash_butternut_intensive': const YieldReference(
      id: 'squash_butternut_intensive',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-05 butternut intensivo en suelo',
      yieldLowTonPerHa: 35,
      yieldHighTonPerHa: 65,
      seedsLowPerHa: 5000,
      seedsHighPerHa: 12000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-05 BIO-G intensivo/protegido en suelo; usar solo con manejo explicito.',
    ),
    'squash_chilacayote_mature': const YieldReference(
      id: 'squash_chilacayote_mature',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-06 chilacayote fruto maduro',
      yieldLowTonPerHa: 8,
      yieldHighTonPerHa: 25,
      seedsLowPerHa: 1000,
      seedsHighPerHa: 4000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-06 BIO-G; guia vigorosa, ciclo muy largo y evidencia menos estandarizada.',
    ),
    'squash_pipian_seed_dry': const YieldReference(
      id: 'squash_pipian_seed_dry',
      cropId: 'squash',
      useType: 'seed',
      displayName: 'CA-07 pipian / pepita seca',
      yieldLowTonPerHa: 0.4,
      yieldHighTonPerHa: 1.2,
      seedsLowPerHa: 3000,
      seedsHighPerHa: 8000,
      isFreshMatter: false,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'CA-07 BIO-G; destino semilla seca / pepita. No comparar con toneladas de fruto fresco.',
    ),
    'squash_pipian_fruit_mature': const YieldReference(
      id: 'squash_pipian_fruit_mature',
      cropId: 'squash',
      useType: 'fresh',
      displayName: 'CA-07 pipian fruto maduro secundario',
      yieldLowTonPerHa: 12,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 3000,
      seedsHighPerHa: 8000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'CA-07 BIO-G cuando el usuario declara destino fruto; por defecto CA-07 usa pepita seca.',
    ),

    // Lechuga / lettuce (hortaliza de hoja, peso fresco comercial).
    // BIO-G v1: suelo en campo abierto o protegido; sin hidroponia.
    // Densidad = plantas establecidas/ha. Los rangos son orientativos y
    // NO deben mostrarse como garantia: la lechuga prioriza calidad y
    // ventana comercial sobre kg exactos.
    'lettuce_generic': const YieldReference(
      id: 'lettuce_generic',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'Lechuga generica (LE-GEN)',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 45,
      seedsLowPerHa: 70000,
      seedsHighPerHa: 120000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo conservador LE-GEN BIO-G; no asume tipo comercial hasta que el usuario lo define.',
    ),
    'lettuce_field_generic': const YieldReference(
      id: 'lettuce_field_generic',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'Lechuga campo abierto (generica)',
      yieldLowTonPerHa: 16,
      yieldHighTonPerHa: 42,
      seedsLowPerHa: 70000,
      seedsHighPerHa: 115000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'Referencia BIO-G para lechuga de campo abierto cuando no hay tipo especifico.',
    ),
    'lettuce_protected_soil_generic': const YieldReference(
      id: 'lettuce_protected_soil_generic',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'Lechuga protegida en suelo (generica)',
      yieldLowTonPerHa: 30,
      yieldHighTonPerHa: 65,
      seedsLowPerHa: 80000,
      seedsHighPerHa: 140000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'Modelo para malla/invernadero en suelo; excluye hidroponia y sustratos inertes.',
    ),
    'lettuce_romaine_field': const YieldReference(
      id: 'lettuce_romaine_field',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'LE-01 lechuga romana / cos',
      yieldLowTonPerHa: 20,
      yieldHighTonPerHa: 50,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 95000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'LE-01 BIO-G; cabeza alargada de 1 corte. Depende de densidad, variedad, clima y mercado.',
    ),
    'lettuce_mini_romaine_field': const YieldReference(
      id: 'lettuce_mini_romaine_field',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'LE-02 mini romana / corazones',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 40,
      seedsLowPerHa: 90000,
      seedsHighPerHa: 140000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'LE-02 BIO-G; mas plantas por area y menor peso por planta.',
    ),
    'lettuce_iceberg_field': const YieldReference(
      id: 'lettuce_iceberg_field',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'LE-03 lechuga bola / iceberg',
      yieldLowTonPerHa: 25,
      yieldHighTonPerHa: 60,
      seedsLowPerHa: 50000,
      seedsHighPerHa: 80000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.calibrated,
      sourceMethod:
          'LE-03 BIO-G; cabeza compacta de mayor peso, ciclo mas largo y sensible a calor/bolting.',
    ),
    'lettuce_butterhead_field': const YieldReference(
      id: 'lettuce_butterhead_field',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'LE-04 lechuga mantequilla / butterhead',
      yieldLowTonPerHa: 15,
      yieldHighTonPerHa: 35,
      seedsLowPerHa: 60000,
      seedsHighPerHa: 95000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'LE-04 BIO-G; premium por textura, muy sensible a manejo de agua y sanidad.',
    ),
    'lettuce_looseleaf_field': const YieldReference(
      id: 'lettuce_looseleaf_field',
      cropId: 'lettuce',
      useType: 'fresh',
      displayName: 'LE-05 lechuga hoja suelta / baby leaf',
      yieldLowTonPerHa: 10,
      yieldHighTonPerHa: 30,
      seedsLowPerHa: 120000,
      seedsHighPerHa: 320000,
      isFreshMatter: true,
      confidence: YieldDataConfidence.modeled,
      sourceMethod:
          'LE-05 BIO-G; roseta abierta de 1 corte o multicorte; densidad alta segun sistema.',
    ),
  };

  /// Mapeo de referencia genérica forrajera por cultivo.
  static const Map<String, String> _genericForageIds = {
    'maize': 'generic_maize_forage',
    'wheat': 'wheat_forrajero',
    'barley': 'barley_forrajera_inifap',
    'oat': 'oat_forrajera',
  };

  /// Mapeo de referencia genérica de grano por cultivo.
  static const Map<String, String> _genericGrainIds = {
    'maize': 'generic_maize_white_grain',
    'wheat': 'wheat_generic',
    'barley': 'barley_generic',
    'oat': 'oat_generic',
    'bean': 'bean_generic',
  };

  /// Mapeo de referencia genérica de fruto fresco por cultivo.
  ///
  /// Para tomate, la referencia por defecto es campo abierto; la variante
  /// protegida se resuelve explícitamente con `genericFreshProtected`.
  static const Map<String, String> _genericFreshIds = {
    'tomato': 'tomato_field_generic',
    'cucumber': 'cucumber_field_generic',
    'chili': 'chili_field_generic',
    'eggplant': 'eggplant_field_generic',
    'squash': 'squash_field_generic',
    'lettuce': 'lettuce_field_generic',
  };

  static const Map<String, String> _genericFreshProtectedIds = {
    'tomato': 'tomato_protected_generic',
    'cucumber': 'cucumber_protected_soil_generic',
    'chili': 'chili_protected_soil_generic',
    'eggplant': 'eggplant_protected_soil_generic',
    'squash': 'squash_protected_soil_generic',
    'lettuce': 'lettuce_protected_soil_generic',
  };

  /// Devuelve la referencia genérica de fruto fresco (campo abierto por defecto).
  static YieldReference? genericFresh(String cropId) {
    final id = _genericFreshIds[cropId];
    return id == null ? null : byId[id];
  }

  /// Devuelve la referencia genérica de fruto fresco en ambiente protegido.
  static YieldReference? genericFreshProtected(String cropId) {
    final id = _genericFreshProtectedIds[cropId];
    return id == null ? null : byId[id];
  }

  /// Devuelve la referencia genérica de forraje para un cropId, o null si
  /// ese cultivo no soporta modo forraje.
  static YieldReference? genericForage(String cropId) {
    final id = _genericForageIds[cropId];
    return id == null ? null : byId[id];
  }

  /// Devuelve la referencia genérica de grano para un cropId.
  static YieldReference? genericGrain(String cropId) {
    final id = _genericGrainIds[cropId];
    return id == null ? null : byId[id];
  }

  static YieldReference? findById(String? id) {
    if (id == null || id.trim().isEmpty) return null;
    return byId[id.trim()];
  }
}
