import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/chili_profiles.dart';

const String kCropChili = 'chili';
const String kChiliDefaultCalendarId = 'chili_default';

const List<CropProfileEntry> chiliProfileEntries = [
  CropProfileEntry(
    id: kChGen,
    label: 'CH-GEN - Chile generico',
    cropId: kCropChili,
    subtitle: 'Perfil conservador, migrable y recomendado si no sabes el tipo',
    aliases: ['CH-GEN', 'CHGEN', 'Generico', 'Generic', 'No se', 'Otro chile'],
  ),
  CropProfileEntry(
    id: kCh01,
    label: 'CH-01 - Jalapeno',
    cropId: kCropChili,
    subtitle: 'Intermedio - fresco, proceso o chipotle',
    aliases: ['CH-01', 'CH01', 'Jalapeno', 'Chipotle'],
  ),
  CropProfileEntry(
    id: kCh02,
    label: 'CH-02 - Serrano',
    cropId: kCropChili,
    subtitle: 'Intermedio - alta carga y cosecha continua',
    aliases: ['CH-02', 'CH02', 'Serrano'],
  ),
  CropProfileEntry(
    id: kCh03,
    label: 'CH-03 - Poblano / Ancho',
    cropId: kCropChili,
    subtitle: 'Intermedio-largo - fresco como poblano, seco como ancho',
    aliases: ['CH-03', 'CH03', 'Poblano', 'Ancho', 'Mulato'],
  ),
  CropProfileEntry(
    id: kCh04,
    label: 'CH-04 - Chilaca / Pasilla',
    cropId: kCropChili,
    subtitle: 'Intermedio-largo - fruto largo orientado a secado',
    aliases: ['CH-04', 'CH04', 'Chilaca', 'Pasilla'],
  ),
  CropProfileEntry(
    id: kCh05,
    label: 'CH-05 - Mirasol / Guajillo',
    cropId: kCropChili,
    subtitle: 'Intermedio-largo - mercado seco principal',
    aliases: ['CH-05', 'CH05', 'Mirasol', 'Guajillo'],
  ),
  CropProfileEntry(
    id: kCh06,
    label: 'CH-06 - De arbol / Puya',
    cropId: kCropChili,
    subtitle: 'Intermedio - fruto pequeno, alta densidad, uso seco',
    aliases: [
      'CH-06',
      'CH06',
      'De arbol',
      'Arbol',
      'Puya',
      'De arbol fresco',
      'Chile de arbol fresco',
      'Puya seco',
    ],
  ),
  CropProfileEntry(
    id: kCh07,
    label: 'CH-07 - Habanero',
    cropId: kCropChili,
    subtitle: 'Capsicum chinense - mas termico y sensible',
    aliases: ['CH-07', 'CH07', 'Habanero', 'Capsicum chinense'],
  ),
  CropProfileEntry(
    id: kCh08,
    label: 'CH-08 - Pimiento morron / Chile gordo',
    cropId: kCropChili,
    subtitle: 'Fruto grande y alto potencial productivo',
    aliases: ['CH-08', 'CH08', 'Pimiento', 'Morron', 'Chile gordo'],
  ),
];

const List<CropVarietyEntry> chiliVarieties = [
  CropVarietyEntry(
    id: 'chili_jalapeno',
    label: 'Jalapeno',
    cropId: kCropChili,
    subtitle: 'Tipo - fresco / proceso / chipotle',
    defaultProfileId: kCh01,
    aliases: ['Jalapeno', 'Chipotle', 'CH-01', 'CH01'],
  ),
  CropVarietyEntry(
    id: 'chili_serrano',
    label: 'Serrano',
    cropId: kCropChili,
    subtitle: 'Tipo - alta carga y cosecha continua',
    defaultProfileId: kCh02,
    aliases: ['Serrano', 'CH-02', 'CH02'],
  ),
  CropVarietyEntry(
    id: 'chili_poblano_ancho',
    label: 'Poblano / Ancho',
    cropId: kCropChili,
    subtitle: 'Tipo - fresco o seco',
    defaultProfileId: kCh03,
    aliases: ['Poblano', 'Ancho', 'Mulato', 'CH-03', 'CH03'],
  ),
  CropVarietyEntry(
    id: 'chili_chilaca_pasilla',
    label: 'Chilaca / Pasilla',
    cropId: kCropChili,
    subtitle: 'Tipo - fruto largo orientado a secado',
    defaultProfileId: kCh04,
    aliases: ['Chilaca', 'Pasilla', 'CH-04', 'CH04'],
  ),
  CropVarietyEntry(
    id: 'chili_guajillo_mirasol',
    label: 'Guajillo / Mirasol',
    cropId: kCropChili,
    subtitle: 'Tipo - seco principalmente',
    defaultProfileId: kCh05,
    aliases: ['Guajillo', 'Mirasol', 'CH-05', 'CH05'],
  ),
  CropVarietyEntry(
    id: 'chili_arbol_puya',
    label: 'De arbol / Puya',
    cropId: kCropChili,
    subtitle: 'Tipo - fruto pequeno y alta densidad',
    defaultProfileId: kCh06,
    aliases: [
      'De arbol',
      'Arbol',
      'Puya',
      'De arbol fresco',
      'Chile de arbol fresco',
      'Puya seco',
      'CH-06',
      'CH06',
    ],
  ),
  CropVarietyEntry(
    id: 'chili_habanero',
    label: 'Habanero',
    cropId: kCropChili,
    subtitle: 'Tipo - Capsicum chinense, mas termico',
    defaultProfileId: kCh07,
    aliases: ['Habanero', 'Capsicum chinense', 'CH-07', 'CH07'],
  ),
  CropVarietyEntry(
    id: 'chili_bell_pepper',
    label: 'Pimiento morron / Chile gordo',
    cropId: kCropChili,
    subtitle: 'Tipo - fruto grande y alto potencial',
    defaultProfileId: kCh08,
    aliases: [
      'Pimiento',
      'Pimiento morron',
      'Morron',
      'Chile gordo',
      'Bell pepper',
      'CH-08',
      'CH08',
    ],
  ),
  CropVarietyEntry(
    id: 'chili_generic',
    label: 'No se / Otro chile',
    cropId: kCropChili,
    subtitle: 'Sin tipo definido (CH-GEN)',
    defaultProfileId: kChGen,
    aliases: [
      'Generico',
      'Chile generico',
      'Otro chile',
      'No se',
      'CH-GEN',
      'CHGEN',
    ],
    isGeneric: true,
  ),
];
