import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/spinach_profiles.dart';

const String kCropSpinach = 'spinach';
const String kSpinachDefaultCalendarId = 'spinach_default';

const List<CropProfileEntry> spinachProfileEntries = [
  CropProfileEntry(
    id: kSpGen,
    label: 'SP-GEN - Espinaca generica / no se todavia',
    cropId: kCropSpinach,
    subtitle:
        'Perfil conservador y migrable: puedes cambiar el tipo despues sin perder historial',
    aliases: [
      'SP-GEN',
      'SPGEN',
      'SP_GEN',
      'Espinaca',
      'Espinaca generica',
      'Otra espinaca',
      'Otra variedad',
      'No se',
      'No se todavia',
      'Spinach',
    ],
  ),
  CropProfileEntry(
    id: kSp01,
    label: 'SP-01 - Saboya / semi-saboya verano-calor',
    cropId: kCropSpinach,
    subtitle: 'Hoja rizada fresca con tolerancia relativa a calor',
    aliases: [
      'SP-01',
      'SP01',
      'Saboya verano',
      'Semi-saboya verano',
      'Verano calor',
      'Savoy summer',
      'Semi savoy summer',
    ],
  ),
  CropProfileEntry(
    id: kSp02,
    label: 'SP-02 - Saboya / semi-saboya invierno',
    cropId: kCropSpinach,
    subtitle: 'Hoja rizada para clima fresco y dias cortos',
    aliases: [
      'SP-02',
      'SP02',
      'Saboya invierno',
      'Semi-saboya invierno',
      'Dias cortos',
      'Savoy winter',
      'Winter savoy',
    ],
  ),
  CropProfileEntry(
    id: kSp03,
    label: 'SP-03 - Lisa / baby leaf / premium',
    cropId: kCropSpinach,
    subtitle: 'Hoja lisa tierna, baby leaf o mercado premium',
    aliases: [
      'SP-03',
      'SP03',
      'Lisa',
      'Baby leaf',
      'Baby spinach',
      'Premium',
      'Smooth baby',
    ],
  ),
  CropProfileEntry(
    id: kSp04,
    label: 'SP-04 - Oriental / manojo erecta',
    cropId: kCropSpinach,
    subtitle: 'Hoja erecta para manojo y corte fresco',
    aliases: [
      'SP-04',
      'SP04',
      'Oriental',
      'Manojo',
      'Bunching',
      'Oriental bunch',
      'Erecta',
    ],
  ),
  CropProfileEntry(
    id: kSp05,
    label: 'SP-05 - Proceso / industria',
    cropId: kCropSpinach,
    subtitle: 'Biomasa comercial uniforme para proceso',
    aliases: [
      'SP-05',
      'SP05',
      'Proceso',
      'Industria',
      'Industrial',
      'Processing',
    ],
  ),
];

const List<CropVarietyEntry> spinachVarieties = [
  CropVarietyEntry(
    id: 'spinach_generic',
    label: 'No se / Otra espinaca',
    cropId: kCropSpinach,
    subtitle: 'Perfil seguro y migrable: ajusta despues sin reiniciar',
    defaultProfileId: kSpGen,
    aliases: [
      'Espinaca',
      'Espinaca generica',
      'Otra espinaca',
      'Otra variedad',
      'No se',
      'No se todavia',
      'Spinach',
      'SP-GEN',
      'SPGEN',
    ],
    isGeneric: true,
  ),
  CropVarietyEntry(
    id: 'spinach_savoy_summer',
    label: 'Saboya / semi-saboya verano-calor',
    cropId: kCropSpinach,
    subtitle: 'Tipo - hoja rizada para clima con mas calor',
    defaultProfileId: kSp01,
    aliases: [
      'Saboya verano',
      'Semi-saboya verano',
      'Verano calor',
      'Savoy summer',
      'Semi savoy summer',
      'SP-01',
      'SP01',
    ],
  ),
  CropVarietyEntry(
    id: 'spinach_savoy_winter',
    label: 'Saboya / semi-saboya invierno',
    cropId: kCropSpinach,
    subtitle: 'Tipo - hoja rizada para clima fresco y dias cortos',
    defaultProfileId: kSp02,
    aliases: [
      'Saboya invierno',
      'Semi-saboya invierno',
      'Invierno',
      'Dias cortos',
      'Savoy winter',
      'SP-02',
      'SP02',
    ],
  ),
  CropVarietyEntry(
    id: 'spinach_smooth_baby',
    label: 'Lisa / baby leaf / premium',
    cropId: kCropSpinach,
    subtitle: 'Tipo - hoja lisa tierna de alta sensibilidad visual',
    defaultProfileId: kSp03,
    aliases: [
      'Lisa',
      'Espinaca lisa',
      'Baby leaf',
      'Baby spinach',
      'Premium',
      'Smooth baby',
      'SP-03',
      'SP03',
    ],
  ),
  CropVarietyEntry(
    id: 'spinach_oriental_bunching',
    label: 'Oriental / manojo erecta',
    cropId: kCropSpinach,
    subtitle: 'Tipo - hoja erecta para manojo',
    defaultProfileId: kSp04,
    aliases: [
      'Oriental',
      'Espinaca oriental',
      'Manojo',
      'Bunching',
      'Oriental bunch',
      'Erecta',
      'SP-04',
      'SP04',
    ],
  ),
  CropVarietyEntry(
    id: 'spinach_processing',
    label: 'Proceso / industria',
    cropId: kCropSpinach,
    subtitle: 'Tipo - hoja para proceso e industria',
    defaultProfileId: kSp05,
    aliases: [
      'Proceso',
      'Industria',
      'Industrial',
      'Processing',
      'Process spinach',
      'SP-05',
      'SP05',
    ],
  ),
];
