import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/eggplant_models.dart';

class EggplantUniversalProfile {
  const EggplantUniversalProfile({
    required this.byStage,
    required this.weights,
  });

  final Map<EggplantStageKey, StageTargets> byStage;
  final Map<EggplantStageKey, StageWeights> weights;
}

const AgroRange _phEarly = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 6.8,
  highMin: 7.3,
);

const AgroRange _phStd = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 6.8,
  highMin: 7.3,
);

const AgroRange _phReproductive = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 6.8,
  highMin: 7.3,
);

const AgroRange _ecEarly = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecVeg = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecReproductive = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _soilTempEarly = AgroRange(
  lowMax: 15,
  optimalMin: 20,
  optimalMax: 30,
  highMin: 32,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 15,
  optimalMin: 20,
  optimalMax: 30,
  highMin: 32,
);

const AgroRange _moistureActive = AgroRange(
  lowMax: 50,
  optimalMin: 60,
  optimalMax: 90,
  highMin: 95,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required double caPriority,
  required double mgPriority,
  required double sPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  required String caGuide,
  required String mgGuide,
  required String sGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.78,
}) {
  AgroRange idx(double p) => AgroRange(
        lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
        optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
        optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
        highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
      );

  AgroRange ppm(double low, double min, double max) => AgroRange(
        lowMax: low,
        optimalMin: min,
        optimalMax: max,
        highMin: max + (max - min) * 0.55,
      );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: caPriority,
    mgPriority: mgPriority,
    sPriority: sPriority,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs: caGuide,
    mgShortGuidanceEs: mgGuide,
    sShortGuidanceEs: sGuide,
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final EggplantUniversalProfile eggplantUniversalV1 = EggplantUniversalProfile(
  byStage: <EggplantStageKey, StageTargets>{
    EggplantStageKey.germinacion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 22,
      nOptMin: 28,
      nOptMax: 55,
      pLow: 40,
      pOptMin: 50,
      pOptMax: 74,
      kLow: 60,
      kOptMin: 75,
      kOptMax: 120,
      nPriority: 0.22,
      pPriority: 0.80,
      kPriority: 0.30,
      caPriority: 0.38,
      mgPriority: 0.30,
      sPriority: 0.24,
      nWindow: 'Arranque prudente de N',
      pWindow: 'Raiz y energia inicial',
      kWindow: 'Soporte minimo de K',
      nGuide: 'N bajo control; exceso de sales frena plantula.',
      pGuide: 'P temprano sostiene raiz y emergencia.',
      kGuide: 'K solo como base inicial.',
      caGuide: 'Ca de base para estructura.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S en mantenimiento.',
      confidence: 0.72,
    ),
    EggplantStageKey.establecimiento: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 30,
      nOptMin: 38,
      nOptMax: 65,
      pLow: 42,
      pOptMin: 52,
      pOptMax: 78,
      kLow: 70,
      kOptMin: 85,
      kOptMax: 130,
      nPriority: 0.42,
      pPriority: 0.84,
      kPriority: 0.42,
      caPriority: 0.52,
      mgPriority: 0.38,
      sPriority: 0.30,
      nWindow: 'Soporte moderado de N',
      pWindow: 'Pegue y raiz',
      kWindow: 'Balance inicial',
      nGuide: 'N acompana sin forzar follaje.',
      pGuide: 'P starter es clave para pegue y raiz.',
      kGuide: 'K acompana balance hidrico temprano.',
      caGuide: 'Ca empieza a sostener pared celular.',
      mgGuide: 'Mg apoya primeras hojas.',
      sGuide: 'S en soporte base.',
      nHint: 'Evitar pulsos fuertes de N en trasplante reciente.',
      pHint: 'Corregir P temprano si la lectura queda corta.',
      kHint: 'Mantener K de base sin subir sales.',
      confidence: 0.80,
    ),
    EggplantStageKey.vegetativo: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecVeg,
      nLow: 52,
      nOptMin: 65,
      nOptMax: 100,
      pLow: 36,
      pOptMin: 45,
      pOptMax: 68,
      kLow: 90,
      kOptMin: 110,
      kOptMax: 160,
      nPriority: 0.76,
      pPriority: 0.50,
      kPriority: 0.60,
      caPriority: 0.58,
      mgPriority: 0.52,
      sPriority: 0.38,
      nWindow: 'Follaje con mesura',
      pWindow: 'Soporte de P',
      kWindow: 'Reserva antes de flor',
      nGuide: 'N importante para hoja activa, sin exceso vegetativo.',
      pGuide: 'P pasa a soporte; corregir si queda corto.',
      kGuide: 'K sube gradualmente antes de floracion.',
      caGuide: 'Ca sostiene estructura y brotes.',
      mgGuide: 'Mg sostiene fotosintesis.',
      sGuide: 'S apoya vigor y calidad.',
      nHint: 'No llegar a floracion con planta vegetada de mas.',
      kHint: 'Preparar reserva de K para floracion y cuajado.',
      confidence: 0.84,
    ),
    EggplantStageKey.floracion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phReproductive,
      ec: _ecReproductive,
      nLow: 44,
      nOptMin: 52,
      nOptMax: 84,
      pLow: 34,
      pOptMin: 42,
      pOptMax: 66,
      kLow: 105,
      kOptMin: 130,
      kOptMax: 175,
      nPriority: 0.58,
      pPriority: 0.52,
      kPriority: 0.76,
      caPriority: 0.78,
      mgPriority: 0.60,
      sPriority: 0.42,
      nWindow: 'N equilibrado para flor',
      pWindow: 'Energia reproductiva',
      kWindow: 'K subiendo para amarre',
      nGuide: 'N se modera: exceso tira flor y retrasa cuaje.',
      pGuide: 'P sostiene energia de floracion.',
      kGuide: 'K empieza a mandar; mantener humedad pareja.',
      caGuide: 'Ca importante antes del fruto joven.',
      mgGuide: 'Mg sostiene hoja activa.',
      sGuide: 'S acompana calidad.',
      nHint: 'Evitar aplicaciones altas de N en floracion.',
      pHint: 'P solo si lectura o analisis lo justifica.',
      kHint: 'Subir K sin golpes de sales.',
      confidence: 0.86,
    ),
    EggplantStageKey.cuajado: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phReproductive,
      ec: _ecReproductive,
      nLow: 40,
      nOptMin: 48,
      nOptMax: 78,
      pLow: 32,
      pOptMin: 40,
      pOptMax: 62,
      kLow: 120,
      kOptMin: 145,
      kOptMax: 195,
      nPriority: 0.52,
      pPriority: 0.44,
      kPriority: 0.88,
      caPriority: 0.88,
      mgPriority: 0.64,
      sPriority: 0.42,
      nWindow: 'N moderado para cuaje',
      pWindow: 'P de soporte',
      kWindow: 'K fuerte para amarre',
      nGuide: 'N bajo control para no tirar flor ni cuaje.',
      pGuide: 'P acompana, pero no rescata tarde.',
      kGuide: 'K, Ca y agua estable dominan el amarre.',
      caGuide: 'Ca clave para calidad inicial del fruto.',
      mgGuide: 'Mg sostiene fotosintesis de planta cargada.',
      sGuide: 'S en soporte.',
      nHint: 'No meter pulsos altos de N en amarre activo.',
      kHint: 'Si K cae, corregir con prioridad y humedad estable.',
      confidence: 0.88,
    ),
    EggplantStageKey.llenado: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecReproductive,
      nLow: 34,
      nOptMin: 42,
      nOptMax: 72,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 58,
      kLow: 125,
      kOptMin: 150,
      kOptMax: 205,
      nPriority: 0.46,
      pPriority: 0.36,
      kPriority: 0.92,
      caPriority: 0.84,
      mgPriority: 0.66,
      sPriority: 0.40,
      nWindow: 'N a la baja',
      pWindow: 'P de mantenimiento',
      kWindow: 'K dominante para llenado',
      nGuide: 'N baja; exceso resta calidad y abre vegetatividad.',
      pGuide: 'P de soporte, respuesta moderada.',
      kGuide: 'K domina llenado, brillo, peso y firmeza.',
      caGuide: 'Ca cuida pared, firmeza y calidad visual.',
      mgGuide: 'Mg sostiene llenado desde hoja sana.',
      sGuide: 'S acompana calidad.',
      nHint: 'No perseguir N como cuello principal en llenado.',
      kHint: 'Priorizar K soluble sin golpes osmoticos fuertes.',
      confidence: 0.88,
    ),
    EggplantStageKey.cosechaProgresiva: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecReproductive,
      nLow: 32,
      nOptMin: 38,
      nOptMax: 68,
      pLow: 26,
      pOptMin: 34,
      pOptMax: 56,
      kLow: 118,
      kOptMin: 145,
      kOptMax: 195,
      nPriority: 0.46,
      pPriority: 0.34,
      kPriority: 0.86,
      caPriority: 0.76,
      mgPriority: 0.58,
      sPriority: 0.38,
      nWindow: 'N de mantenimiento',
      pWindow: 'P de mantenimiento',
      kWindow: 'K sostenido de cosecha',
      nGuide: 'N solo para sostener cortes productivos.',
      pGuide: 'P rara vez es el cuello en cosecha.',
      kGuide: 'K sostenido mantiene cortes, calidad y firmeza.',
      caGuide: 'Ca mantiene firmeza en cortes continuos.',
      mgGuide: 'Mg sostiene hoja funcional.',
      sGuide: 'S en soporte.',
      nHint: 'Evitar exceso de N en cosecha progresiva.',
      kHint: 'Mantener K constante y balanceado con Ca/Mg.',
      confidence: 0.82,
    ),
    EggplantStageKey.finCiclo: _targets(
      moisture: const AgroRange(
        lowMax: 22,
        optimalMin: 35,
        optimalMax: 60,
        highMin: 75,
      ),
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 18,
      nOptMin: 22,
      nOptMax: 48,
      pLow: 20,
      pOptMin: 25,
      pOptMax: 50,
      kLow: 80,
      kOptMin: 95,
      kOptMax: 155,
      nPriority: 0.20,
      pPriority: 0.18,
      kPriority: 0.32,
      caPriority: 0.28,
      mgPriority: 0.25,
      sPriority: 0.20,
      nWindow: 'Cierre de N',
      pWindow: 'Cierre de P',
      kWindow: 'Cierre de K',
      nGuide: 'Lectura para planear el siguiente ciclo.',
      pGuide: 'P sirve mas para ajustar la siguiente base.',
      kGuide: 'K solo sostiene cosecha residual.',
      caGuide: 'Ca ya no corrige calidad del fruto actual.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S en mantenimiento.',
      nHint: 'No corregir tarde; documentar y cerrar.',
      pHint: 'Usar lectura para pre-siembra del siguiente ciclo.',
      kHint: 'Usar lectura para trazabilidad del plan.',
      confidence: 0.66,
    ),
  },
  weights: const <EggplantStageKey, StageWeights>{
    EggplantStageKey.germinacion: StageWeights(
      moisture: 0.32,
      soilTemp: 0.12,
      resistance: 0.12,
      ph: 0.12,
      ec: 0.14,
      npk: 0.18,
    ),
    EggplantStageKey.establecimiento: StageWeights(
      moisture: 0.30,
      soilTemp: 0.10,
      resistance: 0.12,
      ph: 0.12,
      ec: 0.12,
      npk: 0.24,
    ),
    EggplantStageKey.vegetativo: StageWeights(
      moisture: 0.27,
      soilTemp: 0.07,
      resistance: 0.10,
      ph: 0.10,
      ec: 0.12,
      npk: 0.34,
    ),
    EggplantStageKey.floracion: StageWeights(
      moisture: 0.32,
      soilTemp: 0.08,
      resistance: 0.07,
      ph: 0.09,
      ec: 0.13,
      npk: 0.31,
    ),
    EggplantStageKey.cuajado: StageWeights(
      moisture: 0.34,
      soilTemp: 0.08,
      resistance: 0.06,
      ph: 0.08,
      ec: 0.15,
      npk: 0.29,
    ),
    EggplantStageKey.llenado: StageWeights(
      moisture: 0.31,
      soilTemp: 0.06,
      resistance: 0.07,
      ph: 0.08,
      ec: 0.15,
      npk: 0.33,
    ),
    EggplantStageKey.cosechaProgresiva: StageWeights(
      moisture: 0.29,
      soilTemp: 0.06,
      resistance: 0.08,
      ph: 0.08,
      ec: 0.14,
      npk: 0.35,
    ),
    EggplantStageKey.finCiclo: StageWeights(
      moisture: 0.22,
      soilTemp: 0.06,
      resistance: 0.14,
      ph: 0.14,
      ec: 0.14,
      npk: 0.30,
    ),
  },
);
