import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/eggplant_profiles.dart';

const String kCropEggplant = 'eggplant';
const String kEggplantDefaultCalendarId = 'eggplant_default';

const List<CropProfileEntry> eggplantProfileEntries = [
  CropProfileEntry(
    id: kBeGen,
    label: 'BE-GEN - Berenjena genérica',
    cropId: kCropEggplant,
    subtitle: 'Perfil conservador, migrable y recomendado si no sabes el tipo',
    aliases: [
      'BE-GEN',
      'BEGEN',
      'Generica',
      'Genérica',
      'Generico',
      'Genérico',
      'Generic',
      'No se',
      'No sé',
      'Otra berenjena',
      'Berenjena generica',
      'Berenjena genérica',
    ],
  ),
  CropProfileEntry(
    id: kBe01,
    label: 'BE-01 - Berenjena larga / semilarga morada',
    cropId: kCropEggplant,
    subtitle: 'Tipo dominante - fruto fresco y cosecha progresiva',
    aliases: [
      'BE-01',
      'BE01',
      'Larga',
      'Semilarga',
      'Morada larga',
      'Larga morada',
      'Berenjena larga',
      'Berenjena semilarga',
      'Semilarga morada',
      'Oriental',
      'China',
      'Berenjena china',
      'Barcelona',
      'Dark Night',
      'Orestia',
      'Napoli',
      'Nápoli',
    ],
  ),
  CropProfileEntry(
    id: kBe02,
    label: 'BE-02 - Berenjena oval / bola morada',
    cropId: kCropEggplant,
    subtitle: 'Fruto fresco, tamaño y uniformidad de mercado',
    aliases: [
      'BE-02',
      'BE02',
      'Oval',
      'Bola',
      'Bola morada',
      'Oval morada',
      'Berenjena bola',
      'Berenjena oval',
      'Americana',
      'Morada grande',
      'Italiana',
      'Berenjena italiana',
      'Berenjena italiana / clasica morada',
      'Berenjena italiana / clásica morada',
      'Clasica',
      'Clásica',
      'Clasica morada',
      'Clásica morada',
      'Morada clasica',
      'Morada clásica',
      'Black Beauty',
      'Night Shadow',
      'Emma F1',
      'eggplant_italian_purple',
      'eggplant_italian_black',
      'eggplant_oval_round',
    ],
  ),
  CropProfileEntry(
    id: kBe03,
    label: 'BE-03 - Berenjena rayada / listada',
    cropId: kCropEggplant,
    subtitle: 'Nicho/gourmet; mayor cuidado de calidad visual',
    aliases: [
      'BE-03',
      'BE03',
      'Rayada',
      'Listada',
      'Jaspeada',
      'Berenjena rayada',
      'Berenjena listada',
      'Graffiti',
      'Grafiti',
    ],
  ),
  CropProfileEntry(
    id: kBe04,
    label: 'BE-04 - Berenjena blanca',
    cropId: kCropEggplant,
    subtitle: 'Nicho de fruto fresco; alta sensibilidad visual',
    aliases: [
      'BE-04',
      'BE04',
      'Blanca',
      'Berenjena blanca',
      'White Egg',
      'Blanca F1',
      'Otra blanca',
    ],
  ),
];

const List<CropVarietyEntry> eggplantVarieties = [
  CropVarietyEntry(
    id: 'eggplant_long_purple',
    label: 'Berenjena larga / semilarga morada',
    cropId: kCropEggplant,
    subtitle: 'Tipo - fruto fresco morado alargado',
    defaultProfileId: kBe01,
    aliases: [
      'Barcelona',
      'Dark Night',
      'Orestia',
      'Napoli',
      'Nápoli',
      'Morada larga',
      'Larga morada',
      'Berenjena larga',
      'Berenjena semilarga',
      'Semilarga morada',
      'Oriental',
      'China',
      'Berenjena china',
      'Otra variedad larga',
      'BE-01',
      'BE01',
    ],
  ),
  CropVarietyEntry(
    id: 'eggplant_italian_purple',
    label: 'Berenjena italiana / clásica morada',
    cropId: kCropEggplant,
    subtitle: 'Tipo - clásica morada de fruto ovalado',
    defaultProfileId: kBe02,
    aliases: [
      'Italiana',
      'Berenjena italiana',
      'Berenjena italiana / clasica morada',
      'Berenjena italiana / clásica morada',
      'Italiana clasica morada',
      'Italiana clásica morada',
      'Italian',
      'Clasica',
      'Clásica',
      'Clasica morada',
      'Clásica morada',
      'Morada clasica',
      'Morada clásica',
      'Black Beauty',
      'eggplant_italian_black',
      'BE-02',
      'BE02',
    ],
  ),
  CropVarietyEntry(
    id: 'eggplant_oval_round',
    label: 'Berenjena oval / bola morada',
    cropId: kCropEggplant,
    subtitle: 'Tipo - oval o bola morada',
    defaultProfileId: kBe02,
    aliases: [
      'Night Shadow',
      'Emma F1',
      'Berenjena bola',
      'Berenjena oval',
      'Oval',
      'Bola',
      'Bola morada',
      'Oval morada',
      'Americana',
      'Morada grande',
      'Otra variedad oval',
      'BE-02',
      'BE02',
    ],
  ),
  CropVarietyEntry(
    id: 'eggplant_striped',
    label: 'Berenjena rayada / listada',
    cropId: kCropEggplant,
    subtitle: 'Tipo - nicho/gourmet de calidad visual',
    defaultProfileId: kBe03,
    aliases: [
      'Berenjena rayada',
      'Berenjena listada',
      'Rayada',
      'Listada',
      'Jaspeada',
      'Graffiti',
      'Grafiti',
      'Otra variedad rayada',
      'BE-03',
      'BE03',
    ],
  ),
  CropVarietyEntry(
    id: 'eggplant_white',
    label: 'Berenjena blanca',
    cropId: kCropEggplant,
    subtitle: 'Tipo - fruto blanco de nicho',
    defaultProfileId: kBe04,
    aliases: [
      'Berenjena blanca',
      'Blanca',
      'White Egg',
      'Blanca F1',
      'Otra variedad blanca',
      'BE-04',
      'BE04',
    ],
  ),
  CropVarietyEntry(
    id: 'eggplant_generic',
    label: 'No sé / Otra berenjena',
    cropId: kCropEggplant,
    subtitle: 'Usar perfil seguro si no sabes el tipo',
    defaultProfileId: kBeGen,
    aliases: [
      'Generica',
      'Genérica',
      'Berenjena generica',
      'Berenjena genérica',
      'Otra berenjena',
      'No se',
      'No sé',
      'BE-GEN',
      'BEGEN',
    ],
    isGeneric: true,
  ),
];
