import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/bean_profiles.dart';

const String kCropBean = 'bean';
const String kBeanDefaultCalendarId = 'bean_default';

const List<CropProfileEntry> beanProfileEntries = [
  CropProfileEntry(
    id: kFj01,
    label: 'FJ-01 · Precoz',
    cropId: kCropBean,
    subtitle: 'Negro temprano',
    aliases: ['FJ-01', 'FJ01', 'Precoz'],
  ),
  CropProfileEntry(
    id: kFj02,
    label: 'FJ-02 · Intermedio',
    cropId: kCropBean,
    subtitle: 'Negro / Bayo / Azufrado / Blanco',
    aliases: ['FJ-02', 'FJ02', 'Intermedio'],
  ),
  CropProfileEntry(
    id: kFj03,
    label: 'FJ-03 · Intermedio largo',
    cropId: kCropBean,
    subtitle: 'Pinto / Flor de Mayo / Flor de Junio',
    aliases: ['FJ-03', 'FJ03', 'Intermedio largo'],
  ),
  CropProfileEntry(
    id: kFj04,
    label: 'FJ-04 · Temporal largo',
    cropId: kCropBean,
    subtitle: 'Peruano / Canario / >115 días',
    aliases: ['FJ-04', 'FJ04', 'Temporal largo'],
  ),
  CropProfileEntry(
    id: kFjGen,
    label: 'FJ-GEN · Intermedio conservador',
    cropId: kCropBean,
    subtitle: 'Perfil general',
    aliases: ['FJ-GEN', 'FJGEN', 'Genérico', 'Generico'],
  ),
];

const List<CropVarietyEntry> beanVarieties = [
  CropVarietyEntry(
    id: 'bean_negro_temprano',
    label: 'Frijol negro temprano',
    cropId: kCropBean,
    subtitle: 'Tipo · Precoz',
    defaultProfileId: kFj01,
    aliases: [
      'Negro temprano',
      'Verdín',
      'Verdin',
      'Frailescano',
      'Sangre Maya',
      'FJ-01',
      'FJ01',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_negro',
    label: 'Frijol negro',
    cropId: kCropBean,
    subtitle: 'Tipo · Intermedio',
    defaultProfileId: kFj02,
    aliases: [
      'Negro',
      'Negro Jamapa',
      'Negro INIFAP',
      'Negro Comapa',
      'Negro Veracruz',
      'Negro San Luis',
      'Negro Tacaná',
      'Negro Tacana',
      'Negro Huasteco',
      'FJ-02',
      'FJ02',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_pinto',
    label: 'Frijol pinto',
    cropId: kCropBean,
    subtitle: 'Tipo · Intermedio largo',
    defaultProfileId: kFj03,
    aliases: [
      'Pinto',
      'Pinto Saltillo',
      'Pinto Durango',
      'Pinto Centenario',
      'Pinto Mestizo',
      'Pinto Libertad',
      'FJ-03',
      'FJ03',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_flor_mayo_junio',
    label: 'Frijol Flor de Mayo / Flor de Junio',
    cropId: kCropBean,
    subtitle: 'Tipo · Intermedio largo',
    defaultProfileId: kFj03,
    aliases: [
      'Flor de Mayo',
      'Flor de Junio',
      'Flor de Mayo / Flor de Junio',
      'Flor de Mayo Dolores',
      'Flor de Junio León',
      'Flor de Junio Leon',
      'Junio León',
      'Junio Leon',
      'Dalia',
      'FJ-03',
      'FJ03',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_bayo_azufrado_blanco',
    label: 'Frijol bayo / azufrado / blanco',
    cropId: kCropBean,
    subtitle: 'Tipo · Intermedio',
    defaultProfileId: kFj02,
    aliases: [
      'Bayo',
      'Azufrado',
      'Blanco',
      'Bayo Azteca',
      'Azufrado Higuera',
      'Azufrasin',
      'Aluyori',
      'FJ-02',
      'FJ02',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_peruano',
    label: 'Frijol peruano',
    cropId: kCropBean,
    subtitle: 'Tipo · Temporal largo',
    defaultProfileId: kFj04,
    aliases: [
      'Peruano',
      'Frijol peruano',
      'Peruano Bola',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_canario',
    label: 'Frijol canario',
    cropId: kCropBean,
    subtitle: 'Tipo · Temporal largo',
    defaultProfileId: kFj04,
    aliases: [
      'Canario',
      'Frijol canario',
      'Mayocoba',
      'Frijol Mayocoba',
    ],
  ),
  CropVarietyEntry(
    id: 'bean_generic',
    label: 'Frijol genérico',
    cropId: kCropBean,
    subtitle: 'Usar perfil general',
    defaultProfileId: kFjGen,
    aliases: [
      'Genérico',
      'Generico',
      'Frijol genérico',
      'Frijol generico',
      'FJ-GEN',
      'FJGEN',
    ],
    isGeneric: true,
  ),
];
