import 'package:bio_g/widgets/seeds/garlic_models.dart';
import 'package:bio_g/widgets/seeds/maize_models.dart';

const String kAgGen = 'ag_gen';
const String kAg01 = 'ag_01';
const String kAg02 = 'ag_02';
const String kAg03 = 'ag_03';
const String kAg04 = 'ag_04';
const String kAg05 = 'ag_05';

/// Perfiles biologicos de ajo basados en los TXT BIO-G.
///
/// AG-GEN es la entrada SKIP segura y migrable: no asume color, origen ni
/// destino final. Cambiar de AG-GEN a AG-01..AG-05 no debe reiniciar la
/// memoria del cultivo.
const Map<String, GarlicProfile> garlicProfiles = {
  kAgGen: GarlicProfile(
    id: kAgGen,
    label: 'AG-GEN - No se / Otro ajo',
    useType: 'Bulbo de ajo generico - configuracion segura',
    marketType: GarlicMarketType.generic,
    garlicUseType: GarlicUseType.flexible,
    coldRequirementClass: GarlicColdRequirementClass.unknown,
    neckClass: GarlicNeckClass.unknown,
    e2EndDay: 35,
    e3EndDay: 90,
    e4EndDay: 120,
    e5EndDay: 135,
    e6EndDay: 195,
    e7EndDay: 230,
    e8EndDay: 245,
    e9EndDay: 260,
    cycleDays: RangeInt(190, 240),
    densityPlantsPerHa: RangeInt(250000, 500000),
    referenceYieldTHa: RangeDouble(6, 13),
    isGenericProfile: true,
    vernalizationSensitivity01: 0.72,
    scapeSensitivity01: 0.55,
    bulbQualitySensitivity01: 0.78,
    salinitySensitivity01: 0.82,
    seedCloveRisk01: 0.65,
  ),
  kAg01: GarlicProfile(
    id: kAg01,
    label: 'AG-01 - Ajo blanco / Perla',
    useType: 'Blanco o perla; bulbo comercial curado',
    marketType: GarlicMarketType.whitePearl,
    garlicUseType: GarlicUseType.curedBulbFresh,
    coldRequirementClass: GarlicColdRequirementClass.medium,
    neckClass: GarlicNeckClass.softneck,
    e2EndDay: 32,
    e3EndDay: 85,
    e4EndDay: 115,
    e5EndDay: 128,
    e6EndDay: 185,
    e7EndDay: 222,
    e8EndDay: 238,
    e9EndDay: 252,
    cycleDays: RangeInt(190, 230),
    densityPlantsPerHa: RangeInt(300000, 520000),
    referenceYieldTHa: RangeDouble(10, 17),
    isPremiumBulb: true,
    isStorageFocused: true,
    vernalizationSensitivity01: 0.72,
    scapeSensitivity01: 0.48,
    bulbQualitySensitivity01: 0.84,
    salinitySensitivity01: 0.82,
    seedCloveRisk01: 0.55,
  ),
  kAg02: GarlicProfile(
    id: kAg02,
    label: 'AG-02 - Ajo jaspeado / Calera / rayado',
    useType: 'Jaspeado, rayado o Calera; bulbo comercial de alto potencial',
    marketType: GarlicMarketType.jaspeadoCalera,
    garlicUseType: GarlicUseType.curedBulbFresh,
    coldRequirementClass: GarlicColdRequirementClass.mediumHigh,
    neckClass: GarlicNeckClass.semiHardneck,
    e2EndDay: 35,
    e3EndDay: 95,
    e4EndDay: 128,
    e5EndDay: 140,
    e6EndDay: 205,
    e7EndDay: 238,
    e8EndDay: 252,
    e9EndDay: 268,
    cycleDays: RangeInt(205, 245),
    densityPlantsPerHa: RangeInt(300000, 560000),
    referenceYieldTHa: RangeDouble(11, 20),
    isPremiumBulb: true,
    isStorageFocused: true,
    vernalizationSensitivity01: 0.82,
    scapeSensitivity01: 0.66,
    bulbQualitySensitivity01: 0.86,
    salinitySensitivity01: 0.84,
    seedCloveRisk01: 0.56,
  ),
  kAg03: GarlicProfile(
    id: kAg03,
    label: 'AG-03 - Ajo morado',
    useType: 'Morado; mercado regional/premium por color',
    marketType: GarlicMarketType.purple,
    garlicUseType: GarlicUseType.curedBulbFresh,
    coldRequirementClass: GarlicColdRequirementClass.high,
    neckClass: GarlicNeckClass.semiHardneck,
    e2EndDay: 38,
    e3EndDay: 100,
    e4EndDay: 135,
    e5EndDay: 148,
    e6EndDay: 212,
    e7EndDay: 245,
    e8EndDay: 262,
    e9EndDay: 278,
    cycleDays: RangeInt(210, 250),
    densityPlantsPerHa: RangeInt(240000, 460000),
    referenceYieldTHa: RangeDouble(7, 14),
    isPremiumBulb: true,
    vernalizationSensitivity01: 0.88,
    scapeSensitivity01: 0.70,
    bulbQualitySensitivity01: 0.88,
    salinitySensitivity01: 0.84,
    seedCloveRisk01: 0.58,
  ),
  kAg04: GarlicProfile(
    id: kAg04,
    label: 'AG-04 - Ajo criollo / regional',
    useType: 'Criollo o regional; manejo conservador y semilla local',
    marketType: GarlicMarketType.creoleRegional,
    garlicUseType: GarlicUseType.flexible,
    coldRequirementClass: GarlicColdRequirementClass.medium,
    neckClass: GarlicNeckClass.unknown,
    e2EndDay: 36,
    e3EndDay: 92,
    e4EndDay: 124,
    e5EndDay: 138,
    e6EndDay: 198,
    e7EndDay: 232,
    e8EndDay: 248,
    e9EndDay: 264,
    cycleDays: RangeInt(190, 238),
    densityPlantsPerHa: RangeInt(200000, 440000),
    referenceYieldTHa: RangeDouble(5, 13),
    vernalizationSensitivity01: 0.76,
    scapeSensitivity01: 0.58,
    bulbQualitySensitivity01: 0.76,
    salinitySensitivity01: 0.82,
    seedCloveRisk01: 0.78,
  ),
  kAg05: GarlicProfile(
    id: kAg05,
    label: 'AG-05 - Ajo chino / coreano',
    useType: 'Chino o coreano; verificar trazabilidad y adaptacion local',
    marketType: GarlicMarketType.chineseKorean,
    garlicUseType: GarlicUseType.curedBulbFresh,
    coldRequirementClass: GarlicColdRequirementClass.mediumHigh,
    neckClass: GarlicNeckClass.unknown,
    e2EndDay: 35,
    e3EndDay: 95,
    e4EndDay: 130,
    e5EndDay: 140,
    e6EndDay: 202,
    e7EndDay: 238,
    e8EndDay: 254,
    e9EndDay: 270,
    cycleDays: RangeInt(205, 240),
    densityPlantsPerHa: RangeInt(280000, 520000),
    referenceYieldTHa: RangeDouble(10, 16),
    isStorageFocused: true,
    vernalizationSensitivity01: 0.80,
    scapeSensitivity01: 0.62,
    bulbQualitySensitivity01: 0.80,
    salinitySensitivity01: 0.83,
    seedCloveRisk01: 0.66,
  ),
};

const Map<String, String> _garlicProfileAliasToCanonical = {
  // AG-GEN
  'ag-gen': kAgGen,
  'aggen': kAgGen,
  'ag_gen': kAgGen,
  'ajo': kAgGen,
  'ajos': kAgGen,
  'garlic': kAgGen,
  'crop_garlic': kAgGen,
  'ajo generico': kAgGen,
  'ajo generica': kAgGen,
  'garlic_generic': kAgGen,
  'otra variedad': kAgGen,
  'otro ajo': kAgGen,
  'otra ajo': kAgGen,
  'no se': kAgGen,
  'no se todavia': kAgGen,
  'skip': kAgGen,

  // AG-01 blanco / perla
  'ag-01': kAg01,
  'ag01': kAg01,
  'ag_01': kAg01,
  'ajo blanco': kAg01,
  'blanco': kAg01,
  'perla': kAg01,
  'ajo perla': kAg01,
  'garlic_white_pearl': kAg01,
  'garlic_orion': kAg01,
  'garlic_san_marqueno': kAg01,
  'orion': kAg01,
  'orion blanco': kAg01,
  'san marqueno': kAg01,
  'diamante': kAg01,
  'blanco de egipto': kAg01,

  // AG-02 jaspeado / Calera / rayado
  'ag-02': kAg02,
  'ag02': kAg02,
  'ag_02': kAg02,
  'ajo jaspeado': kAg02,
  'jaspeado': kAg02,
  'calera': kAg02,
  'rayado': kAg02,
  'garlic_jaspeado_calera': kAg02,
  'garlic_cezac_06': kAg02,
  'garlic_barretero': kAg02,
  'cezac 06': kAg02,
  'cezac06': kAg02,
  'jaspeado calera': kAg02,
  'barretero': kAg02,
  'inifap 94': kAg02,
  'inifap94': kAg02,
  'tacatzcuaro': kAg02,
  'tinguindin': kAg02,

  // AG-03 morado
  'ag-03': kAg03,
  'ag03': kAg03,
  'ag_03': kAg03,
  'ajo morado': kAg03,
  'morado': kAg03,
  'garlic_purple': kAg03,

  // AG-04 criollo / regional
  'ag-04': kAg04,
  'ag04': kAg04,
  'ag_04': kAg04,
  'ajo criollo': kAg04,
  'criollo regional': kAg04,
  'ajo regional': kAg04,
  'regional': kAg04,
  'garlic_criollo_regional': kAg04,

  // AG-05 chino / coreano
  'ag-05': kAg05,
  'ag05': kAg05,
  'ag_05': kAg05,
  'ajo chino': kAg05,
  'ajo coreano': kAg05,
  'chino': kAg05,
  'coreano': kAg05,
  'chino calera': kAg05,
  'chino cedel': kAg05,
  'garlic_chinese_korean': kAg05,
};

String? resolveCanonicalGarlicProfileId(String raw) {
  final normalized = raw.trim().toLowerCase();
  if (normalized.isEmpty) return null;
  if (garlicProfiles.containsKey(normalized)) return normalized;
  return _garlicProfileAliasToCanonical[normalized];
}
