import 'package:bio_g/widgets/seeds/maize_models.dart';
import 'package:bio_g/widgets/seeds/onion_models.dart';

const String kOnGen = 'on_gen';
const String kOn01 = 'on_01';
const String kOn02 = 'on_02';
const String kOn03 = 'on_03';
const String kOn04 = 'on_04';
const String kOn05 = 'on_05';

/// Perfiles biologicos de cebolla basados en los TXT finales BIO-G.
///
/// ON-GEN es la entrada SKIP segura y migrable: no asume color,
/// fotoperiodo fino, almacenamiento, proceso ni cambray, y permite
/// afinar a ON-01..ON-05 sin reiniciar la memoria del cultivo.
///
/// Regla: cultivo madre -> tipo UX/perfil -> variedad como alias.
const Map<String, OnionProfile> onionProfiles = {
  kOnGen: OnionProfile(
    id: kOnGen,
    label: 'ON-GEN - No sé / Otra cebolla',
    useType: 'Bulbo fresco generico - configuracion segura',
    marketType: OnionMarketType.generic,
    onionUseType: OnionUseType.flexible,
    defaultEstablishmentMode: OnionEstablishmentMode.unknown,
    photoperiodClass: OnionPhotoperiodClass.shortDay,
    e2EndDay: 18,
    e3EndDay: 28,
    e4EndDay: 60,
    e5EndDay: 85,
    e6EndDay: 100,
    e7EndDay: 125,
    e8EndDay: 140,
    cycleDays: RangeInt(110, 140),
    densityPlantsPerHa: RangeInt(250000, 750000),
    referenceYieldTHa: RangeDouble(20, 40),
    isGenericProfile: true,
    photoperiodSensitivity01: 0.80,
    boltingSensitivity01: 0.55,
    bulbQualitySensitivity01: 0.72,
    salinitySensitivity01: 0.80,
  ),
  kOn01: OnionProfile(
    id: kOn01,
    label: 'ON-01 - Cebolla blanca grano/bola',
    useType: 'Blanca dia corto, mercado nacional/fresco/bodega',
    marketType: OnionMarketType.whiteShortDay,
    onionUseType: OnionUseType.dryBulbFresh,
    defaultEstablishmentMode: OnionEstablishmentMode.directSeed,
    photoperiodClass: OnionPhotoperiodClass.shortDay,
    e2EndDay: 18,
    e3EndDay: 30,
    e4EndDay: 58,
    e5EndDay: 80,
    e6EndDay: 95,
    e7EndDay: 120,
    e8EndDay: 135,
    cycleDays: RangeInt(110, 140),
    densityPlantsPerHa: RangeInt(350000, 850000),
    referenceYieldTHa: RangeDouble(30, 58),
    photoperiodSensitivity01: 0.88,
    boltingSensitivity01: 0.55,
    bulbQualitySensitivity01: 0.82,
    salinitySensitivity01: 0.82,
  ),
  kOn02: OnionProfile(
    id: kOn02,
    label: 'ON-02 - Cebolla amarilla/dorada',
    useType: 'Amarilla dia corto, fresco/alto volumen/dulce segun material',
    marketType: OnionMarketType.yellowShortDay,
    onionUseType: OnionUseType.dryBulbFresh,
    defaultEstablishmentMode: OnionEstablishmentMode.directSeed,
    photoperiodClass: OnionPhotoperiodClass.shortDay,
    e2EndDay: 16,
    e3EndDay: 28,
    e4EndDay: 52,
    e5EndDay: 75,
    e6EndDay: 90,
    e7EndDay: 112,
    e8EndDay: 126,
    cycleDays: RangeInt(100, 130),
    densityPlantsPerHa: RangeInt(300000, 800000),
    referenceYieldTHa: RangeDouble(25, 52),
    photoperiodSensitivity01: 0.86,
    boltingSensitivity01: 0.52,
    bulbQualitySensitivity01: 0.78,
    salinitySensitivity01: 0.80,
  ),
  kOn03: OnionProfile(
    id: kOn03,
    label: 'ON-03 - Cebolla morada',
    useType: 'Morada dia corto, fresco/color/mercado regional',
    marketType: OnionMarketType.redShortDay,
    onionUseType: OnionUseType.dryBulbFresh,
    defaultEstablishmentMode: OnionEstablishmentMode.directSeed,
    photoperiodClass: OnionPhotoperiodClass.shortDay,
    e2EndDay: 18,
    e3EndDay: 30,
    e4EndDay: 60,
    e5EndDay: 85,
    e6EndDay: 102,
    e7EndDay: 126,
    e8EndDay: 142,
    cycleDays: RangeInt(115, 145),
    densityPlantsPerHa: RangeInt(300000, 800000),
    referenceYieldTHa: RangeDouble(24, 48),
    photoperiodSensitivity01: 0.86,
    boltingSensitivity01: 0.55,
    bulbQualitySensitivity01: 0.90,
    salinitySensitivity01: 0.82,
  ),
  kOn04: OnionProfile(
    id: kOn04,
    label: 'ON-04 - Cebolla de transicion / dia intermedio',
    useType: 'Dia intermedio, altiplano/templado, calibres grandes/bodega',
    marketType: OnionMarketType.intermediateTransition,
    onionUseType: OnionUseType.storageBulb,
    defaultEstablishmentMode: OnionEstablishmentMode.directSeed,
    photoperiodClass: OnionPhotoperiodClass.intermediateDay,
    e2EndDay: 20,
    e3EndDay: 34,
    e4EndDay: 72,
    e5EndDay: 100,
    e6EndDay: 120,
    e7EndDay: 148,
    e8EndDay: 162,
    cycleDays: RangeInt(140, 165),
    densityPlantsPerHa: RangeInt(350000, 950000),
    referenceYieldTHa: RangeDouble(32, 62),
    isStorageCapable: true,
    photoperiodSensitivity01: 0.92,
    boltingSensitivity01: 0.68,
    bulbQualitySensitivity01: 0.85,
    salinitySensitivity01: 0.80,
  ),
  kOn05: OnionProfile(
    id: kOn05,
    label: 'ON-05 - Cebolla en rama / cambray / manojo',
    useType: 'Precoz, cosecha joven, hoja + base/bulbo incipiente',
    marketType: OnionMarketType.bunchingCambray,
    onionUseType: OnionUseType.bunching,
    defaultEstablishmentMode: OnionEstablishmentMode.directSeed,
    photoperiodClass: OnionPhotoperiodClass.shortDay,
    e2EndDay: 14,
    e3EndDay: 24,
    e4EndDay: 45,
    e5EndDay: 60,
    e6EndDay: 72,
    e7EndDay: 82,
    e8EndDay: 90,
    cycleDays: RangeInt(60, 90),
    densityPlantsPerHa: RangeInt(800000, 2500000),
    referenceYieldTHa: RangeDouble(12, 25),
    isBunching: true,
    photoperiodSensitivity01: 0.30,
    boltingSensitivity01: 0.45,
    bulbQualitySensitivity01: 0.60,
    salinitySensitivity01: 0.78,
  ),
};

const Map<String, String> _onionProfileAliasToCanonical = {
  // ON-GEN
  'on-gen': kOnGen,
  'ongen': kOnGen,
  'on_gen': kOnGen,
  'cebolla': kOnGen,
  'cebolla generica': kOnGen,
  'cebolla generico': kOnGen,
  'onion': kOnGen,
  'generic onion': kOnGen,
  'onion generic': kOnGen,
  'onion_generic': kOnGen,
  'otra cebolla': kOnGen,
  'otra variedad': kOnGen,
  'no se': kOnGen,
  'no se todavia': kOnGen,
  'no sé': kOnGen,
  'no sé todavía': kOnGen,
  'skip': kOnGen,

  // ON-01 blanca dia corto grano/bola
  'on-01': kOn01,
  'on01': kOn01,
  'on_01': kOn01,
  'onion_white': kOn01,
  'blanca': kOn01,
  'cebolla blanca': kOn01,
  'blanca grano': kOn01,
  'blanca bola': kOn01,
  'grano/bola': kOn01,
  'white onion': kOn01,
  'white short day': kOn01,
  'sv4043nm': kOn01,
  'sv7030ns': kOn01,
  'ajusco': kOn01,
  'stratus': kOn01,
  'ex 6800': kOn01,
  'ex6800': kOn01,
  'stratus / ex 6800': kOn01,
  'la joya': kOn01,
  'xon570w': kOn01,
  'bella luna': kOn01,
  'carta blanca': kOn01,
  'otra blanca dia corto': kOn01,
  'otra blanca día corto': kOn01,

  // ON-02 amarilla/dorada dia corto
  'on-02': kOn02,
  'on02': kOn02,
  'on_02': kOn02,
  'onion_yellow': kOn02,
  'amarilla': kOn02,
  'dorada': kOn02,
  'cebolla amarilla': kOn02,
  'cebolla dorada': kOn02,
  'yellow onion': kOn02,
  'yellow short day': kOn02,
  'pecos': kOn02,
  'nomad': kOn02,
  'sv2623nn': kOn02,
  'nomad / sv2623nn': kOn02,
  'plethora': kOn02,
  'texas grano': kOn02,
  'granex': kOn02,
  'texas grano / granex': kOn02,
  'otra amarilla dia corto': kOn02,
  'otra amarilla día corto': kOn02,

  // ON-03 morada dia corto
  'on-03': kOn03,
  'on03': kOn03,
  'on_03': kOn03,
  'onion_purple': kOn03,
  'onion_red': kOn03,
  'morada': kOn03,
  'cebolla morada': kOn03,
  'roja': kOn03,
  'cebolla roja': kOn03,
  'red onion': kOn03,
  'purple onion': kOn03,
  'rasta': kOn03,
  'numex crimson': kOn03,
  'roja regional': kOn03,
  'rojas regionales': kOn03,
  'otra morada dia corto': kOn03,
  'otra morada día corto': kOn03,

  // ON-04 transicion / dia intermedio
  'on-04': kOn04,
  'on04': kOn04,
  'on_04': kOn04,
  'onion_transition': kOn04,
  'onion_intermediate': kOn04,
  'transicion': kOn04,
  'dia intermedio': kOn04,
  'intermedia': kOn04,
  'altiplano': kOn04,
  'intermediate day': kOn04,
  'transition onion': kOn04,
  'cimarron': kOn04,
  'cimarrón': kOn04,
  'nun 6005': kOn04,
  'super luna': kOn04,
  'súper luna': kOn04,
  'numex allure': kOn04,
  'otra dia intermedio': kOn04,
  'otra día intermedio': kOn04,

  // ON-05 cambray / rama / manojo
  'on-05': kOn05,
  'on05': kOn05,
  'on_05': kOn05,
  'onion_cambray': kOn05,
  'cambray': kOn05,
  'cebolla cambray': kOn05,
  'rama': kOn05,
  'cebolla de rama': kOn05,
  'cebollin': kOn05,
  'cebollín': kOn05,
  'manojo': kOn05,
  'green onion': kOn05,
  'bunching onion': kOn05,
  'scallion': kOn05,
  'sv4522nb': kOn05,
  'baja verde': kOn05,
  'otra cambray': kOn05,
  'otra rama': kOn05,
  'otra cambray / rama': kOn05,
};

String? resolveCanonicalOnionProfileId(String raw) {
  final normalized = raw.trim().toLowerCase();
  if (normalized.isEmpty) return null;
  if (onionProfiles.containsKey(normalized)) return normalized;
  return _onionProfileAliasToCanonical[normalized];
}
