import 'package:bio_g/widgets/seeds/maize_models.dart';
import 'package:bio_g/widgets/seeds/spinach_models.dart';

const String kSpGen = 'sp_gen';
const String kSp01 = 'sp_01';
const String kSp02 = 'sp_02';
const String kSp03 = 'sp_03';
const String kSp04 = 'sp_04';
const String kSp05 = 'sp_05';

/// Perfiles biologicos de espinaca basados en los TXT finales BIO-G.
///
/// SP-GEN es la entrada SKIP segura y migrable: no asume baby leaf,
/// saboya ni industria, y permite afinar a SP-01..SP-05 sin reiniciar
/// memoria del cultivo.
const Map<String, SpinachProfile> spinachProfiles = {
  kSpGen: SpinachProfile(
    id: kSpGen,
    label: 'SP-GEN - Espinaca generica / no se todavia',
    useType: 'Hoja comercial generica - configuracion segura',
    marketType: SpinachMarketType.generic,
    spinachUseType: SpinachUseType.flexible,
    defaultEstablishmentMode: SpinachEstablishmentMode.unknown,
    e2EndDay: 18,
    e3EndDay: 28,
    e4EndDay: 38,
    e5EndDay: 50,
    e6EndDay: 60,
    e7EndDay: 74,
    cycleDays: RangeInt(35, 60),
    densityPlantsPerHa: RangeInt(200000, 700000),
    referenceYieldTHa: RangeDouble(8, 16),
    isGenericProfile: true,
    leafQualitySensitivity01: 0.75,
    boltingSensitivity01: 0.72,
    regrowthPotential01: 0.35,
  ),
  kSp01: SpinachProfile(
    id: kSp01,
    label: 'SP-01 - Saboya / semi-saboya verano-calor',
    useType: 'Hoja fresca rizada, tolerancia relativa a calor',
    marketType: SpinachMarketType.savoySummer,
    spinachUseType: SpinachUseType.freshLeaf,
    e2EndDay: 18,
    e3EndDay: 30,
    e4EndDay: 42,
    e5EndDay: 58,
    e6EndDay: 66,
    e7EndDay: 82,
    cycleDays: RangeInt(40, 65),
    densityPlantsPerHa: RangeInt(250000, 800000),
    referenceYieldTHa: RangeDouble(10, 22),
    leafQualitySensitivity01: 0.78,
    boltingSensitivity01: 0.66,
    regrowthPotential01: 0.35,
  ),
  kSp02: SpinachProfile(
    id: kSp02,
    label: 'SP-02 - Saboya / semi-saboya invierno-dias cortos',
    useType: 'Hoja fresca de clima fresco, ciclo de invierno',
    marketType: SpinachMarketType.savoyWinter,
    spinachUseType: SpinachUseType.freshLeaf,
    e2EndDay: 18,
    e3EndDay: 30,
    e4EndDay: 42,
    e5EndDay: 60,
    e6EndDay: 70,
    e7EndDay: 88,
    cycleDays: RangeInt(35, 60),
    densityPlantsPerHa: RangeInt(250000, 850000),
    referenceYieldTHa: RangeDouble(14, 30),
    leafQualitySensitivity01: 0.74,
    boltingSensitivity01: 0.60,
    regrowthPotential01: 0.40,
  ),
  kSp03: SpinachProfile(
    id: kSp03,
    label: 'SP-03 - Lisa / baby leaf / premium',
    useType: 'Hoja lisa tierna, baby leaf o mercado premium',
    marketType: SpinachMarketType.smoothBaby,
    spinachUseType: SpinachUseType.babyLeaf,
    e2EndDay: 14,
    e3EndDay: 22,
    e4EndDay: 30,
    e5EndDay: 40,
    e6EndDay: 50,
    e7EndDay: 64,
    cycleDays: RangeInt(25, 45),
    densityPlantsPerHa: RangeInt(1500000, 9500000),
    referenceYieldTHa: RangeDouble(5, 12),
    isBabyLeaf: true,
    leafQualitySensitivity01: 1.00,
    boltingSensitivity01: 0.82,
    regrowthPotential01: 0.45,
  ),
  kSp04: SpinachProfile(
    id: kSp04,
    label: 'SP-04 - Oriental / manojo erecta',
    useType: 'Hoja erecta para manojo, corte fresco',
    marketType: SpinachMarketType.orientalBunching,
    spinachUseType: SpinachUseType.bunching,
    e2EndDay: 16,
    e3EndDay: 26,
    e4EndDay: 36,
    e5EndDay: 50,
    e6EndDay: 58,
    e7EndDay: 72,
    cycleDays: RangeInt(30, 50),
    densityPlantsPerHa: RangeInt(250000, 700000),
    referenceYieldTHa: RangeDouble(12, 25),
    isBunching: true,
    leafQualitySensitivity01: 0.82,
    boltingSensitivity01: 0.76,
    regrowthPotential01: 0.35,
  ),
  kSp05: SpinachProfile(
    id: kSp05,
    label: 'SP-05 - Proceso / industria',
    useType: 'Hoja para proceso, biomasa comercial uniforme',
    marketType: SpinachMarketType.processing,
    spinachUseType: SpinachUseType.processing,
    e2EndDay: 20,
    e3EndDay: 34,
    e4EndDay: 48,
    e5EndDay: 68,
    e6EndDay: 78,
    e7EndDay: 96,
    cycleDays: RangeInt(40, 70),
    densityPlantsPerHa: RangeInt(500000, 1500000),
    referenceYieldTHa: RangeDouble(16, 27),
    isProcessing: true,
    leafQualitySensitivity01: 0.68,
    boltingSensitivity01: 0.70,
    regrowthPotential01: 0.65,
  ),
};

const Map<String, String> _spinachProfileAliasToCanonical = {
  // SP-GEN
  'sp-gen': kSpGen,
  'spgen': kSpGen,
  'sp_gen': kSpGen,
  'espinaca': kSpGen,
  'espinaca generica': kSpGen,
  'espinaca generico': kSpGen,
  'spinach': kSpGen,
  'generic spinach': kSpGen,
  'spinach generic': kSpGen,
  'spinach_generic': kSpGen,
  'otra espinaca': kSpGen,
  'otra variedad': kSpGen,
  'no se': kSpGen,
  'no se todavia': kSpGen,
  'skip': kSpGen,

  // SP-01
  'sp-01': kSp01,
  'sp01': kSp01,
  'sp_01': kSp01,
  'spinach_savoy_summer': kSp01,
  'saboya verano': kSp01,
  'semi saboya verano': kSp01,
  'semi-saboya verano': kSp01,
  'verano calor': kSp01,
  'calor': kSp01,
  'savoy summer': kSp01,
  'summer savoy': kSp01,
  'semi savoy summer': kSp01,
  'savoy heat': kSp01,

  // SP-02
  'sp-02': kSp02,
  'sp02': kSp02,
  'sp_02': kSp02,
  'spinach_savoy_winter': kSp02,
  'saboya invierno': kSp02,
  'semi saboya invierno': kSp02,
  'semi-saboya invierno': kSp02,
  'invierno': kSp02,
  'dias cortos': kSp02,
  'savoy winter': kSp02,
  'winter savoy': kSp02,
  'short day spinach': kSp02,

  // SP-03
  'sp-03': kSp03,
  'sp03': kSp03,
  'sp_03': kSp03,
  'spinach_smooth_baby': kSp03,
  'lisa': kSp03,
  'espinaca lisa': kSp03,
  'baby leaf': kSp03,
  'babyleaf': kSp03,
  'baby spinach': kSp03,
  'premium': kSp03,
  'smooth': kSp03,
  'smooth baby': kSp03,

  // SP-04
  'sp-04': kSp04,
  'sp04': kSp04,
  'sp_04': kSp04,
  'spinach_oriental_bunching': kSp04,
  'oriental': kSp04,
  'espinaca oriental': kSp04,
  'manojo': kSp04,
  'bunching': kSp04,
  'oriental bunch': kSp04,
  'erecta': kSp04,

  // SP-05
  'sp-05': kSp05,
  'sp05': kSp05,
  'sp_05': kSp05,
  'spinach_processing': kSp05,
  'proceso': kSp05,
  'industria': kSp05,
  'industrial': kSp05,
  'processing': kSp05,
  'process spinach': kSp05,
  'spinach processing': kSp05,
};

String? resolveCanonicalSpinachProfileId(String raw) {
  final normalized = raw.trim().toLowerCase();
  if (normalized.isEmpty) return null;
  if (spinachProfiles.containsKey(normalized)) return normalized;
  return _spinachProfileAliasToCanonical[normalized];
}
