import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/squash_profiles.dart';

const String kCropSquash = 'squash';
const String kSquashDefaultCalendarId = 'squash_default';

/// Perfiles UX visibles en el wizard de configuración de semilla.
///
/// El usuario nunca debe ver "SKIP": CA-GEN se etiqueta como
/// "Calabaza genérica" y queda como entrada por defecto si no sabe.
const List<CropProfileEntry> squashProfileEntries = [
  CropProfileEntry(
    id: kCaGen,
    label: 'CA-GEN - Calabaza genérica',
    cropId: kCropSquash,
    subtitle:
        'Perfil conservador y migrable: puedes afinar el tipo después sin perder historial',
    aliases: [
      'CA-GEN',
      'CAGEN',
      'CA_GEN',
      'Calabaza',
      'Calabaza generica',
      'Calabaza genérica',
      'Otra calabaza',
      'No se',
      'No sé',
      'Squash',
      'Pumpkin',
      'Zapallo',
      'Ayote',
      'Auyama',
    ],
  ),
  CropProfileEntry(
    id: kCa01,
    label: 'CA-01 - Calabacita italiana / zucchini',
    cropId: kCropSquash,
    subtitle: 'Fruto tierno de corte continuo (calabacita)',
    aliases: [
      'CA-01',
      'CA01',
      'Calabacita',
      'Calabacita italiana',
      'Italiana',
      'Zucchini',
      'Zuccini',
      'Calabacin',
      'Calabacín',
      'Italiana larga',
      'Grey zucchini',
      'Squash italiano',
    ],
  ),
  CropProfileEntry(
    id: kCa02,
    label: 'CA-02 - Calabacita criolla / huicha / milpa',
    cropId: kCropSquash,
    subtitle: 'Fruto tierno - sistema mixto / temporal',
    aliases: [
      'CA-02',
      'CA02',
      'Criolla',
      'Calabacita criolla',
      'Calabaza criolla',
      'Huicha',
      'Güicha',
      'Guicha',
      'Milpa',
      'Calabaza de milpa',
      'Calabaza de temporal',
      'Temporal',
    ],
  ),
  CropProfileEntry(
    id: kCa03,
    label: 'CA-03 - Calabacita de bola / redonda',
    cropId: kCropSquash,
    subtitle: 'Fruto tierno - calibre y forma esférica',
    aliases: [
      'CA-03',
      'CA03',
      'Bola',
      'Redonda',
      'Calabacita de bola',
      'Calabacita redonda',
      'Round zucchini',
      'Eight ball',
    ],
  ),
  CropProfileEntry(
    id: kCa04,
    label: 'CA-04 - Calabaza de Castilla',
    cropId: kCropSquash,
    subtitle: 'Fruto maduro - dulce, altar y almacenamiento',
    aliases: [
      'CA-04',
      'CA04',
      'Castilla',
      'Calabaza de Castilla',
      'Calabaza para dulce',
      'Calabaza de altar',
      'Calabaza madura',
      'Pumpkin mexicano',
      'Winter squash',
    ],
  ),
  CropProfileEntry(
    id: kCa05,
    label: 'CA-05 - Butternut / buchona / mantequilla',
    cropId: kCropSquash,
    subtitle: 'Fruto maduro - mercado fresco y postcosecha',
    aliases: [
      'CA-05',
      'CA05',
      'Butternut',
      'Buchona',
      'Mantequilla',
      'Cacahuate',
      'Violin',
      'Violín',
      'Squash mantequilla',
    ],
  ),
  CropProfileEntry(
    id: kCa06,
    label: 'CA-06 - Chilacayote',
    cropId: kCropSquash,
    subtitle: 'Ciclo muy largo / fruto maduro tradicional',
    aliases: [
      'CA-06',
      'CA06',
      'Chilacayote',
      'Chilacayota',
      'Alcayota',
    ],
  ),
  CropProfileEntry(
    id: kCa07,
    label: 'CA-07 - Pipián / pipiana / pepita',
    cropId: kCropSquash,
    subtitle: 'Destino semilla seca (pepita); mide en t/ha de semilla',
    aliases: [
      'CA-07',
      'CA07',
      'Pipian',
      'Pipián',
      'Pipiana',
      'Pepita',
      'Calabaza pipiana',
      'Calabaza para semilla',
      'Chihua',
      'Cushaw',
      'Arota',
    ],
  ),
];

/// Variedades visibles en el wizard. Cada variedad apunta a un perfil
/// canónico CA-XX como `defaultProfileId` y arrastra alias amplios para
/// que la búsqueda en el wizard reconozca nombres regionales.
const List<CropVarietyEntry> squashVarieties = [
  CropVarietyEntry(
    id: 'squash_generic',
    label: 'No sé / Otra calabaza',
    cropId: kCropSquash,
    subtitle: 'Perfil seguro y migrable: ajusta después sin reiniciar',
    defaultProfileId: kCaGen,
    aliases: [
      'Calabaza',
      'Calabaza generica',
      'Calabaza genérica',
      'Otra calabaza',
      'No se',
      'No sé',
      'Pumpkin',
      'Squash',
      'Zapallo',
      'Ayote',
      'Auyama',
      'CA-GEN',
      'CAGEN',
    ],
    isGeneric: true,
  ),
  CropVarietyEntry(
    id: 'squash_zucchini',
    label: 'Calabacita italiana / zucchini',
    cropId: kCropSquash,
    subtitle: 'Tipo - fruto tierno de corte continuo',
    defaultProfileId: kCa01,
    aliases: [
      'Calabacita italiana',
      'Italiana',
      'Zucchini',
      'Zuccini',
      'Calabacin',
      'Calabacín',
      'Grey zucchini',
      'Italiana larga',
      'Squash italiano',
      'CA-01',
      'CA01',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_criolla',
    label: 'Calabacita criolla / huicha / milpa',
    cropId: kCropSquash,
    subtitle: 'Tipo - sistema mixto, temporal, milpa',
    defaultProfileId: kCa02,
    aliases: [
      'Criolla',
      'Calabacita criolla',
      'Calabaza criolla',
      'Huicha',
      'Güicha',
      'Guicha',
      'Milpa',
      'Calabaza de milpa',
      'Calabaza de temporal',
      'CA-02',
      'CA02',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_round',
    label: 'Calabacita de bola / redonda',
    cropId: kCropSquash,
    subtitle: 'Tipo - fruto tierno esférico',
    defaultProfileId: kCa03,
    aliases: [
      'Bola',
      'Redonda',
      'Calabacita de bola',
      'Calabacita redonda',
      'Round zucchini',
      'Eight ball',
      'CA-03',
      'CA03',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_castilla',
    label: 'Calabaza de Castilla',
    cropId: kCropSquash,
    subtitle: 'Tipo - fruto maduro de altar y dulce',
    defaultProfileId: kCa04,
    aliases: [
      'Castilla',
      'Calabaza de Castilla',
      'Calabaza para dulce',
      'Calabaza de altar',
      'Calabaza madura',
      'Pumpkin mexicano',
      'Winter squash',
      'CA-04',
      'CA04',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_butternut',
    label: 'Butternut / buchona / mantequilla',
    cropId: kCropSquash,
    subtitle: 'Tipo - fruto maduro mantequilla y postcosecha',
    defaultProfileId: kCa05,
    aliases: [
      'Butternut',
      'Buchona',
      'Mantequilla',
      'Cacahuate',
      'Violin',
      'Violín',
      'Squash mantequilla',
      'CA-05',
      'CA05',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_chilacayote',
    label: 'Chilacayote',
    cropId: kCropSquash,
    subtitle: 'Tipo - ciclo muy largo, fruto maduro',
    defaultProfileId: kCa06,
    aliases: [
      'Chilacayote',
      'Chilacayota',
      'Alcayota',
      'CA-06',
      'CA06',
    ],
  ),
  CropVarietyEntry(
    id: 'squash_pipian',
    label: 'Pipián / pipiana / pepita',
    cropId: kCropSquash,
    subtitle: 'Tipo - destino semilla seca (pepita)',
    defaultProfileId: kCa07,
    aliases: [
      'Pipian',
      'Pipián',
      'Pipiana',
      'Pepita',
      'Calabaza pipiana',
      'Calabaza para semilla',
      'Chihua',
      'Cushaw',
      'Arota',
      'CA-07',
      'CA07',
    ],
  ),
];
