import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/spinach_models.dart';

/// Perfil Universal BIO-G de espinaca (`crop_spinach`).
///
/// La logica activa v1 es NPK como riesgo/desequilibrio, no receta. Agua,
/// temperatura, salinidad y calidad de hoja pesan fuerte; Ca/Mg/S quedan
/// como contexto y no activan motor principal.
class SpinachUniversalProfile {
  const SpinachUniversalProfile({
    required this.byStage,
    required this.weights,
  });

  final Map<SpinachStageKey, StageTargets> byStage;
  final Map<SpinachStageKey, StageWeights> weights;
}

const AgroRange _phStd = AgroRange(
  lowMax: 5.7,
  optimalMin: 6.0,
  optimalMax: 7.5,
  highMin: 7.8,
);

const AgroRange _ecQuality = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 2.0,
  highMin: 3.5,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 2.3,
  highMin: 4.0,
);

const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _soilTempGerm = AgroRange(
  lowMax: 5,
  optimalMin: 7,
  optimalMax: 24,
  highMin: 27,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 5,
  optimalMin: 10,
  optimalMax: 24,
  highMin: 30,
);

const AgroRange _moistureActive = AgroRange(
  lowMax: 55,
  optimalMin: 65,
  optimalMax: 90,
  highMin: 95,
);

const AgroRange _moistureLate = AgroRange(
  lowMax: 50,
  optimalMin: 60,
  optimalMax: 88,
  highMin: 95,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.78,
}) {
  AgroRange idx(double p) => AgroRange(
        lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
        optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
        optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
        highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
      );

  AgroRange ppm(double low, double min, double max) => AgroRange(
        lowMax: low,
        optimalMin: min,
        optimalMax: max,
        highMin: max + (max - min) * 0.55,
      );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: 0.20,
    mgPriority: 0.18,
    sPriority: 0.16,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs: 'Ca informativo en v1; tip burn se maneja con agua y ambiente.',
    mgShortGuidanceEs: 'Mg en mantenimiento; no es motor principal v1.',
    sShortGuidanceEs: 'S en soporte; no generar receta activa.',
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final SpinachUniversalProfile spinachUniversalV1 = SpinachUniversalProfile(
  byStage: <SpinachStageKey, StageTargets>{
    SpinachStageKey.germinacion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempGerm,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 10,
      nOptMin: 14,
      nOptMax: 24,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 54,
      kLow: 42,
      kOptMin: 55,
      kOptMax: 85,
      nPriority: 0.12,
      pPriority: 0.45,
      kPriority: 0.20,
      nWindow: 'Arranque sin presion de N',
      pWindow: 'Raiz inicial',
      kWindow: 'Reserva baja',
      nGuide: 'No empujar N en germinacion; humedad, temperatura y baja salinidad mandan.',
      pGuide: 'P temprano apoya raiz, pero sin cargar sales.',
      kGuide: 'K solo de base; evitar CE alta en nacencia.',
      pHint: 'Si el suelo viene frio, P de arranque pesa mas que N.',
      confidence: 0.68,
    ),
    SpinachStageKey.establecimiento: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 22,
      nOptMin: 30,
      nOptMax: 48,
      pLow: 40,
      pOptMin: 50,
      pOptMax: 72,
      kLow: 70,
      kOptMin: 85,
      kOptMax: 120,
      nPriority: 0.38,
      pPriority: 0.78,
      kPriority: 0.42,
      nWindow: 'N suave de establecimiento',
      pWindow: 'Pegue y raiz',
      kWindow: 'Balance temprano',
      nGuide: 'N bajo a moderado; evitar hoja blanda y chupadera en planta joven.',
      pGuide: 'P es el nutriente mas sensible en raiz temprana.',
      kGuide: 'K acompana turgencia inicial sin subir CE.',
      nHint: 'Si el riego es irregular, estabilizar agua antes de subir N.',
      pHint: 'Corregir P temprano si la lectura queda corta.',
      confidence: 0.80,
    ),
    SpinachStageKey.vegetativoTemprano: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 38,
      nOptMin: 50,
      nOptMax: 78,
      pLow: 30,
      pOptMin: 38,
      pOptMax: 58,
      kLow: 82,
      kOptMin: 100,
      kOptMax: 140,
      nPriority: 0.68,
      pPriority: 0.48,
      kPriority: 0.55,
      nWindow: 'Crecimiento foliar controlado',
      pWindow: 'Soporte de raiz',
      kWindow: 'Reserva de turgencia',
      nGuide: 'N suficiente para hoja, sin exceder por riesgo de hoja blanda y nitratos.',
      pGuide: 'P pasa a soporte; el cuello principal ya fue establecimiento.',
      kGuide: 'K prepara turgencia para expansion foliar.',
      nHint: 'El exceso de N puede parecer vigor, pero reduce calidad de anaquel.',
      confidence: 0.82,
    ),
    SpinachStageKey.expansionFoliar: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 55,
      nOptMin: 68,
      nOptMax: 96,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 56,
      kLow: 105,
      kOptMin: 125,
      kOptMax: 170,
      nPriority: 0.86,
      pPriority: 0.44,
      kPriority: 0.74,
      nWindow: 'Mayor demanda de hoja',
      pWindow: 'P de soporte',
      kWindow: 'K para turgencia',
      nGuide: 'Etapa de mayor N, pero BIO-G lo lee como riesgo: suficiente, no exceso.',
      pGuide: 'P de mantenimiento; no desplaza agua ni temperatura.',
      kGuide: 'K sostiene turgencia y calidad de hoja.',
      nHint: 'En baby leaf o CE alta, no subir N fuerte.',
      kHint: 'K solo funciona con humedad pareja y salinidad controlada.',
      confidence: 0.86,
    ),
    SpinachStageKey.madurezComercial: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 38,
      nOptMin: 48,
      nOptMax: 74,
      pLow: 24,
      pOptMin: 30,
      pOptMax: 48,
      kLow: 118,
      kOptMin: 140,
      kOptMax: 185,
      nPriority: 0.52,
      pPriority: 0.30,
      kPriority: 0.82,
      nWindow: 'N moderado cerca de corte',
      pWindow: 'P de mantenimiento',
      kWindow: 'Turgencia y calidad visual',
      nGuide: 'No empujar N cerca de cosecha; sube riesgo de nitratos y hoja blanda.',
      pGuide: 'P de soporte, rara vez decide la calidad final.',
      kGuide: 'K apoya turgencia, color y vida de anaquel.',
      nHint: 'Si hay calor o bolting, cosecha pesa mas que fertilizar.',
      kHint: 'Cuidar CE: K no debe convertirse en golpe salino.',
      confidence: 0.86,
    ),
    SpinachStageKey.ventanaCosecha: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecQuality,
      nLow: 24,
      nOptMin: 32,
      nOptMax: 54,
      pLow: 18,
      pOptMin: 24,
      pOptMax: 42,
      kLow: 95,
      kOptMin: 115,
      kOptMax: 160,
      nPriority: 0.34,
      pPriority: 0.22,
      kPriority: 0.68,
      nWindow: 'N a la baja',
      pWindow: 'P de cierre',
      kWindow: 'Calidad al corte',
      nGuide: 'Cerca del corte no conviene subir N fuerte; priorizar hoja limpia y turgente.',
      pGuide: 'P queda como lectura para trazabilidad.',
      kGuide: 'K sostiene turgencia si la humedad y CE estan en rango.',
      nHint: 'Cosechar oportuno si hay calor, manchas o inicio de espigado.',
      confidence: 0.82,
    ),
    SpinachStageKey.perdidaCalidad: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 16,
      nOptMin: 22,
      nOptMax: 38,
      pLow: 14,
      pOptMin: 20,
      pOptMax: 36,
      kLow: 65,
      kOptMin: 82,
      kOptMax: 125,
      nPriority: 0.18,
      pPriority: 0.16,
      kPriority: 0.34,
      nWindow: 'Cierre de N',
      pWindow: 'Cierre de P',
      kWindow: 'Cierre de K',
      nGuide: 'No corregir N tarde; documentar calidad y planear el siguiente ciclo.',
      pGuide: 'Usar la lectura para ajustar base futura.',
      kGuide: 'K solo conserva calidad residual; no empujar.',
      confidence: 0.64,
    ),
    SpinachStageKey.espigadoSenescencia: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 10,
      nOptMin: 16,
      nOptMax: 30,
      pLow: 12,
      pOptMin: 18,
      pOptMax: 32,
      kLow: 50,
      kOptMin: 65,
      kOptMax: 105,
      nPriority: 0.10,
      pPriority: 0.12,
      kPriority: 0.22,
      nWindow: 'Sin impulso nutricional',
      pWindow: 'Registro de cierre',
      kWindow: 'Registro de cierre',
      nGuide: 'Espigado es perdida de calidad; no fertilizar como si fuera etapa productiva.',
      pGuide: 'Registrar y usar para el siguiente ciclo.',
      kGuide: 'Cosechar/cerrar; K no revierte espigado.',
      nHint: 'Si aparece tallo floral, cosechar de inmediato o cerrar ciclo.',
      confidence: 0.58,
    ),
  },
  weights: const <SpinachStageKey, StageWeights>{
    SpinachStageKey.germinacion: StageWeights(
      moisture: 0.35,
      soilTemp: 0.25,
      resistance: 0.14,
      ph: 0.06,
      ec: 0.12,
      npk: 0.08,
    ),
    SpinachStageKey.establecimiento: StageWeights(
      moisture: 0.30,
      soilTemp: 0.18,
      resistance: 0.20,
      ph: 0.07,
      ec: 0.10,
      npk: 0.15,
    ),
    SpinachStageKey.vegetativoTemprano: StageWeights(
      moisture: 0.30,
      soilTemp: 0.18,
      resistance: 0.10,
      ph: 0.07,
      ec: 0.10,
      npk: 0.25,
    ),
    SpinachStageKey.expansionFoliar: StageWeights(
      moisture: 0.30,
      soilTemp: 0.22,
      resistance: 0.06,
      ph: 0.06,
      ec: 0.10,
      npk: 0.26,
    ),
    SpinachStageKey.madurezComercial: StageWeights(
      moisture: 0.35,
      soilTemp: 0.24,
      resistance: 0.04,
      ph: 0.05,
      ec: 0.12,
      npk: 0.20,
    ),
    SpinachStageKey.ventanaCosecha: StageWeights(
      moisture: 0.30,
      soilTemp: 0.23,
      resistance: 0.05,
      ph: 0.05,
      ec: 0.12,
      npk: 0.25,
    ),
    SpinachStageKey.perdidaCalidad: StageWeights(
      moisture: 0.24,
      soilTemp: 0.30,
      resistance: 0.06,
      ph: 0.06,
      ec: 0.12,
      npk: 0.22,
    ),
    SpinachStageKey.espigadoSenescencia: StageWeights(
      moisture: 0.20,
      soilTemp: 0.38,
      resistance: 0.05,
      ph: 0.05,
      ec: 0.12,
      npk: 0.20,
    ),
  },
);
