import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/onion_models.dart';

/// Perfil Universal BIO-G de cebolla (`crop_onion`).
///
/// La logica activa v1 es NPK como riesgo/desequilibrio, no receta. Agua,
/// temperatura, salinidad, fotoperiodo y calidad de bulbo pesan fuerte;
/// Ca/Mg/S/micros quedan como observacion tecnica y no activan el motor
/// principal. El organo objetivo es el bulbo: N temprano con control, P
/// para arranque/raiz, K para llenado/calidad y cierre limpio de cuello.
class OnionUniversalProfile {
  const OnionUniversalProfile({
    required this.byStage,
    required this.weights,
  });

  final Map<OnionStageKey, StageTargets> byStage;
  final Map<OnionStageKey, StageWeights> weights;
}

const AgroRange _phStd = AgroRange(
  lowMax: 5.7,
  optimalMin: 6.0,
  optimalMax: 7.5,
  highMin: 7.8,
);

// Cebolla es sensible a sales: observacion 1.2-1.8, alerta 1.8-2.8,
// critico 2.8-4.3 dS/m. EC mas estricto que hortalizas de hoja.
const AgroRange _ecStrict = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.6,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 1.8,
  highMin: 3.0,
);

const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _soilTempGerm = AgroRange(
  lowMax: 9,
  optimalMin: 15,
  optimalMax: 25,
  highMin: 32,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 8,
  optimalMin: 13,
  optimalMax: 26,
  highMin: 32,
);

// AW 60-85/90% sin saturacion; raiz superficial.
const AgroRange _moistureActive = AgroRange(
  lowMax: 50,
  optimalMin: 60,
  optimalMax: 90,
  highMin: 95,
);

// Maduracion/cosecha: bajar humedad excesiva para cuello/curado.
const AgroRange _moistureLate = AgroRange(
  lowMax: 45,
  optimalMin: 55,
  optimalMax: 80,
  highMin: 90,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.78,
}) {
  AgroRange idx(double p) => AgroRange(
        lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
        optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
        optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
        highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
      );

  AgroRange ppm(double low, double min, double max) => AgroRange(
        lowMax: low,
        optimalMin: min,
        optimalMax: max,
        highMin: max + (max - min) * 0.55,
      );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: 0.20,
    mgPriority: 0.18,
    sPriority: 0.22,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs:
        'Ca informativo en v1; revisa raiz, agua y pH antes de dosis ciega.',
    mgShortGuidanceEs: 'Mg en mantenimiento; confirmar con analisis si K alto.',
    sShortGuidanceEs:
        'Azufre importante en cebolla (Allium), pero v1 lo deja como observacion temprana; tarde o en exceso sube pungencia.',
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final OnionUniversalProfile onionUniversalV1 = OnionUniversalProfile(
  byStage: <OnionStageKey, StageTargets>{
    OnionStageKey.germinacion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempGerm,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 10,
      nOptMin: 14,
      nOptMax: 24,
      pLow: 30,
      pOptMin: 40,
      pOptMax: 58,
      kLow: 60,
      kOptMin: 80,
      kOptMax: 120,
      nPriority: 0.12,
      pPriority: 0.42,
      kPriority: 0.18,
      nWindow: 'Arranque sin presion de N',
      pWindow: 'Raiz inicial',
      kWindow: 'Reserva baja',
      nGuide:
          'No empujar N en germinacion; humedad fina, temperatura y baja salinidad mandan el stand.',
      pGuide: 'P de arranque apoya raiz, pero sin cargar sales sobre la semilla.',
      kGuide: 'K solo de base; evita CE alta en nacencia.',
      pHint: 'Si el suelo viene frio o alcalino, el P de arranque pesa mas que N.',
      confidence: 0.66,
    ),
    OnionStageKey.emergencia: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 18,
      nOptMin: 26,
      nOptMax: 42,
      pLow: 45,
      pOptMin: 56,
      pOptMax: 80,
      kLow: 80,
      kOptMin: 100,
      kOptMax: 140,
      nPriority: 0.40,
      pPriority: 0.74,
      kPriority: 0.42,
      nWindow: 'N suave de plantula',
      pWindow: 'Pegue y raiz joven',
      kWindow: 'Balance temprano',
      nGuide:
          'N bajo a moderado; la plantula de latigo no necesita empuje fuerte de N.',
      pGuide: 'P es el nutriente mas sensible en raiz superficial temprana.',
      kGuide: 'K acompana sin subir CE cerca de la raiz joven.',
      nHint: 'Si la emergencia es despareja, revisa costra/sales antes que N.',
      confidence: 0.74,
    ),
    OnionStageKey.establecimiento: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 24,
      nOptMin: 32,
      nOptMax: 50,
      pLow: 48,
      pOptMin: 60,
      pOptMax: 84,
      kLow: 95,
      kOptMin: 115,
      kOptMax: 155,
      nPriority: 0.42,
      pPriority: 0.80,
      kPriority: 0.48,
      nWindow: 'N de establecimiento',
      pWindow: 'Raiz funcional',
      kWindow: 'Balance de suelo',
      nGuide:
          'N bajo-medio; evita sobrefertilizar planta joven con raiz limitada.',
      pGuide: 'P alto relativo si suelo bajo, frio o alcalino; coloca cerca de raiz.',
      kGuide: 'K medio segun suelo, cuidando salinidad.',
      pHint: 'Cebolla depende de micorrizas para P en suelos calcareos.',
      confidence: 0.80,
    ),
    OnionStageKey.vegetativo: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 42,
      nOptMin: 56,
      nOptMax: 86,
      pLow: 32,
      pOptMin: 42,
      pOptMax: 62,
      kLow: 110,
      kOptMin: 135,
      kOptMax: 180,
      nPriority: 0.74,
      pPriority: 0.46,
      kPriority: 0.58,
      nWindow: 'Construir fabrica foliar',
      pWindow: 'Soporte de raiz',
      kWindow: 'Reserva para bulbo',
      nGuide:
          'N suficiente para hoja sana; el exceso tarde engruesa cuello y retrasa madurez.',
      pGuide: 'P pasa a soporte; el arranque ya se resolvio en establecimiento.',
      kGuide: 'K prepara turgencia y reservas para la bulbificacion.',
      nHint: 'La hoja es la fabrica del bulbo, pero mas hoja no siempre es mas bulbo.',
      confidence: 0.82,
    ),
    OnionStageKey.induccionBulbificacion: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 36,
      nOptMin: 48,
      nOptMax: 74,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 56,
      kLow: 130,
      kOptMin: 155,
      kOptMax: 205,
      nPriority: 0.52,
      pPriority: 0.36,
      kPriority: 0.66,
      nWindow: 'N a la baja, equilibrio',
      pWindow: 'P de soporte',
      kWindow: 'K sube para bulbo',
      nGuide:
          'Fotoperiodo manda: mas N no corrige un dia equivocado. Comienza a bajar intensidad de N.',
      pGuide: 'P rara vez es la palanca aqui salvo deficiencia comprobada.',
      kGuide: 'K medio-alto si suelo y CE lo permiten para preparar calibre.',
      nHint: 'Mucha hoja y poco bulbo: revisa fotoperiodo y exceso de N, no apliques mas.',
      kHint: 'K solo funciona con humedad estable y CE controlada.',
      confidence: 0.78,
    ),
    OnionStageKey.inicioBulbo: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 30,
      nOptMin: 40,
      nOptMax: 62,
      pLow: 24,
      pOptMin: 32,
      pOptMax: 50,
      kLow: 150,
      kOptMin: 180,
      kOptMax: 235,
      nPriority: 0.44,
      pPriority: 0.30,
      kPriority: 0.80,
      nWindow: 'N moderado, sin empuje',
      pWindow: 'P de mantenimiento',
      kWindow: 'Calibre y firmeza',
      nGuide:
          'Bulbo definiendose: no apliques N fuerte si ya hay buen follaje y el bulbo crece.',
      pGuide: 'P de mantenimiento segun laboratorio; no decide el calibre.',
      kGuide: 'K alto relativo sostiene agua, turgencia y calibre del bulbo.',
      kHint: 'Si la CE ya esta alta, no subas K hasta revisar salinidad.',
      confidence: 0.84,
    ),
    OnionStageKey.llenadoBulbo: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 24,
      nOptMin: 32,
      nOptMax: 52,
      pLow: 20,
      pOptMin: 28,
      pOptMax: 46,
      kLow: 165,
      kOptMin: 200,
      kOptMax: 255,
      nPriority: 0.34,
      pPriority: 0.26,
      kPriority: 0.90,
      nWindow: 'N a la baja',
      pWindow: 'P de cierre',
      kWindow: 'Llenado y calidad',
      nGuide:
          'No empujar N: evita 2/3 de tamano final con N tardio (cuello grueso, doble centro, mala conservacion).',
      pGuide: 'P bajo-medio segun analisis; no es la prioridad del llenado.',
      kGuide: 'K es el nutriente del bulbo: agua pareja + K sostienen calibre y firmeza.',
      nHint: 'Si el bulbo llego a ~2/3 de su tamano, bloquea N fuerte.',
      kHint: 'K no compensa salinidad ni falta de agua; revisa CE primero.',
      confidence: 0.86,
    ),
    OnionStageKey.maduracionCosecha: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 14,
      nOptMin: 20,
      nOptMax: 34,
      pLow: 16,
      pOptMin: 22,
      pOptMax: 38,
      kLow: 120,
      kOptMin: 150,
      kOptMax: 195,
      nPriority: 0.16,
      pPriority: 0.16,
      kPriority: 0.46,
      nWindow: 'Detener N',
      pWindow: 'Cierre de P',
      kWindow: 'Solo mantenimiento',
      nGuide:
          'Detener N: el cuello debe cerrar y madurar. N o riego tardio retrasan secado y suben pudriciones.',
      pGuide: 'P ya no decide; usa la lectura para el siguiente ciclo.',
      kGuide: 'K solo mantenimiento si hay deficiencia comprobada; no corregir tarde.',
      nHint: 'Bloquea N fuerte: maduracion, cuello y curado pesan mas que crecer.',
      confidence: 0.80,
    ),
    OnionStageKey.espigado: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 10,
      nOptMin: 16,
      nOptMax: 28,
      pLow: 12,
      pOptMin: 18,
      pOptMax: 32,
      kLow: 90,
      kOptMin: 115,
      kOptMax: 160,
      nPriority: 0.10,
      pPriority: 0.12,
      kPriority: 0.24,
      nWindow: 'Sin impulso nutricional',
      pWindow: 'Registro de cierre',
      kWindow: 'Registro de cierre',
      nGuide:
          'Espigado es perdida de calidad; no fertilizar como si fuera etapa productiva.',
      pGuide: 'Registrar y usar para ajustar el siguiente ciclo.',
      kGuide: 'El K no revierte el espigado; decide cosecha/cierre.',
      nHint: 'Si hay tallo floral, evalua cosecha/descarte y registra la causa.',
      confidence: 0.58,
    ),
  },
  weights: const <OnionStageKey, StageWeights>{
    OnionStageKey.germinacion: StageWeights(
      moisture: 0.35,
      soilTemp: 0.22,
      resistance: 0.14,
      ph: 0.05,
      ec: 0.12,
      npk: 0.12,
    ),
    OnionStageKey.emergencia: StageWeights(
      moisture: 0.30,
      soilTemp: 0.18,
      resistance: 0.18,
      ph: 0.05,
      ec: 0.14,
      npk: 0.15,
    ),
    OnionStageKey.establecimiento: StageWeights(
      moisture: 0.30,
      soilTemp: 0.18,
      resistance: 0.18,
      ph: 0.05,
      ec: 0.14,
      npk: 0.15,
    ),
    OnionStageKey.vegetativo: StageWeights(
      moisture: 0.26,
      soilTemp: 0.18,
      resistance: 0.12,
      ph: 0.05,
      ec: 0.13,
      npk: 0.26,
    ),
    OnionStageKey.induccionBulbificacion: StageWeights(
      moisture: 0.28,
      soilTemp: 0.20,
      resistance: 0.10,
      ph: 0.05,
      ec: 0.13,
      npk: 0.24,
    ),
    OnionStageKey.inicioBulbo: StageWeights(
      moisture: 0.32,
      soilTemp: 0.18,
      resistance: 0.10,
      ph: 0.05,
      ec: 0.13,
      npk: 0.22,
    ),
    OnionStageKey.llenadoBulbo: StageWeights(
      moisture: 0.34,
      soilTemp: 0.18,
      resistance: 0.12,
      ph: 0.04,
      ec: 0.14,
      npk: 0.18,
    ),
    OnionStageKey.maduracionCosecha: StageWeights(
      moisture: 0.26,
      soilTemp: 0.18,
      resistance: 0.08,
      ph: 0.05,
      ec: 0.15,
      npk: 0.20,
    ),
    OnionStageKey.espigado: StageWeights(
      moisture: 0.20,
      soilTemp: 0.30,
      resistance: 0.06,
      ph: 0.05,
      ec: 0.13,
      npk: 0.16,
    ),
  },
);
