import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/garlic_profiles.dart';

const String kCropGarlic = 'garlic';
const String kGarlicDefaultCalendarId = 'garlic_default';

const List<CropProfileEntry> garlicProfileEntries = [
  CropProfileEntry(
    id: kAgGen,
    label: 'AG-GEN - No se / Otro ajo',
    cropId: kCropGarlic,
    subtitle:
        'Perfil conservador y migrable: puedes cambiar el tipo despues sin perder historial',
    aliases: [
      'AG-GEN',
      'AGGEN',
      'AG_GEN',
      'Ajo',
      'Ajo generico',
      'Otro ajo',
      'Otra variedad',
      'No se',
      'Garlic',
    ],
  ),
  CropProfileEntry(
    id: kAg01,
    label: 'AG-01 - Ajo blanco / Perla',
    cropId: kCropGarlic,
    subtitle: 'Blanco o Perla; curado y calibre comercial',
    aliases: [
      'AG-01',
      'AG01',
      'Ajo blanco',
      'Perla',
      'Orion',
      'San Marqueno',
      'Diamante',
      'Blanco de Egipto',
    ],
  ),
  CropProfileEntry(
    id: kAg02,
    label: 'AG-02 - Ajo jaspeado / Calera / rayado',
    cropId: kCropGarlic,
    subtitle: 'Jaspeado, Calera o rayado; alto potencial si hay frio y sanidad',
    aliases: [
      'AG-02',
      'AG02',
      'Ajo jaspeado',
      'Calera',
      'Rayado',
      'CEZAC 06',
      'Jaspeado Calera',
      'Barretero',
      'Inifap 94',
      'Tacatzcuaro',
      'Tinguindin',
    ],
  ),
  CropProfileEntry(
    id: kAg03,
    label: 'AG-03 - Ajo morado',
    cropId: kCropGarlic,
    subtitle: 'Morado; color, frio y curado pesan fuerte',
    aliases: ['AG-03', 'AG03', 'Ajo morado', 'Morado'],
  ),
  CropProfileEntry(
    id: kAg04,
    label: 'AG-04 - Ajo criollo / regional',
    cropId: kCropGarlic,
    subtitle: 'Criollo o regional; cuidar diente-semilla y sanidad local',
    aliases: ['AG-04', 'AG04', 'Ajo criollo', 'Criollo Regional', 'Regional'],
  ),
  CropProfileEntry(
    id: kAg05,
    label: 'AG-05 - Ajo chino / coreano',
    cropId: kCropGarlic,
    subtitle: 'Chino o coreano; verificar trazabilidad y adaptacion',
    aliases: [
      'AG-05',
      'AG05',
      'Ajo chino',
      'Ajo coreano',
      'Chino Calera',
      'Chino CEDEL',
      'Coreano',
    ],
  ),
];

const List<CropVarietyEntry> garlicVarieties = [
  CropVarietyEntry(
    id: 'garlic_generic',
    label: 'No se / Otro ajo',
    cropId: kCropGarlic,
    subtitle: 'Perfil seguro y migrable: ajusta despues sin reiniciar',
    defaultProfileId: kAgGen,
    aliases: [
      'Ajo',
      'Ajo generico',
      'Otro ajo',
      'Otra variedad',
      'No se',
      'Garlic',
      'AG-GEN',
      'AGGEN',
    ],
    isGeneric: true,
  ),
  CropVarietyEntry(
    id: 'garlic_white_pearl',
    label: 'Blanco / Perla',
    cropId: kCropGarlic,
    subtitle: 'Tipo - blanco o perla, bulbo comercial curado',
    defaultProfileId: kAg01,
    aliases: [
      'Ajo blanco',
      'Perla',
      'Orion',
      'San Marqueno',
      'Diamante',
      'Blanco de Egipto',
      'garlic_orion',
      'garlic_san_marqueno',
      'AG-01',
      'AG01',
    ],
  ),
  CropVarietyEntry(
    id: 'garlic_jaspeado_calera',
    label: 'Jaspeado / Calera / rayado',
    cropId: kCropGarlic,
    subtitle: 'Tipo - jaspeado, Calera o rayado',
    defaultProfileId: kAg02,
    aliases: [
      'Ajo jaspeado',
      'Calera',
      'Rayado',
      'CEZAC 06',
      'Jaspeado Calera',
      'Barretero',
      'Inifap 94',
      'Tacatzcuaro',
      'Tinguindin',
      'garlic_cezac_06',
      'garlic_barretero',
      'AG-02',
      'AG02',
    ],
  ),
  CropVarietyEntry(
    id: 'garlic_purple',
    label: 'Morado',
    cropId: kCropGarlic,
    subtitle: 'Tipo - morado, color y mercado regional',
    defaultProfileId: kAg03,
    aliases: ['Ajo morado', 'Morado', 'AG-03', 'AG03'],
  ),
  CropVarietyEntry(
    id: 'garlic_criollo_regional',
    label: 'Criollo / Regional',
    cropId: kCropGarlic,
    subtitle: 'Tipo - criollo o regional',
    defaultProfileId: kAg04,
    aliases: ['Ajo criollo', 'Criollo Regional', 'Regional', 'AG-04', 'AG04'],
  ),
  CropVarietyEntry(
    id: 'garlic_chinese_korean',
    label: 'Chino / Coreano',
    cropId: kCropGarlic,
    subtitle: 'Tipo - chino, coreano o trazabilidad similar',
    defaultProfileId: kAg05,
    aliases: [
      'Ajo chino',
      'Ajo coreano',
      'Chino Calera',
      'Chino CEDEL',
      'Coreano',
      'AG-05',
      'AG05',
    ],
  ),
];
