import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/garlic_models.dart';

/// Perfil Universal BIO-G de ajo (`crop_garlic`).
///
/// La logica activa v1 es NPK como riesgo/desequilibrio, no receta. El ajo
/// depende de diente-semilla sano, frio/vernalizacion, agua estable, baja CE,
/// suelo suelto, maduracion y curado. S es importante en Allium, pero queda
/// como observacion tecnica/futuro Pro si el motor activo no lo soporta.
class GarlicUniversalProfile {
  const GarlicUniversalProfile({required this.byStage, required this.weights});

  final Map<GarlicStageKey, StageTargets> byStage;
  final Map<GarlicStageKey, StageWeights> weights;
}

const AgroRange _phStd = AgroRange(
  lowMax: 5.7,
  optimalMin: 6.0,
  optimalMax: 7.5,
  highMin: 7.8,
);

const AgroRange _ecStrict = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 2.0,
  highMin: 3.0,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.0,
  optimalMin: 0.0,
  optimalMax: 2.2,
  highMin: 3.2,
);

const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _soilTempStart = AgroRange(
  lowMax: 8,
  optimalMin: 10,
  optimalMax: 22,
  highMin: 28,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 8,
  optimalMin: 12,
  optimalMax: 25,
  highMin: 30,
);

const AgroRange _soilTempBulb = AgroRange(
  lowMax: 8,
  optimalMin: 12,
  optimalMax: 24,
  highMin: 29,
);

const AgroRange _moistureActive = AgroRange(
  lowMax: 50,
  optimalMin: 60,
  optimalMax: 85,
  highMin: 95,
);

const AgroRange _moistureLate = AgroRange(
  lowMax: 45,
  optimalMin: 55,
  optimalMax: 78,
  highMin: 90,
);

const AgroRange _moistureCuring = AgroRange(
  lowMax: 35,
  optimalMin: 45,
  optimalMax: 65,
  highMin: 82,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.76,
}) {
  AgroRange idx(double p) => AgroRange(
    lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
    optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
    optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
    highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
  );

  AgroRange ppm(double low, double min, double max) => AgroRange(
    lowMax: low,
    optimalMin: min,
    optimalMax: max,
    highMin: max + (max - min) * 0.55,
  );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: 0.18,
    mgPriority: 0.18,
    sPriority: 0.24,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs:
        'Ca informativo en v1; revisar raiz, agua, pH y curado antes de sobreactuar.',
    mgShortGuidanceEs: 'Mg en mantenimiento; confirmar con analisis si K alto.',
    sShortGuidanceEs:
        'Azufre es relevante en ajo (Allium), pero BIO-G v1 lo deja como observacion tecnica/futuro Pro; no es motor activo principal.',
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final GarlicUniversalProfile garlicUniversalV1 = GarlicUniversalProfile(
  byStage: <GarlicStageKey, StageTargets>{
    GarlicStageKey.clovePlanting: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStart,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 10,
      nOptMin: 14,
      nOptMax: 24,
      pLow: 30,
      pOptMin: 40,
      pOptMax: 58,
      kLow: 65,
      kOptMin: 85,
      kOptMax: 125,
      nPriority: 0.12,
      pPriority: 0.46,
      kPriority: 0.22,
      nWindow: 'Arranque sin empuje de N',
      pWindow: 'Raiz inicial del diente',
      kWindow: 'Reserva baja',
      nGuide:
          'No empujar N al plantar; diente sano, humedad fina, suelo suelto y baja CE mandan el stand.',
      pGuide:
          'P de arranque apoya raiz, pero debe venir de analisis y sin cargar sales al diente.',
      kGuide: 'K de base moderado; no subir si la CE ya esta alta.',
      pHint: 'Si el suelo esta frio o alcalino, P colocado pesa mas que N.',
      confidence: 0.66,
    ),
    GarlicStageKey.emergenceEstablishment: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStart,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 18,
      nOptMin: 26,
      nOptMax: 42,
      pLow: 42,
      pOptMin: 55,
      pOptMax: 78,
      kLow: 85,
      kOptMin: 105,
      kOptMax: 145,
      nPriority: 0.36,
      pPriority: 0.76,
      kPriority: 0.42,
      nWindow: 'N suave de establecimiento',
      pWindow: 'Pegue y raiz joven',
      kWindow: 'Balance temprano',
      nGuide:
          'N bajo a moderado; si el stand falla, revisar diente, raiz, humedad y sales antes que N.',
      pGuide:
          'P es sensible en raiz temprana, siempre segun analisis de suelo.',
      kGuide: 'K acompana sin subir CE cerca de raiz joven.',
      nHint: 'Emergencia despareja rara vez se arregla con mas nitrogeno.',
      confidence: 0.74,
    ),
    GarlicStageKey.vegetativeLeafDevelopment: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 40,
      nOptMin: 54,
      nOptMax: 82,
      pLow: 30,
      pOptMin: 40,
      pOptMax: 60,
      kLow: 115,
      kOptMin: 140,
      kOptMax: 185,
      nPriority: 0.72,
      pPriority: 0.42,
      kPriority: 0.58,
      nWindow: 'Construir hoja funcional',
      pWindow: 'Soporte de raiz',
      kWindow: 'Reserva para bulbo',
      nGuide:
          'N temprano ayuda a hoja sana, pero sin excesos: demasiado vigor complica bulbo, maduracion y curado.',
      pGuide: 'P pasa a soporte; el arranque ya debio resolverse.',
      kGuide: 'K prepara turgencia y reservas para diferenciacion.',
      nHint: 'Mas follaje no garantiza mas dientes si falta frio fisiologico.',
      confidence: 0.82,
    ),
    GarlicStageKey.coldInductionVernalization: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 36,
      nOptMin: 48,
      nOptMax: 70,
      pLow: 26,
      pOptMin: 34,
      pOptMax: 54,
      kLow: 125,
      kOptMin: 150,
      kOptMax: 198,
      nPriority: 0.46,
      pPriority: 0.34,
      kPriority: 0.62,
      nWindow: 'N con freno: frio manda',
      pWindow: 'P de soporte',
      kWindow: 'Preparar diferenciacion',
      nGuide:
          'La vernalizacion define dientes: mas NPK no corrige falta de frio. Mantener equilibrio y registrar clima.',
      pGuide: 'P de soporte; no desplaza la prioridad del frio fisiologico.',
      kGuide: 'K medio-alto solo si suelo y CE lo permiten.',
      nHint: 'No recomendar fertilizante para corregir mala vernalizacion.',
      kHint: 'K no compensa frio insuficiente ni salinidad.',
      confidence: 0.76,
    ),
    GarlicStageKey.bulbDifferentiation: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempBulb,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 30,
      nOptMin: 40,
      nOptMax: 60,
      pLow: 22,
      pOptMin: 30,
      pOptMax: 48,
      kLow: 150,
      kOptMin: 180,
      kOptMax: 235,
      nPriority: 0.34,
      pPriority: 0.28,
      kPriority: 0.82,
      nWindow: 'Bajar N, definir dientes',
      pWindow: 'P de mantenimiento',
      kWindow: 'Diferenciacion y firmeza',
      nGuide:
          'Baja intensidad de N. N alto aqui puede provocar exceso de vigor, escobeteado/canutos y mala maduracion.',
      pGuide: 'P rara vez rescata esta etapa salvo deficiencia comprobada.',
      kGuide:
          'K alto relativo sostiene diferenciacion y firmeza si humedad y CE estan en rango.',
      nHint:
          'Si hay mucha hoja y poco bulbo, revisar frio/variedad/fecha antes que N.',
      kHint: 'Si CE esta alta, no subir K como primera respuesta.',
      confidence: 0.82,
    ),
    GarlicStageKey.bulbFilling: _targets(
      moisture: _moistureActive,
      soilTemp: _soilTempBulb,
      ph: _phStd,
      ec: _ecStrict,
      nLow: 22,
      nOptMin: 30,
      nOptMax: 50,
      pLow: 18,
      pOptMin: 26,
      pOptMax: 42,
      kLow: 170,
      kOptMin: 205,
      kOptMax: 265,
      nPriority: 0.24,
      pPriority: 0.22,
      kPriority: 0.90,
      nWindow: 'N a la baja',
      pWindow: 'P de cierre',
      kWindow: 'Llenado y calidad',
      nGuide:
          'No empujar N en llenado: protege calibre real, maduracion, sanidad y curado.',
      pGuide:
          'P bajo-medio segun analisis; no decide el calibre en esta ventana.',
      kGuide:
          'K es clave para llenado y firmeza, pero no compensa deficit hidrico, anoxia o salinidad.',
      nHint: 'N tardio aumenta riesgo de pudriciones y mal curado.',
      kHint: 'Antes de subir K, revisar CE, agua y raiz.',
      confidence: 0.86,
    ),
    GarlicStageKey.bulbMaturation: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 12,
      nOptMin: 18,
      nOptMax: 30,
      pLow: 14,
      pOptMin: 20,
      pOptMax: 36,
      kLow: 115,
      kOptMin: 145,
      kOptMax: 190,
      nPriority: 0.10,
      pPriority: 0.14,
      kPriority: 0.40,
      nWindow: 'Detener N',
      pWindow: 'Cierre de P',
      kWindow: 'Solo mantenimiento',
      nGuide:
          'Detener N: maduracion y curado valen mas que seguir verde. Evita canutos, pudriciones y mal almacenamiento.',
      pGuide: 'P ya no decide; guardar lectura para el siguiente ciclo.',
      kGuide:
          'K solo mantenimiento si hay deficiencia comprobada; no corregir tarde.',
      nHint: 'Bloquear o bajar fuerza de N en maduracion.',
      confidence: 0.78,
    ),
    GarlicStageKey.harvest: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 10,
      nOptMin: 14,
      nOptMax: 26,
      pLow: 12,
      pOptMin: 18,
      pOptMax: 32,
      kLow: 95,
      kOptMin: 120,
      kOptMax: 165,
      nPriority: 0.06,
      pPriority: 0.10,
      kPriority: 0.24,
      nWindow: 'Sin impulso de N',
      pWindow: 'Registro de cierre',
      kWindow: 'Registro de cierre',
      nGuide: 'Cosecha no es ventana de NPK; decidir corte, descarte y curado.',
      pGuide: 'Usar lectura para planear base del siguiente ciclo.',
      kGuide: 'K no corrige calibre en cosecha; prioriza manejo sin golpes.',
      nHint: 'No fertilizar para rescatar cosecha.',
      confidence: 0.62,
    ),
    GarlicStageKey.curingRest: _targets(
      moisture: _moistureCuring,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 8,
      nOptMin: 12,
      nOptMax: 22,
      pLow: 10,
      pOptMin: 14,
      pOptMax: 28,
      kLow: 80,
      kOptMin: 100,
      kOptMax: 145,
      nPriority: 0.04,
      pPriority: 0.06,
      kPriority: 0.12,
      nWindow: 'Curado: no NPK',
      pWindow: 'Trazabilidad',
      kWindow: 'Trazabilidad',
      nGuide:
          'Curado deficiente reduce rendimiento comercial/almacenado; no se corrige con fertilizante.',
      pGuide: 'Registrar para siguiente ciclo.',
      kGuide: 'Registrar para siguiente ciclo.',
      nHint: 'Prioriza ventilacion, sombra, cuello seco y seleccion de bulbos.',
      confidence: 0.54,
    ),
    GarlicStageKey.scapeBrooming: _targets(
      moisture: _moistureLate,
      soilTemp: _soilTempStd,
      ph: _phStd,
      ec: _ecLate,
      nLow: 8,
      nOptMin: 12,
      nOptMax: 22,
      pLow: 10,
      pOptMin: 14,
      pOptMax: 28,
      kLow: 80,
      kOptMin: 100,
      kOptMax: 145,
      nPriority: 0.04,
      pPriority: 0.06,
      kPriority: 0.12,
      nWindow: 'Evento: no empujar N',
      pWindow: 'Registro de causa',
      kWindow: 'Registro de causa',
      nGuide:
          'Escapo/canuto/escobeteado es evento de riesgo: no fertilizar como etapa productiva.',
      pGuide: 'Registrar frio, variedad, fecha, N tardio y estres.',
      kGuide: 'K no revierte escobeteado; decide cosecha/cierre.',
      nHint: 'Bloquear N fuerte si hay escapo o canutos.',
      confidence: 0.50,
    ),
  },
  weights: const <GarlicStageKey, StageWeights>{
    GarlicStageKey.clovePlanting: StageWeights(
      moisture: 0.30,
      soilTemp: 0.20,
      resistance: 0.22,
      ph: 0.05,
      ec: 0.13,
      npk: 0.10,
    ),
    GarlicStageKey.emergenceEstablishment: StageWeights(
      moisture: 0.30,
      soilTemp: 0.20,
      resistance: 0.20,
      ph: 0.05,
      ec: 0.12,
      npk: 0.13,
    ),
    GarlicStageKey.vegetativeLeafDevelopment: StageWeights(
      moisture: 0.25,
      soilTemp: 0.18,
      resistance: 0.12,
      ph: 0.05,
      ec: 0.10,
      npk: 0.30,
    ),
    GarlicStageKey.coldInductionVernalization: StageWeights(
      moisture: 0.22,
      soilTemp: 0.23,
      resistance: 0.12,
      ph: 0.05,
      ec: 0.10,
      npk: 0.28,
    ),
    GarlicStageKey.bulbDifferentiation: StageWeights(
      moisture: 0.30,
      soilTemp: 0.18,
      resistance: 0.10,
      ph: 0.05,
      ec: 0.12,
      npk: 0.25,
    ),
    GarlicStageKey.bulbFilling: StageWeights(
      moisture: 0.34,
      soilTemp: 0.18,
      resistance: 0.12,
      ph: 0.04,
      ec: 0.14,
      npk: 0.18,
    ),
    GarlicStageKey.bulbMaturation: StageWeights(
      moisture: 0.24,
      soilTemp: 0.16,
      resistance: 0.08,
      ph: 0.05,
      ec: 0.14,
      npk: 0.23,
    ),
    GarlicStageKey.harvest: StageWeights(
      moisture: 0.12,
      soilTemp: 0.20,
      resistance: 0.05,
      ph: 0.04,
      ec: 0.12,
      npk: 0.12,
    ),
    GarlicStageKey.curingRest: StageWeights(
      moisture: 0.05,
      soilTemp: 0.20,
      resistance: 0.02,
      ph: 0.02,
      ec: 0.05,
      npk: 0.04,
    ),
    GarlicStageKey.scapeBrooming: StageWeights(
      moisture: 0.18,
      soilTemp: 0.22,
      resistance: 0.08,
      ph: 0.05,
      ec: 0.12,
      npk: 0.25,
    ),
  },
);
