import 'package:bio_g/core/agro/agro_types.dart';
import 'package:bio_g/core/crops/crop_target_models.dart';
import 'package:bio_g/widgets/seeds/chili_models.dart';

class ChiliUniversalProfile {
  const ChiliUniversalProfile({
    required this.byStage,
    required this.weights,
  });

  final Map<ChiliStageKey, StageTargets> byStage;
  final Map<ChiliStageKey, StageWeights> weights;
}

const AgroRange _phEarly = AgroRange(
  lowMax: 5.5,
  optimalMin: 5.8,
  optimalMax: 6.8,
  highMin: 7.2,
);

const AgroRange _phVeg = AgroRange(
  lowMax: 5.5,
  optimalMin: 6.0,
  optimalMax: 7.2,
  highMin: 7.6,
);

const AgroRange _phFlowering = AgroRange(
  lowMax: 5.6,
  optimalMin: 6.0,
  optimalMax: 7.0,
  highMin: 7.3,
);

const AgroRange _phLate = AgroRange(
  lowMax: 5.5,
  optimalMin: 5.8,
  optimalMax: 7.2,
  highMin: 7.6,
);

const AgroRange _ecEarly = AgroRange(
  lowMax: 0.5,
  optimalMin: 0.7,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecVeg = AgroRange(
  lowMax: 0.6,
  optimalMin: 0.9,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecProd = AgroRange(
  lowMax: 0.7,
  optimalMin: 1.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _ecLate = AgroRange(
  lowMax: 0.6,
  optimalMin: 0.8,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _resistance = AgroRange(
  lowMax: -1.0,
  optimalMin: 0.0,
  optimalMax: 1.5,
  highMin: 2.0,
);

const AgroRange _soilTempEarly = AgroRange(
  lowMax: 15,
  optimalMin: 20,
  optimalMax: 28,
  highMin: 32,
);

const AgroRange _soilTempStd = AgroRange(
  lowMax: 14,
  optimalMin: 18,
  optimalMax: 28,
  highMin: 33,
);

StageTargets _targets({
  required AgroRange moisture,
  required AgroRange soilTemp,
  required AgroRange ph,
  required AgroRange ec,
  required double nLow,
  required double nOptMin,
  required double nOptMax,
  required double pLow,
  required double pOptMin,
  required double pOptMax,
  required double kLow,
  required double kOptMin,
  required double kOptMax,
  required double nPriority,
  required double pPriority,
  required double kPriority,
  required double caPriority,
  required double mgPriority,
  required double sPriority,
  required String nWindow,
  required String pWindow,
  required String kWindow,
  required String nGuide,
  required String pGuide,
  required String kGuide,
  required String caGuide,
  required String mgGuide,
  required String sGuide,
  String? nHint,
  String? pHint,
  String? kHint,
  double confidence = 0.78,
}) {
  AgroRange idx(double p) => AgroRange(
        lowMax: (p * 100 - 12).clamp(0, 100).toDouble(),
        optimalMin: (p * 100 - 5).clamp(0, 100).toDouble(),
        optimalMax: (p * 100 + 12).clamp(0, 100).toDouble(),
        highMin: (p * 100 + 22).clamp(0, 100).toDouble(),
      );

  AgroRange ppm(double low, double min, double max) => AgroRange(
        lowMax: low,
        optimalMin: min,
        optimalMax: max,
        highMin: max + (max - min) * 0.55,
      );

  return StageTargets(
    moistureRaw: moisture,
    soilTemp: soilTemp,
    ph: ph,
    ec: ec,
    resistance: _resistance,
    nIndex: idx(nPriority),
    pIndex: idx(pPriority),
    kIndex: idx(kPriority),
    nSoilPpmRange: ppm(nLow, nOptMin, nOptMax),
    pSoilPpmRange: ppm(pLow, pOptMin, pOptMax),
    kSoilPpmRange: ppm(kLow, kOptMin, kOptMax),
    nPriority: nPriority,
    pPriority: pPriority,
    kPriority: kPriority,
    caPriority: caPriority,
    mgPriority: mgPriority,
    sPriority: sPriority,
    nWindowLabelEs: nWindow,
    pWindowLabelEs: pWindow,
    kWindowLabelEs: kWindow,
    nShortGuidanceEs: nGuide,
    pShortGuidanceEs: pGuide,
    kShortGuidanceEs: kGuide,
    caShortGuidanceEs: caGuide,
    mgShortGuidanceEs: mgGuide,
    sShortGuidanceEs: sGuide,
    nPlannerHintEs: nHint,
    pPlannerHintEs: pHint,
    kPlannerHintEs: kHint,
    nConfidence01: confidence,
    pConfidence01: confidence,
    kConfidence01: confidence,
  );
}

final ChiliUniversalProfile chiliUniversalV1 = ChiliUniversalProfile(
  byStage: <ChiliStageKey, StageTargets>{
    ChiliStageKey.germinacion: _targets(
      moisture: const AgroRange(
        lowMax: 35,
        optimalMin: 55,
        optimalMax: 80,
        highMin: 88,
      ),
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 22,
      nOptMin: 28,
      nOptMax: 55,
      pLow: 40,
      pOptMin: 48,
      pOptMax: 72,
      kLow: 55,
      kOptMin: 70,
      kOptMax: 120,
      nPriority: 0.22,
      pPriority: 0.78,
      kPriority: 0.30,
      caPriority: 0.38,
      mgPriority: 0.30,
      sPriority: 0.24,
      nWindow: 'Arranque prudente de N',
      pWindow: 'Raiz y energia inicial',
      kWindow: 'Soporte minimo de K',
      nGuide: 'N bajo control; exceso afecta emergencia.',
      pGuide: 'P temprano sostiene raiz y arranque.',
      kGuide: 'K solo como base inicial.',
      caGuide: 'Ca de base para estructura.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S en mantenimiento.',
      confidence: 0.72,
    ),
    ChiliStageKey.establecimiento: _targets(
      moisture: const AgroRange(
        lowMax: 38,
        optimalMin: 58,
        optimalMax: 82,
        highMin: 90,
      ),
      soilTemp: _soilTempEarly,
      ph: _phEarly,
      ec: _ecEarly,
      nLow: 30,
      nOptMin: 38,
      nOptMax: 62,
      pLow: 42,
      pOptMin: 52,
      pOptMax: 76,
      kLow: 65,
      kOptMin: 80,
      kOptMax: 125,
      nPriority: 0.42,
      pPriority: 0.82,
      kPriority: 0.40,
      caPriority: 0.55,
      mgPriority: 0.38,
      sPriority: 0.30,
      nWindow: 'Soporte moderado de N',
      pWindow: 'Pegue y raiz',
      kWindow: 'Balance inicial',
      nGuide: 'N acompana sin forzar follaje.',
      pGuide: 'P starter es clave para pegue y raiz.',
      kGuide: 'K acompana balance hidrico temprano.',
      caGuide: 'Ca empieza a sostener pared celular.',
      mgGuide: 'Mg apoya primeras hojas.',
      sGuide: 'S en soporte base.',
      nHint: 'Evitar pulsos fuertes de N en plantula o trasplante reciente.',
      pHint: 'Corregir P temprano si la lectura queda corta.',
      kHint: 'Mantener K de base sin subir sales.',
      confidence: 0.80,
    ),
    ChiliStageKey.vegetativo: _targets(
      moisture: const AgroRange(
        lowMax: 40,
        optimalMin: 58,
        optimalMax: 80,
        highMin: 88,
      ),
      soilTemp: _soilTempStd,
      ph: _phVeg,
      ec: _ecVeg,
      nLow: 50,
      nOptMin: 60,
      nOptMax: 95,
      pLow: 36,
      pOptMin: 45,
      pOptMax: 68,
      kLow: 80,
      kOptMin: 100,
      kOptMax: 150,
      nPriority: 0.74,
      pPriority: 0.52,
      kPriority: 0.58,
      caPriority: 0.58,
      mgPriority: 0.50,
      sPriority: 0.38,
      nWindow: 'Follaje con mesura',
      pWindow: 'Soporte de P',
      kWindow: 'Reserva antes de flor',
      nGuide: 'N importante para follaje, sin sobredimensionarlo.',
      pGuide: 'P pasa a soporte; corregir si queda corto.',
      kGuide: 'K sube gradualmente antes de floracion.',
      caGuide: 'Ca sostiene estructura y brotes.',
      mgGuide: 'Mg sostiene fotosintesis.',
      sGuide: 'S apoya vigor y calidad.',
      nHint: 'No llegar a floracion con exceso vegetativo.',
      kHint: 'Preparar reserva de K para floracion y cuajado.',
      confidence: 0.84,
    ),
    ChiliStageKey.floracion: _targets(
      moisture: const AgroRange(
        lowMax: 42,
        optimalMin: 60,
        optimalMax: 82,
        highMin: 88,
      ),
      soilTemp: _soilTempStd,
      ph: _phFlowering,
      ec: _ecProd,
      nLow: 42,
      nOptMin: 50,
      nOptMax: 82,
      pLow: 34,
      pOptMin: 42,
      pOptMax: 65,
      kLow: 95,
      kOptMin: 120,
      kOptMax: 165,
      nPriority: 0.60,
      pPriority: 0.48,
      kPriority: 0.74,
      caPriority: 0.78,
      mgPriority: 0.58,
      sPriority: 0.42,
      nWindow: 'N equilibrado para flor',
      pWindow: 'Energia reproductiva',
      kWindow: 'K subiendo para amarre',
      nGuide: 'N se modera: exceso tumba flor y retrasa cuaje.',
      pGuide: 'P sostiene energia de floracion.',
      kGuide: 'K empieza a mandar; mantener humedad pareja.',
      caGuide: 'Ca importante antes del fruto joven.',
      mgGuide: 'Mg sostiene hoja activa.',
      sGuide: 'S acompana calidad.',
      nHint: 'Evitar aplicaciones altas de N en floracion.',
      pHint: 'P solo si lectura o analisis lo justifica.',
      kHint: 'Subir K sin golpes de sales.',
      confidence: 0.86,
    ),
    ChiliStageKey.cuajado: _targets(
      moisture: const AgroRange(
        lowMax: 44,
        optimalMin: 62,
        optimalMax: 82,
        highMin: 88,
      ),
      soilTemp: _soilTempStd,
      ph: _phFlowering,
      ec: _ecProd,
      nLow: 38,
      nOptMin: 45,
      nOptMax: 75,
      pLow: 32,
      pOptMin: 40,
      pOptMax: 62,
      kLow: 110,
      kOptMin: 135,
      kOptMax: 180,
      nPriority: 0.54,
      pPriority: 0.44,
      kPriority: 0.86,
      caPriority: 0.88,
      mgPriority: 0.62,
      sPriority: 0.42,
      nWindow: 'N moderado para cuaje',
      pWindow: 'P de soporte',
      kWindow: 'K fuerte para amarre',
      nGuide: 'N bajo control para no tirar flor ni cuaje.',
      pGuide: 'P acompana, pero no es rescate tardio.',
      kGuide: 'K y Ca son la prioridad del amarre.',
      caGuide: 'Ca clave para calidad inicial del fruto.',
      mgGuide: 'Mg sostiene fotosintesis de planta cargada.',
      sGuide: 'S en soporte.',
      nHint: 'No meter pulsos altos de N en amarre activo.',
      pHint: 'Corregir P solo si esta realmente corto.',
      kHint: 'Si K cae, corregir con prioridad y humedad estable.',
      confidence: 0.88,
    ),
    ChiliStageKey.llenado: _targets(
      moisture: const AgroRange(
        lowMax: 44,
        optimalMin: 62,
        optimalMax: 80,
        highMin: 86,
      ),
      soilTemp: _soilTempStd,
      ph: _phVeg,
      ec: _ecProd,
      nLow: 32,
      nOptMin: 38,
      nOptMax: 68,
      pLow: 28,
      pOptMin: 36,
      pOptMax: 58,
      kLow: 115,
      kOptMin: 140,
      kOptMax: 190,
      nPriority: 0.46,
      pPriority: 0.36,
      kPriority: 0.90,
      caPriority: 0.78,
      mgPriority: 0.62,
      sPriority: 0.40,
      nWindow: 'N a la baja',
      pWindow: 'P de mantenimiento',
      kWindow: 'K dominante para llenado',
      nGuide: 'N baja; exceso resta calidad y abre vegetatividad.',
      pGuide: 'P de soporte, respuesta moderada.',
      kGuide: 'K domina llenado, color, firmeza y peso.',
      caGuide: 'Ca cuida pared, firmeza y calidad.',
      mgGuide: 'Mg sostiene llenado desde hoja sana.',
      sGuide: 'S acompana calidad.',
      nHint: 'No perseguir N como cuello principal en llenado.',
      kHint: 'Priorizar K soluble sin golpes osmoticamente fuertes.',
      confidence: 0.88,
    ),
    ChiliStageKey.cosechaProgresiva: _targets(
      moisture: const AgroRange(
        lowMax: 40,
        optimalMin: 58,
        optimalMax: 78,
        highMin: 86,
      ),
      soilTemp: _soilTempStd,
      ph: _phVeg,
      ec: _ecProd,
      nLow: 30,
      nOptMin: 35,
      nOptMax: 65,
      pLow: 26,
      pOptMin: 34,
      pOptMax: 56,
      kLow: 110,
      kOptMin: 135,
      kOptMax: 185,
      nPriority: 0.45,
      pPriority: 0.34,
      kPriority: 0.86,
      caPriority: 0.72,
      mgPriority: 0.58,
      sPriority: 0.38,
      nWindow: 'N de mantenimiento',
      pWindow: 'P de mantenimiento',
      kWindow: 'K sostenido de cosecha',
      nGuide: 'N solo para sostener brotes productivos.',
      pGuide: 'P rara vez es el cuello en cosecha.',
      kGuide: 'K sostenido mantiene cortes, calidad y firmeza.',
      caGuide: 'Ca mantiene firmeza en cortes continuos.',
      mgGuide: 'Mg sostiene hoja funcional.',
      sGuide: 'S en soporte.',
      nHint: 'Evitar exceso de N en cosecha progresiva.',
      kHint: 'Mantener K constante y balanceado con Ca/Mg.',
      confidence: 0.82,
    ),
    ChiliStageKey.finCiclo: _targets(
      moisture: const AgroRange(
        lowMax: 22,
        optimalMin: 35,
        optimalMax: 60,
        highMin: 75,
      ),
      soilTemp: _soilTempStd,
      ph: _phLate,
      ec: _ecLate,
      nLow: 18,
      nOptMin: 22,
      nOptMax: 48,
      pLow: 20,
      pOptMin: 25,
      pOptMax: 50,
      kLow: 75,
      kOptMin: 90,
      kOptMax: 150,
      nPriority: 0.20,
      pPriority: 0.18,
      kPriority: 0.32,
      caPriority: 0.28,
      mgPriority: 0.25,
      sPriority: 0.20,
      nWindow: 'Cierre de N',
      pWindow: 'Cierre de P',
      kWindow: 'Cierre de K',
      nGuide: 'Lectura para planear el siguiente ciclo.',
      pGuide: 'P sirve mas para ajustar la siguiente base.',
      kGuide: 'K solo sostiene cosecha residual.',
      caGuide: 'Ca ya no corrige calidad del fruto actual.',
      mgGuide: 'Mg en mantenimiento.',
      sGuide: 'S en mantenimiento.',
      nHint: 'No corregir tarde; documentar y cerrar.',
      pHint: 'Usar lectura para pre-siembra del siguiente ciclo.',
      kHint: 'Usar lectura para trazabilidad del plan.',
      confidence: 0.66,
    ),
  },
  weights: const <ChiliStageKey, StageWeights>{
    ChiliStageKey.germinacion: StageWeights(
      moisture: 0.32,
      soilTemp: 0.11,
      resistance: 0.12,
      ph: 0.12,
      ec: 0.14,
      npk: 0.19,
    ),
    ChiliStageKey.establecimiento: StageWeights(
      moisture: 0.30,
      soilTemp: 0.10,
      resistance: 0.12,
      ph: 0.12,
      ec: 0.12,
      npk: 0.24,
    ),
    ChiliStageKey.vegetativo: StageWeights(
      moisture: 0.27,
      soilTemp: 0.07,
      resistance: 0.10,
      ph: 0.10,
      ec: 0.12,
      npk: 0.34,
    ),
    ChiliStageKey.floracion: StageWeights(
      moisture: 0.31,
      soilTemp: 0.07,
      resistance: 0.08,
      ph: 0.10,
      ec: 0.13,
      npk: 0.31,
    ),
    ChiliStageKey.cuajado: StageWeights(
      moisture: 0.33,
      soilTemp: 0.07,
      resistance: 0.07,
      ph: 0.08,
      ec: 0.14,
      npk: 0.31,
    ),
    ChiliStageKey.llenado: StageWeights(
      moisture: 0.31,
      soilTemp: 0.06,
      resistance: 0.07,
      ph: 0.08,
      ec: 0.14,
      npk: 0.34,
    ),
    ChiliStageKey.cosechaProgresiva: StageWeights(
      moisture: 0.29,
      soilTemp: 0.06,
      resistance: 0.08,
      ph: 0.08,
      ec: 0.14,
      npk: 0.35,
    ),
    ChiliStageKey.finCiclo: StageWeights(
      moisture: 0.22,
      soilTemp: 0.06,
      resistance: 0.14,
      ph: 0.14,
      ec: 0.14,
      npk: 0.30,
    ),
  },
);
