import 'package:bio_g/core/crops/catalog/crop_catalog_models.dart';
import 'package:bio_g/widgets/seeds/onion_profiles.dart';

const String kCropOnion = 'onion';
const String kOnionDefaultCalendarId = 'onion_default';

const List<CropProfileEntry> onionProfileEntries = [
  CropProfileEntry(
    id: kOnGen,
    label: 'ON-GEN - No sé / Otra cebolla',
    cropId: kCropOnion,
    subtitle:
        'Perfil general de cebolla, conservador y migrable — cambias el tipo '
        'después sin perder historial',
    aliases: [
      'ON-GEN',
      'ONGEN',
      'ON_GEN',
      'Cebolla',
      'Cebolla generica',
      'Otra cebolla',
      'Otra variedad',
      'No se',
      'No se todavia',
      'No sé',
      'No sé todavía',
      'Onion',
    ],
  ),
  CropProfileEntry(
    id: kOn01,
    label: 'ON-01 - Cebolla blanca grano/bola',
    cropId: kCropOnion,
    subtitle:
        'Cebolla blanca de siembra otoño-invierno, bulbo de bola o grano para '
        'fresco nacional y bodega',
    aliases: [
      'ON-01',
      'ON01',
      'Cebolla blanca',
      'Blanca grano',
      'Blanca bola',
      'White onion',
      'SV4043NM',
      'SV7030NS',
      'AJUSCO',
      'Stratus',
      'EX 6800',
      'Stratus / EX 6800',
      'LA JOYA',
      'XON570W',
      'Bella Luna',
      'Carta Blanca',
      'Otra blanca dia corto',
      'Otra blanca día corto',
    ],
  ),
  CropProfileEntry(
    id: kOn02,
    label: 'ON-02 - Cebolla amarilla/dorada',
    cropId: kCropOnion,
    subtitle:
        'Cebolla amarilla o dorada de siembra otoño-invierno, para fresco de '
        'alto volumen y tipo dulce',
    aliases: [
      'ON-02',
      'ON02',
      'Cebolla amarilla',
      'Cebolla dorada',
      'Yellow onion',
      'PECOS',
      'Nomad',
      'SV2623NN',
      'Nomad / SV2623NN',
      'Plethora',
      'Granex',
      'Texas Grano',
      'Texas Grano / Granex',
      'Otra amarilla dia corto',
      'Otra amarilla día corto',
    ],
  ),
  CropProfileEntry(
    id: kOn03,
    label: 'ON-03 - Cebolla morada',
    cropId: kCropOnion,
    subtitle:
        'Cebolla morada de siembra otoño-invierno, se vende por su color en '
        'mercado regional y en fresco',
    aliases: [
      'ON-03',
      'ON03',
      'Cebolla morada',
      'Cebolla roja',
      'Red onion',
      'Rasta',
      'NuMex Crimson',
      'Rojas regionales',
      'Otra morada dia corto',
      'Otra morada día corto',
    ],
  ),
  CropProfileEntry(
    id: kOn04,
    label: 'ON-04 - Cebolla de transicion / dia intermedio',
    cropId: kCropOnion,
    subtitle:
        'Cebolla de transición o día intermedio, para altiplano templado, de '
        'bulbo grande y buena bodega',
    aliases: [
      'ON-04',
      'ON04',
      'Transicion',
      'Dia intermedio',
      'Altiplano',
      'Cimarron',
      'Cimarrón',
      'Super Luna',
      'Súper Luna',
      'NUN 6005',
      'NuMex Allure',
      'Otra dia intermedio',
      'Otra día intermedio',
    ],
  ),
  CropProfileEntry(
    id: kOn05,
    label: 'ON-05 - Cebolla en rama / cambray / manojo',
    cropId: kCropOnion,
    subtitle:
        'Cebolla cortada joven, con hoja verde y base apenas engrosada, para '
        'vender en manojo (cambray)',
    aliases: [
      'ON-05',
      'ON05',
      'Cambray',
      'Cebolla cambray',
      'Rama',
      'Cebollin',
      'Manojo',
      'Green onion',
      'SV4522NB',
      'Baja Verde',
      'Otra cambray',
      'Otra rama',
      'Otra cambray / rama',
    ],
  ),
];

const List<CropVarietyEntry> onionVarieties = [
  CropVarietyEntry(
    id: 'onion_generic',
    label: 'No sé / Otra cebolla',
    cropId: kCropOnion,
    subtitle:
        'Perfil general de cebolla, seguro y migrable — lo ajustas después sin '
        'reiniciar tu historial',
    defaultProfileId: kOnGen,
    aliases: [
      'Cebolla',
      'Cebolla generica',
      'Otra cebolla',
      'Otra variedad',
      'No se',
      'No se todavia',
      'No sé',
      'No sé todavía',
      'Onion',
      'ON-GEN',
      'ONGEN',
    ],
    isGeneric: true,
  ),
  CropVarietyEntry(
    id: 'onion_white',
    label: 'Cebolla blanca grano/bola',
    cropId: kCropOnion,
    subtitle:
        'Tipo blanca de siembra otoño-invierno, bulbo de bola o grano para '
        'fresco de mercado nacional',
    defaultProfileId: kOn01,
    aliases: [
      'Cebolla blanca',
      'Blanca grano',
      'Blanca bola',
      'White onion',
      'SV4043NM',
      'SV7030NS',
      'AJUSCO',
      'Stratus',
      'EX 6800',
      'Stratus / EX 6800',
      'LA JOYA',
      'XON570W',
      'Bella Luna',
      'Carta Blanca',
      'Otra blanca dia corto',
      'Otra blanca día corto',
      'ON-01',
      'ON01',
    ],
  ),
  CropVarietyEntry(
    id: 'onion_yellow',
    label: 'Cebolla amarilla/dorada',
    cropId: kCropOnion,
    subtitle:
        'Tipo amarilla o dorada de siembra otoño-invierno, para fresco de alto '
        'volumen y también dulce',
    defaultProfileId: kOn02,
    aliases: [
      'Cebolla amarilla',
      'Cebolla dorada',
      'Yellow onion',
      'PECOS',
      'Nomad',
      'SV2623NN',
      'Nomad / SV2623NN',
      'Plethora',
      'Texas Grano',
      'Granex',
      'Texas Grano / Granex',
      'Otra amarilla dia corto',
      'Otra amarilla día corto',
      'ON-02',
      'ON02',
    ],
  ),
  CropVarietyEntry(
    id: 'onion_purple',
    label: 'Cebolla morada',
    cropId: kCropOnion,
    subtitle:
        'Tipo morada de siembra otoño-invierno, se vende por su color fuerte '
        'en el mercado regional',
    defaultProfileId: kOn03,
    aliases: [
      'Cebolla morada',
      'Cebolla roja',
      'Red onion',
      'Purple onion',
      'Rasta',
      'NuMex Crimson',
      'Rojas regionales',
      'Otra morada dia corto',
      'Otra morada día corto',
      'ON-03',
      'ON03',
    ],
  ),
  CropVarietyEntry(
    id: 'onion_transition',
    label: 'Cebolla de transicion / dia intermedio',
    cropId: kCropOnion,
    subtitle:
        'Tipo de transición o día intermedio, para siembras de altiplano y '
        'clima templado',
    defaultProfileId: kOn04,
    aliases: [
      'Transicion',
      'Dia intermedio',
      'Intermedia',
      'Altiplano',
      'Cimarron',
      'NUN 6005',
      'Super Luna',
      'NuMex Allure',
      'Otra dia intermedio',
      'Otra día intermedio',
      'ON-04',
      'ON04',
    ],
  ),
  CropVarietyEntry(
    id: 'onion_cambray',
    label: 'Cebolla en rama / cambray / manojo',
    cropId: kCropOnion,
    subtitle:
        'Tipo que se cosecha joven, con hoja verde y base apenas engrosada, '
        'para vender en manojo',
    defaultProfileId: kOn05,
    aliases: [
      'Cambray',
      'Cebolla cambray',
      'Rama',
      'Cebolla de rama',
      'Cebollin',
      'Manojo',
      'Green onion',
      'Bunching onion',
      'SV4522NB',
      'Baja Verde',
      'Otra cambray',
      'Otra rama',
      'Otra cambray / rama',
      'ON-05',
      'ON05',
    ],
  ),
];
